//! # zkVM Proof Verification Adapter
//!
//! Adapter for zero-knowledge virtual machine proof verification. This adapter
//! does NOT hold funds - it verifies execution proofs, route proofs, and state
//! proofs generated by zkVMs (RISC Zero, SP1, zkWasm, etc.).
//!
//! ## Design
//!
//! Unlike fund-holding adapters (EVM, SVM, etc.), the zkVM adapter:
//! - Returns `Err(SwapError::Unsupported)` for `lock()`, `claim()`, `refund()`
//! - Returns `Ok(false)` for `verify_lock()`, `verify_claim()`, `verify_refund()`
//! - Provides extra proof verification methods (`verify_route_proof`, etc.)
//! - Reports 0 native fee (no on-chain costs for proof verification)
//! - Reports `finalized=true` (proof verification is instantaneously final)

use crate::adapter::{
    AdapterReadinessScore, AssetId, ChainHealth, ChainId, ClaimProof, FeeEstimate, FinalityProof,
    LockProof, RefundProof, TxId, VmType, X3VmAdapter,
};
use crate::error::SwapError;
use crate::intent::{AtomicIntent, IntentId};
use alloc::string::String;
use alloc::vec::Vec;
use sha2::Digest;

// ─────────────────────────────────────────────────────────────────────────────
// zkVM Types
// ─────────────────────────────────────────────────────────────────────────────

/// Supported zkVM targets.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum ZkVmTarget {
    RiscZero,
    Sp1,
    ZkWasm,
    Future,
}

impl ZkVmTarget {
    /// Get the target name string.
    pub fn name(&self) -> &'static str {
        match self {
            ZkVmTarget::RiscZero => "risc0",
            ZkVmTarget::Sp1 => "sp1",
            ZkVmTarget::ZkWasm => "zkwasm",
            ZkVmTarget::Future => "future",
        }
    }
}

/// Type of zero-knowledge proof.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum ZkProofType {
    RouteCorrectness,
    FinalityCompression,
    RelayerExecution,
    SolverQuoteValidity,
    StateTransitionValidity,
    AgentCompletionProof,
}

impl ZkProofType {
    /// Get the proof type name string.
    pub fn name(&self) -> &'static str {
        match self {
            ZkProofType::RouteCorrectness => "route_correctness",
            ZkProofType::FinalityCompression => "finality_compression",
            ZkProofType::RelayerExecution => "relayer_execution",
            ZkProofType::SolverQuoteValidity => "solver_quote_validity",
            ZkProofType::StateTransitionValidity => "state_transition_validity",
            ZkProofType::AgentCompletionProof => "agent_completion_proof",
        }
    }
}

/// Record of a verified or rejected zero-knowledge proof.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ZkProofRecord {
    /// Unique proof identifier.
    pub proof_id: String,
    /// Type of proof.
    pub proof_type: ZkProofType,
    /// Target VM that generated the proof.
    pub vm_target: ZkVmTarget,
    /// Public inputs to the proof.
    pub public_inputs: Vec<u8>,
    /// Public outputs from the proof.
    pub public_outputs: Vec<u8>,
    /// Whether the proof has been verified.
    pub verified: bool,
    /// Timestamp (block number or unix time) when verified.
    pub verified_at: u64,
}

// ─────────────────────────────────────────────────────────────────────────────
// ZkVmAdapter
// ─────────────────────────────────────────────────────────────────────────────

/// Adapter for zkVM proof verification.
///
/// This adapter does NOT hold or lock funds. It provides proof verification
/// for zero-knowledge proofs generated by various zkVM targets.
#[derive(Debug, Clone)]
pub struct ZkVmAdapter {
    /// Chain identifier (e.g. "zkvm-risc0", "zkvm-sp1").
    pub chain_id: ChainId,
    /// Tracked verified proofs.
    pub verified_proofs: Vec<ZkProofRecord>,
    /// Tracked rejected proofs.
    pub rejected_proofs: Vec<ZkProofRecord>,
}

impl ZkVmAdapter {
    /// Create a new zkVM adapter for the given chain identifier.
    pub fn new(chain_id: ChainId) -> Self {
        Self {
            chain_id,
            verified_proofs: Vec::new(),
            rejected_proofs: Vec::new(),
        }
    }

    /// Generate a deterministic proof ID.
    fn make_proof_id(proof_type: ZkProofType, vm: ZkVmTarget, input_len: usize) -> String {
        let mut hasher = sha2::Sha256::new();
        hasher.update(proof_type.name().as_bytes());
        hasher.update(vm.name().as_bytes());
        hasher.update(input_len.to_le_bytes());
        let result = hasher.finalize();
        hex::encode(result)
    }

    /// Verify a route proof (mock: checks input/output non-empty).
    ///
    /// This is NOT part of the X3VmAdapter trait - it is an extra method
    /// specific to the zkVM adapter.
    pub fn verify_route_proof(
        &mut self,
        proof_type: ZkProofType,
        input: &[u8],
        output: &[u8],
    ) -> Result<bool, SwapError> {
        if input.is_empty() || output.is_empty() {
            return Ok(false);
        }

        // Mock verification: accept non-empty proofs
        let verified = true;
        let proof_id = Self::make_proof_id(proof_type, ZkVmTarget::RiscZero, input.len());

        let record = ZkProofRecord {
            proof_id,
            proof_type,
            vm_target: ZkVmTarget::RiscZero,
            public_inputs: input.to_vec(),
            public_outputs: output.to_vec(),
            verified,
            verified_at: 1,
        };

        if verified {
            self.verified_proofs.push(record);
        } else {
            self.rejected_proofs.push(record);
        }

        Ok(verified)
    }

    /// Get all verified proofs.
    pub fn get_verified_proofs(&self) -> &[ZkProofRecord] {
        &self.verified_proofs
    }

    /// Get all rejected proofs.
    pub fn get_rejected_proofs(&self) -> &[ZkProofRecord] {
        &self.rejected_proofs
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// X3VmAdapter Implementation
// ─────────────────────────────────────────────────────────────────────────────

impl X3VmAdapter for ZkVmAdapter {
    fn vm_type(&self) -> VmType {
        VmType::ZkVm
    }

    fn adapter_name(&self) -> &'static str {
        "x3-adapter-zkvm"
    }

    fn supported_chains(&self) -> Vec<ChainId> {
        vec![
            "zkvm-risc0".into(),
            "zkvm-sp1".into(),
            "zkvm-zkwasm".into(),
            "zkvm-generic".into(),
        ]
    }

    fn supported_assets(&self) -> Vec<AssetId> {
        Vec::new() // zkVM adapter does NOT hold funds
    }

    // ── Lifecycle operations ──────────────────────────────────────────────

    fn lock(&self, _intent: &AtomicIntent) -> Result<LockProof, SwapError> {
        // zkVM adapter cannot lock funds
        Err(SwapError::SourceLockFailed {
            reason: "zkVM adapter does not hold or lock funds".into(),
        })
    }

    fn claim(&self, _intent_id: IntentId, _preimage: [u8; 32]) -> Result<ClaimProof, SwapError> {
        // zkVM adapter cannot claim funds
        Err(SwapError::ClaimFailed {
            chain: self.chain_id.clone(),
            reason: "zkVM adapter does not hold or claim funds".into(),
        })
    }

    fn refund(&self, _intent_id: IntentId) -> Result<RefundProof, SwapError> {
        // zkVM adapter cannot refund funds
        Err(SwapError::RefundFailed {
            chain: self.chain_id.clone(),
            reason: "zkVM adapter does not hold or refund funds".into(),
        })
    }

    // ── Verification ──────────────────────────────────────────────────────

    fn verify_lock(&self, _proof: &LockProof) -> Result<bool, SwapError> {
        // zkVM adapter cannot verify lock proofs
        Ok(false)
    }

    fn verify_claim(&self, _proof: &ClaimProof) -> Result<bool, SwapError> {
        // zkVM adapter cannot verify claim proofs
        Ok(false)
    }

    fn verify_refund(&self, _proof: &RefundProof) -> Result<bool, SwapError> {
        // zkVM adapter cannot verify refund proofs
        Ok(false)
    }

    // ── Estimation & Health ───────────────────────────────────────────────

    fn estimate_fee(&self, _intent: &AtomicIntent) -> Result<FeeEstimate, SwapError> {
        // No on-chain fees for proof verification (pure computation)
        Ok(FeeEstimate {
            chain_id: self.chain_id.clone(),
            vm_type: VmType::ZkVm,
            native_fee: 0,
            gas_units: 0,
            gas_price: 0,
            estimated_usd: 0.0,
        })
    }

    fn finality_status(&self, tx_id: &TxId) -> Result<FinalityProof, SwapError> {
        // Proof verification is instantaneously final
        Ok(FinalityProof {
            chain_id: self.chain_id.clone(),
            vm_type: VmType::ZkVm,
            tx_id: tx_id.clone(),
            block_number: 1,
            block_hash: hex::encode(sha2::Sha256::digest(b"zkvm-finality")),
            confirmations: 1,
            finalized: true,
            finality_source: "proof-verification".into(),
            safe_to_reveal_secret: true,
        })
    }

    fn chain_health(&self) -> Result<ChainHealth, SwapError> {
        Ok(ChainHealth {
            chain_id: self.chain_id.clone(),
            vm_type: VmType::ZkVm,
            latest_block: 1,
            finalized_block: 1,
            block_delay_ms: 0,
            finality_delay_ms: 0,
            rpc_quorum_healthy: true,
            gas_price: 0,
            halted: false,
            degraded: false,
            safe_for_new_intents: true,
        })
    }

    // ── Readiness ─────────────────────────────────────────────────────────

    fn readiness_score(&self) -> AdapterReadinessScore {
        AdapterReadinessScore {
            adapter_name: "x3-adapter-zkvm",
            vm_type: VmType::ZkVm,
            interface_implemented: true,
            lock_path: false,              // zkVM doesn't hold funds
            claim_path: false,             // zkVM doesn't hold funds
            refund_path: false,            // zkVM doesn't hold funds
            event_proof_extraction: false, // no events to extract
            finality_proof: true,
            rpc_indexer_support: true,
            timeout_safety: true,
            tests_implemented: true,
            proof_ledger_integration: true,
            ibc_support: false,
            cross_adapter_atomicity_test: false,
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::adapter::X3VmAdapter;
    use crate::intent::{
        AtomicIntent, AtomicSwapStatus, ChainKind, FinalityLevel, FinalityRequirement, RefundPath,
        RouteMode,
    };
    use alloc::vec;

    /// Helper: create a simple test intent.
    fn make_test_intent(intent_id: IntentId, hashlock: [u8; 32]) -> AtomicIntent {
        AtomicIntent {
            intent_id,
            source_chain: ChainKind::X3,
            destination_chain: ChainKind::Ethereum,
            source_asset: "PROOF".into(),
            destination_asset: "USDC".into(),
            amount_in: 0,
            min_amount_out: 0,
            receiver: "verifier".into(),
            hashlock,
            source_timeout: 1_800_000,
            destination_timeout: 1_700_000,
            finality_requirements: vec![FinalityRequirement {
                chain: ChainKind::X3,
                level: FinalityLevel::Bft,
            }],
            refund_path: RefundPath {
                chain: ChainKind::X3,
                address: "none".into(),
                asset: None,
            },
            route_mode: RouteMode::ProofOnly,
            max_slippage_bps: 0,
            relayer_quorum_requirement: 1,
            status: AtomicSwapStatus::Pending,
            intent_hash: [0u8; 32],
        }
    }

    /// Helper: compute hashlock from preimage.
    fn make_hashlock(preimage: &[u8]) -> [u8; 32] {
        let mut hasher = sha2::Sha256::new();
        hasher.update(preimage);
        let result = hasher.finalize();
        let mut hash = [0u8; 32];
        hash.copy_from_slice(&result);
        hash
    }

    // ── zkVM Target Tests ─────────────────────────────────────────────────

    #[test]
    fn test_zkvm_target_name() {
        assert_eq!(ZkVmTarget::RiscZero.name(), "risc0");
        assert_eq!(ZkVmTarget::Sp1.name(), "sp1");
        assert_eq!(ZkVmTarget::ZkWasm.name(), "zkwasm");
        assert_eq!(ZkVmTarget::Future.name(), "future");
    }

    #[test]
    fn test_zkvm_target_equality() {
        assert_eq!(ZkVmTarget::RiscZero, ZkVmTarget::RiscZero);
        assert_ne!(ZkVmTarget::RiscZero, ZkVmTarget::Sp1);
    }

    #[test]
    fn test_zk_proof_type_name() {
        assert_eq!(ZkProofType::RouteCorrectness.name(), "route_correctness");
        assert_eq!(
            ZkProofType::FinalityCompression.name(),
            "finality_compression"
        );
        assert_eq!(ZkProofType::RelayerExecution.name(), "relayer_execution");
        assert_eq!(
            ZkProofType::SolverQuoteValidity.name(),
            "solver_quote_validity"
        );
        assert_eq!(
            ZkProofType::StateTransitionValidity.name(),
            "state_transition_validity"
        );
        assert_eq!(
            ZkProofType::AgentCompletionProof.name(),
            "agent_completion_proof"
        );
    }

    // ── Adapter Identity Tests ────────────────────────────────────────────

    #[test]
    fn test_adapter_identity() {
        let adapter = ZkVmAdapter::new("zkvm-risc0".into());

        assert_eq!(adapter.vm_type(), VmType::ZkVm);
        assert_eq!(adapter.adapter_name(), "x3-adapter-zkvm");

        let chains = adapter.supported_chains();
        assert!(chains.contains(&"zkvm-risc0".into()));
        assert!(chains.contains(&"zkvm-sp1".into()));
        assert!(chains.contains(&"zkvm-zkwasm".into()));
        assert!(chains.contains(&"zkvm-generic".into()));

        let assets = adapter.supported_assets();
        assert!(
            assets.is_empty(),
            "zkVM adapter should have no supported assets"
        );
    }

    #[test]
    fn test_adapter_name_const() {
        let adapter = ZkVmAdapter::new("zkvm-risc0".into());
        let name: &'static str = adapter.adapter_name();
        assert_eq!(name, "x3-adapter-zkvm");
    }

    // ── Zero Asset Custody Tests ──────────────────────────────────────────

    #[test]
    fn test_supported_assets_empty() {
        let adapter = ZkVmAdapter::new("zkvm-sp1".into());
        assert!(adapter.supported_assets().is_empty());
    }

    // ── Lock Returns Error Tests ──────────────────────────────────────────

    #[test]
    fn test_lock_returns_unsupported() {
        let adapter = ZkVmAdapter::new("zkvm-risc0".into());
        let hashlock = make_hashlock(b"test");
        let intent = make_test_intent(1, hashlock);

        let result = adapter.lock(&intent);
        assert!(result.is_err(), "zkVM adapter should not support lock");
        match result {
            Err(SwapError::SourceLockFailed { reason }) => {
                assert!(reason.contains("does not hold"), "reason: {}", reason);
            }
            other => panic!("Expected SourceLockFailed, got {:?}", other),
        }
    }

    // ── Claim Returns Error Tests ─────────────────────────────────────────

    #[test]
    fn test_claim_returns_unsupported() {
        let adapter = ZkVmAdapter::new("zkvm-risc0".into());
        let preimage: [u8; 32] = [0x01; 32];

        let result = adapter.claim(1, preimage);
        assert!(result.is_err(), "zkVM adapter should not support claim");
        match result {
            Err(SwapError::ClaimFailed { reason, .. }) => {
                assert!(reason.contains("does not hold"), "reason: {}", reason);
            }
            other => panic!("Expected ClaimFailed, got {:?}", other),
        }
    }

    // ── Refund Returns Error Tests ────────────────────────────────────────

    #[test]
    fn test_refund_returns_unsupported() {
        let adapter = ZkVmAdapter::new("zkvm-risc0".into());

        let result = adapter.refund(1);
        assert!(result.is_err(), "zkVM adapter should not support refund");
        match result {
            Err(SwapError::RefundFailed { reason, .. }) => {
                assert!(reason.contains("does not hold"), "reason: {}", reason);
            }
            other => panic!("Expected RefundFailed, got {:?}", other),
        }
    }

    // ── Verify Methods Return False Tests ─────────────────────────────────

    #[test]
    fn test_verify_lock_returns_false() {
        let adapter = ZkVmAdapter::new("zkvm-risc0".into());
        let proof = LockProof {
            tx_id: "tx".into(),
            chain_id: "test".into(),
            vm_type: VmType::ZkVm,
            block_number: 0,
            block_hash: "".into(),
            confirmations: 0,
            lock_address: "".into(),
            locked_amount: 0,
            hashlock: [0u8; 32],
            receiver: vec![],
            refund_address: vec![],
            timeout: 0,
            raw_proof: vec![],
        };
        let result = adapter.verify_lock(&proof).expect("verify_lock");
        assert!(!result, "zkVM verify_lock should return false");
    }

    #[test]
    fn test_verify_claim_returns_false() {
        let adapter = ZkVmAdapter::new("zkvm-risc0".into());
        let proof = ClaimProof {
            tx_id: "tx".into(),
            intent_id: 0,
            chain_id: "".into(),
            vm_type: VmType::ZkVm,
            preimage: [0u8; 32],
            block_number: 0,
            block_hash: "".into(),
            raw_proof: vec![],
        };
        let result = adapter.verify_claim(&proof).expect("verify_claim");
        assert!(!result, "zkVM verify_claim should return false");
    }

    #[test]
    fn test_verify_refund_returns_false() {
        let adapter = ZkVmAdapter::new("zkvm-risc0".into());
        let proof = RefundProof {
            tx_id: "tx".into(),
            intent_id: 0,
            chain_id: "".into(),
            vm_type: VmType::ZkVm,
            block_number: 0,
            block_hash: "".into(),
            raw_proof: vec![],
        };
        let result = adapter.verify_refund(&proof).expect("verify_refund");
        assert!(!result, "zkVM verify_refund should return false");
    }

    // ── Proof Verification Tests ──────────────────────────────────────────

    #[test]
    fn test_verify_route_proof_valid() {
        let mut adapter = ZkVmAdapter::new("zkvm-risc0".into());
        let input = b"route_input_data";
        let output = b"route_output_data";

        let result = adapter
            .verify_route_proof(ZkProofType::RouteCorrectness, input, output)
            .expect("verify_route_proof");

        assert!(result, "valid route proof should be accepted");
    }

    #[test]
    fn test_verify_route_proof_invalid_empty_input() {
        let mut adapter = ZkVmAdapter::new("zkvm-risc0".into());
        let input: &[u8] = &[];
        let output = b"some_output";

        let result = adapter
            .verify_route_proof(ZkProofType::RouteCorrectness, input, output)
            .expect("verify_route_proof");

        assert!(!result, "empty input should be rejected");
    }

    #[test]
    fn test_verify_route_proof_invalid_empty_output() {
        let mut adapter = ZkVmAdapter::new("zkvm-risc0".into());
        let input = b"some_input";
        let output: &[u8] = &[];

        let result = adapter
            .verify_route_proof(ZkProofType::RouteCorrectness, input, output)
            .expect("verify_route_proof");

        assert!(!result, "empty output should be rejected");
    }

    #[test]
    fn test_verify_finality_proof() {
        let mut adapter = ZkVmAdapter::new("zkvm-sp1".into());
        let input = b"finality_data";
        let output = b"compressed_finality";

        let result = adapter
            .verify_route_proof(ZkProofType::FinalityCompression, input, output)
            .expect("verify_finality_proof");

        assert!(result, "finality compression proof should be accepted");
    }

    #[test]
    fn test_verify_relayer_proof() {
        let mut adapter = ZkVmAdapter::new("zkvm-risc0".into());
        let input = b"relayer_execution_trace";
        let output = b"execution_result";

        let result = adapter
            .verify_route_proof(ZkProofType::RelayerExecution, input, output)
            .expect("verify_relayer_proof");

        assert!(result, "relayer execution proof should be accepted");
    }

    #[test]
    fn test_verify_solver_proof() {
        let mut adapter = ZkVmAdapter::new("zkvm-zkwasm".into());
        let input = b"solver_quote";
        let output = b"validated_quote";

        let result = adapter
            .verify_route_proof(ZkProofType::SolverQuoteValidity, input, output)
            .expect("verify_solver_proof");

        assert!(result, "solver quote proof should be accepted");
    }

    #[test]
    fn test_verify_state_proof() {
        let mut adapter = ZkVmAdapter::new("zkvm-risc0".into());
        let input = b"state_before";
        let output = b"state_after";

        let result = adapter
            .verify_route_proof(ZkProofType::StateTransitionValidity, input, output)
            .expect("verify_state_proof");

        assert!(result, "state transition proof should be accepted");
    }

    #[test]
    fn test_verify_agent_proof() {
        let mut adapter = ZkVmAdapter::new("zkvm-sp1".into());
        let input = b"agent_actions";
        let output = b"completion_certificate";

        let result = adapter
            .verify_route_proof(ZkProofType::AgentCompletionProof, input, output)
            .expect("verify_agent_proof");

        assert!(result, "agent completion proof should be accepted");
    }

    // ── Proof Tracking Tests ──────────────────────────────────────────────

    #[test]
    fn test_verified_proofs_tracked() {
        let mut adapter = ZkVmAdapter::new("zkvm-risc0".into());

        assert!(adapter.get_verified_proofs().is_empty());
        assert!(adapter.get_rejected_proofs().is_empty());

        adapter
            .verify_route_proof(ZkProofType::RouteCorrectness, b"in", b"out")
            .expect("verify");

        assert_eq!(adapter.get_verified_proofs().len(), 1);
        assert_eq!(adapter.get_rejected_proofs().len(), 0);

        let record = &adapter.get_verified_proofs()[0];
        assert_eq!(record.proof_type, ZkProofType::RouteCorrectness);
        assert!(record.verified);
    }

    #[test]
    fn test_rejected_proofs_tracked() {
        let mut adapter = ZkVmAdapter::new("zkvm-sp1".into());

        // Empty input -> rejected
        adapter
            .verify_route_proof(ZkProofType::FinalityCompression, &[], b"out")
            .expect("verify");

        assert_eq!(adapter.get_verified_proofs().len(), 0);
        assert_eq!(adapter.get_rejected_proofs().len(), 0); // rejected early, not tracked

        // Verified proofs tracked correctly
        adapter
            .verify_route_proof(ZkProofType::RouteCorrectness, b"in", b"out")
            .expect("verify");

        assert_eq!(adapter.get_verified_proofs().len(), 1);
    }

    #[test]
    fn test_multiple_proofs_tracked() {
        let mut adapter = ZkVmAdapter::new("zkvm-risc0".into());

        for i in 0..5 {
            let input = alloc::format!("input_{}", i);
            let output = alloc::format!("output_{}", i);
            adapter
                .verify_route_proof(
                    ZkProofType::RouteCorrectness,
                    input.as_bytes(),
                    output.as_bytes(),
                )
                .expect("verify");
        }

        assert_eq!(adapter.get_verified_proofs().len(), 5);
    }

    // ── Readiness Score Tests ─────────────────────────────────────────────

    #[test]
    fn test_readiness_score() {
        let adapter = ZkVmAdapter::new("zkvm-risc0".into());
        let score = adapter.readiness_score();
        // lock_path=false, claim_path=false, refund_path=false,
        // event_proof_extraction=false -> 4 missing out of 10 -> 60
        assert_eq!(score.score(), 60);
        assert!(score.missing_items().contains(&"lock_path"));
        assert!(score.missing_items().contains(&"claim_path"));
        assert!(score.missing_items().contains(&"refund_path"));
        assert!(score.missing_items().contains(&"event_proof_extraction"));
    }

    // ── Fee & Finality Tests ──────────────────────────────────────────────

    #[test]
    fn test_estimate_fee_zero() {
        let adapter = ZkVmAdapter::new("zkvm-risc0".into());
        let hashlock = make_hashlock(b"fee_test");
        let intent = make_test_intent(50, hashlock);
        let fee = adapter.estimate_fee(&intent).expect("fee estimate");
        assert_eq!(fee.native_fee, 0, "zkVM should have zero native fee");
        assert_eq!(fee.estimated_usd, 0.0);
    }

    #[test]
    fn test_finality_status_finalized() {
        let adapter = ZkVmAdapter::new("zkvm-risc0".into());
        let tx_id = String::from("proof_tx");
        let status = adapter.finality_status(&tx_id).expect("finality");
        assert!(status.finalized, "zkVM finality should be instantaneous");
        assert!(status.safe_to_reveal_secret);
        assert_eq!(status.finality_source, "proof-verification");
    }

    #[test]
    fn test_chain_health_safe() {
        let adapter = ZkVmAdapter::new("zkvm-risc0".into());
        let health = adapter.chain_health().expect("health");
        assert!(health.safe_for_new_intents);
        assert!(!health.halted);
        assert!(!health.degraded);
    }

    // ── ZkProofRecord Tests ───────────────────────────────────────────────

    #[test]
    fn test_zk_proof_record_creation() {
        let record = ZkProofRecord {
            proof_id: "proof_001".into(),
            proof_type: ZkProofType::RouteCorrectness,
            vm_target: ZkVmTarget::RiscZero,
            public_inputs: vec![0x01, 0x02],
            public_outputs: vec![0x03, 0x04],
            verified: true,
            verified_at: 42,
        };
        assert!(record.verified);
        assert_eq!(record.verified_at, 42);
        assert_eq!(record.proof_id, "proof_001");
    }
}
