#!/usr/bin/env python3
"""
scripts/x3_generate_issues.py — Auto-generate GitHub Issues from X3_COMPLETION.md

Usage:
    python3 scripts/x3_generate_issues.py [--dry-run]

Requirements:
    - GitHub CLI installed: https://cli.github.com/
    - Authenticated: gh auth login
    - Run from repo root

Effect:
    Every unchecked item (⬜) in X3_COMPLETION.md becomes a blocking GitHub issue
    labelled x3, audit, blocking. Already-open issues with the same title are
    skipped (idempotent).
"""

import json
import re
import subprocess
import sys

CHECKLIST = "X3_COMPLETION.md"
LABELS = "x3,audit,blocking"
DRY_RUN = "--dry-run" in sys.argv


def get_existing_issue_titles() -> set[str]:
    """Fetch all open issue titles to avoid creating duplicates."""
    try:
        result = subprocess.run(
            ["gh", "issue", "list", "--state", "open", "--json", "title", "--limit", "500"],
            capture_output=True, text=True, check=True
        )
        issues = json.loads(result.stdout)
        return {i["title"] for i in issues}
    except subprocess.CalledProcessError:
        print("⚠️  Could not fetch existing issues — will create all (may produce duplicates)")
        return set()


def parse_checklist(path: str) -> list[dict]:
    """Parse X3_COMPLETION.md and extract unchecked items with context."""
    with open(path) as f:
        content = f.read()

    items = []
    current_section = "Unknown"
    current_subsection = ""

    for line in content.splitlines():
        # Track section headers
        if line.startswith("## "):
            current_section = line.lstrip("# ").strip()
            current_subsection = ""
        elif line.startswith("### "):
            current_subsection = line.lstrip("# ").strip()

        # Match table rows with ⬜
        # Format: | Item description | ⬜ | Files / Modules |
        match = re.match(r"\|\s*(.+?)\s*\|\s*⬜\s*\|\s*(.+?)\s*\|", line)
        if match:
            item_text = match.group(1).strip()
            files_text = match.group(2).strip()

            # Skip header rows
            if item_text.lower() in ("item", "---", "status"):
                continue

            items.append({
                "section": current_section,
                "subsection": current_subsection,
                "item": item_text,
                "files": files_text,
            })

    return items


def create_issue(item: dict, existing_titles: set[str]) -> bool:
    """Create a single GitHub issue. Returns True if created."""
    title = f"[X3] {item['section']}: {item['item']}"

    if title in existing_titles:
        print(f"  [SKIP] Already exists: {title}")
        return False

    body = f"""## Checklist Item

**{item['item']}**

## Subsystem

**{item['section']}** — {item['subsection']}

## Files / Modules

```
{item['files']}
```

## Completion Criteria

- [ ] Implement the feature / fix
- [ ] Write or update unit tests
- [ ] All tests pass (`cargo test`)
- [ ] Update `X3_COMPLETION.md`: change `⬜` → `✅`
- [ ] Commit with message: `fix: [X3] {item['item'][:60]}`

---
*AUTOGENERATED from X3_COMPLETION.md — DO NOT CLOSE WITHOUT A FIX.*
"""

    if DRY_RUN:
        print(f"  [DRY-RUN] Would create: {title}")
        return True

    try:
        subprocess.run(
            [
                "gh", "issue", "create",
                "--title", title,
                "--body", body,
                "--label", LABELS,
            ],
            check=True,
            capture_output=True,
        )
        print(f"  [CREATED] {title}")
        return True
    except subprocess.CalledProcessError as e:
        # Label may not exist yet — try creating it first
        if b"label" in (e.stderr or b""):
            for label in LABELS.split(","):
                subprocess.run(
                    ["gh", "label", "create", label.strip(), "--force"],
                    capture_output=True,
                )
            # Retry
            try:
                subprocess.run(
                    ["gh", "issue", "create",
                     "--title", title, "--body", body, "--label", LABELS],
                    check=True, capture_output=True,
                )
                print(f"  [CREATED] {title}")
                return True
            except subprocess.CalledProcessError as e2:
                print(f"  [ERROR] {title}: {e2.stderr.decode()[:80]}")
                return False
        else:
            print(f"  [ERROR] {title}: {e.stderr.decode()[:80]}")
            return False


def ensure_labels() -> None:
    """Ensure required labels exist in the repo."""
    label_configs = [
        ("x3",      "0075ca", "X3 Chain item"),
        ("audit",   "e4e669", "Audit / compliance item"),
        ("blocking","d93f0b", "Blocks shipping"),
    ]
    for name, color, desc in label_configs:
        subprocess.run(
            ["gh", "label", "create", name,
             "--color", color, "--description", desc, "--force"],
            capture_output=True,
        )


def main() -> None:
    print("=== X3 GitHub Issue Generator ===")
    if DRY_RUN:
        print("(DRY-RUN MODE — no issues will be created)\n")

    items = parse_checklist(CHECKLIST)
    print(f"Parsed {len(items)} unchecked items from {CHECKLIST}\n")

    if not items:
        print("✅ No unchecked items found — checklist is complete!")
        return

    if not DRY_RUN:
        ensure_labels()

    existing = get_existing_issue_titles()
    created = 0
    skipped = 0

    for item in items:
        if create_issue(item, existing):
            created += 1
        else:
            skipped += 1

    print(f"\n✅ Done: {created} created, {skipped} skipped")
    if DRY_RUN:
        print("   Remove --dry-run to actually create issues")


if __name__ == "__main__":
    main()
