//! Autogenerated weights for `pallet_atomic_trade_engine`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0
//! FOR DEVELOPMENT PURPOSES ONLY. NOT FOR PRODUCTION USE.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_atomic_trade_engine.
pub trait WeightInfo {
    fn create_trade_batch(legs: u32) -> Weight;
    fn execute_trade_batch() -> Weight;
    fn cancel_trade_batch() -> Weight;
    fn register_amm_adapter() -> Weight;
    fn remove_amm_adapter() -> Weight;
    fn create_manual_checkpoint() -> Weight;
}

/// Weights for pallet_atomic_trade_engine using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// The range of component `l` is `[1, 16]`.
    fn create_trade_batch(l: u32) -> Weight {
        // Proof Size summary:
        // Measured:  `0`
        // Estimated: `0`
        Weight::from_parts(20_000_000, 0)
            .saturating_add(Weight::from_parts(5_000_000, 0).saturating_mul(l.into()))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    fn execute_trade_batch() -> Weight {
        // Proof Size summary for executing a batch with up to 16 legs
        // Measured:  `512`
        // Estimated: `6000`
        Weight::from_parts(500_000_000, 6000)
            .saturating_add(T::DbWeight::get().reads(10))
            .saturating_add(T::DbWeight::get().writes(8))
    }

    fn cancel_trade_batch() -> Weight {
        // Proof Size summary:
        // Measured:  `256`
        // Estimated: `3000`
        Weight::from_parts(15_000_000, 3000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    fn register_amm_adapter() -> Weight {
        // Proof Size summary:
        // Measured:  `0`
        // Estimated: `0`
        Weight::from_parts(10_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn remove_amm_adapter() -> Weight {
        // Proof Size summary:
        // Measured:  `128`
        // Estimated: `1000`
        Weight::from_parts(8_000_000, 1000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn create_manual_checkpoint() -> Weight {
        // Proof Size summary:
        // Measured:  `256`
        // Estimated: `3000`
        Weight::from_parts(25_000_000, 3000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn create_trade_batch(l: u32) -> Weight {
        Weight::from_parts(20_000_000, 0)
            .saturating_add(Weight::from_parts(5_000_000, 0).saturating_mul(l.into()))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(3))
    }

    fn execute_trade_batch() -> Weight {
        Weight::from_parts(500_000_000, 6000)
            .saturating_add(RocksDbWeight::get().reads(10))
            .saturating_add(RocksDbWeight::get().writes(8))
    }

    fn cancel_trade_batch() -> Weight {
        Weight::from_parts(15_000_000, 3000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(3))
    }

    fn register_amm_adapter() -> Weight {
        Weight::from_parts(10_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn remove_amm_adapter() -> Weight {
        Weight::from_parts(8_000_000, 1000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn create_manual_checkpoint() -> Weight {
        Weight::from_parts(25_000_000, 3000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
}
