//! Autogenerated weights for pallet_x3_vrf
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-04-29, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `x3-dev`, CPU: `AMD EPYC 7742`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/x3 benchmark pallet --chain=dev --steps=50 --repeat=20 --pallet=pallet_x3_vrf --extrinsic=* --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=./pallets/x3-vrf/src/weights.rs --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_x3_vrf.
pub trait WeightInfo {
	fn request_randomness() -> Weight;
	fn fulfill_randomness() -> Weight;
	fn cancel_randomness() -> Weight;
}

/// Weights for pallet_x3_vrf using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `RequestCounter` (r:1 w:1)
	/// Proof: `RequestCounter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AccountRequests` (r:1 w:1)
	/// Proof: `AccountRequests` (`max_values`: None, `max_size`: Some(1032), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `PendingRequests` (r:0 w:1)
	/// Proof: `PendingRequests` (`max_values`: None, `max_size`: Some(109), added: 584, mode: `MaxEncodedLen`)
	fn request_randomness() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `75`
		//  Estimated: `3500`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(36_000_000, 3500)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `PendingRequests` (r:1 w:1)
	/// Proof: `PendingRequests` (`max_values`: None, `max_size`: Some(109), added: 584, mode: `MaxEncodedLen`)
	/// Storage: `FulfilledRequests` (r:1 w:1)
	/// Proof: `FulfilledRequests` (`max_values`: None, `max_size`: Some(173), added: 648, mode: `MaxEncodedLen`)
	/// Storage: `AccountRequests` (r:1 w:1)
	/// Proof: `AccountRequests` (`max_values`: None, `max_size`: Some(1032), added: 2507, mode: `MaxEncodedLen`)
	fn fulfill_randomness() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `3740`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(46_000_000, 3740)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `PendingRequests` (r:1 w:1)
	/// Proof: `PendingRequests` (`max_values`: None, `max_size`: Some(109), added: 584, mode: `MaxEncodedLen`)
	/// Storage: `FulfilledRequests` (r:1 w:0)
	/// Proof: `FulfilledRequests` (`max_values`: None, `max_size`: Some(173), added: 648, mode: `MaxEncodedLen`)
	/// Storage: `AccountRequests` (r:1 w:1)
	/// Proof: `AccountRequests` (`max_values`: None, `max_size`: Some(1032), added: 2507, mode: `MaxEncodedLen`)
	fn cancel_randomness() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `3740`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(36_000_000, 3740)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `RequestCounter` (r:1 w:1)
	/// Proof: `RequestCounter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AccountRequests` (r:1 w:1)
	/// Proof: `AccountRequests` (`max_values`: None, `max_size`: Some(1032), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `PendingRequests` (r:0 w:1)
	/// Proof: `PendingRequests` (`max_values`: None, `max_size`: Some(109), added: 584, mode: `MaxEncodedLen`)
	fn request_randomness() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `75`
		//  Estimated: `3500`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(36_000_000, 3500)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `PendingRequests` (r:1 w:1)
	/// Proof: `PendingRequests` (`max_values`: None, `max_size`: Some(109), added: 584, mode: `MaxEncodedLen`)
	/// Storage: `FulfilledRequests` (r:1 w:1)
	/// Proof: `FulfilledRequests` (`max_values`: None, `max_size`: Some(173), added: 648, mode: `MaxEncodedLen`)
	/// Storage: `AccountRequests` (r:1 w:1)
	/// Proof: `AccountRequests` (`max_values`: None, `max_size`: Some(1032), added: 2507, mode: `MaxEncodedLen`)
	fn fulfill_randomness() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `3740`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(46_000_000, 3740)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `PendingRequests` (r:1 w:1)
	/// Proof: `PendingRequests` (`max_values`: None, `max_size`: Some(109), added: 584, mode: `MaxEncodedLen`)
	/// Storage: `FulfilledRequests` (r:1 w:0)
	/// Proof: `FulfilledRequests` (`max_values`: None, `max_size`: Some(173), added: 648, mode: `MaxEncodedLen`)
	/// Storage: `AccountRequests` (r:1 w:1)
	/// Proof: `AccountRequests` (`max_values`: None, `max_size`: Some(1032), added: 2507, mode: `MaxEncodedLen`)
	fn cancel_randomness() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `3740`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(36_000_000, 3740)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}