//! Block Fusion Pass
//!
//! Merges basic block chains that have become trivial after other
//! optimization passes. This eliminates unnecessary jumps and creates
//! larger basic blocks for better instruction scheduling.
//!
//! # Fusion Rules
//!
//! Two blocks P (predecessor) and B (successor) can be fused when:
//!
//! 1. P has exactly one successor (B)
//! 2. B has exactly one predecessor (P)
//! 3. P does not end an atomic transaction window
//! 4. B does not start an atomic transaction window
//! 5. P's terminator is Goto(B)
//!
//! When fused:
//! - B's statements are appended to P
//! - P's terminator is replaced with B's terminator
//! - B is removed from the function
//!
//! # Benefits
//!
//! - Eliminates jump overhead in generated bytecode
//! - Creates larger basic blocks for better register allocation
//! - Reduces CFG complexity for subsequent passes
//! - Improves instruction cache locality
//!
//! # Interaction with Other Passes
//!
//! Should run AFTER:
//! - BranchInversionPass (creates more fusion candidates)
//! - ConstantPropagation (eliminates conditional branches)
//! - DeadCodeElimination (removes unreachable blocks)
//!
//! May enable more:
//! - Peephole optimizations (larger instruction windows)
//! - Copy propagation (more visible def-use chains)

use crate::cfg::Cfg;
use crate::pass::{Pass, PassResult};
use crate::OptResult;
use x3_mir::mir::{MirBlockId, MirModule, MirTerminator};

/// Block fusion pass for merging linear block chains.
pub struct BlockFusionPass;

impl Pass for BlockFusionPass {
    fn name(&self) -> &'static str {
        "block_fusion"
    }

    fn run(&self, module: &mut MirModule) -> OptResult<PassResult> {
        let mut transformation_count = 0;

        for func in &mut module.functions {
            if func.blocks.len() < 2 {
                continue;
            }

            // Keep fusing until no more candidates
            loop {
                let cfg = Cfg::from_function(func);

                // Find fusion candidates: (predecessor, successor) pairs
                let candidates = find_fusion_candidates(func, &cfg);

                if candidates.is_empty() {
                    break;
                }

                // Perform fusions (one at a time to keep CFG consistent)
                // Take the first candidate
                let (pred_id, succ_id) = candidates[0];

                // Find block indices
                let pred_idx = func.blocks.iter().position(|b| b.id == pred_id);
                let succ_idx = func.blocks.iter().position(|b| b.id == succ_id);

                if let (Some(pred_idx), Some(succ_idx)) = (pred_idx, succ_idx) {
                    // Remove successor block
                    let succ_block = func.blocks.remove(succ_idx);

                    // Adjust pred_idx if needed (if succ was before pred)
                    let adjusted_pred_idx = if succ_idx < pred_idx {
                        pred_idx - 1
                    } else {
                        pred_idx
                    };

                    // Fuse: append succ's statements and terminator to pred
                    let pred_block = &mut func.blocks[adjusted_pred_idx];
                    pred_block.statements.extend(succ_block.statements);
                    pred_block.terminator = succ_block.terminator;

                    transformation_count += 1;

                    // Update any references to the removed block
                    // (redirect jumps from succ_id to pred_id)
                    update_block_references(func, succ_id, pred_id);
                }
            }
        }

        Ok(PassResult::with_count(transformation_count, "blocks fused"))
    }
}

/// Find pairs of blocks that can be fused.
fn find_fusion_candidates(
    func: &x3_mir::mir::MirFunction,
    cfg: &Cfg,
) -> Vec<(MirBlockId, MirBlockId)> {
    let mut candidates = Vec::new();

    for block in &func.blocks {
        // Check if this block ends with Goto
        if let Some(MirTerminator::Goto(succ_id)) = &block.terminator {
            let pred_id = block.id;

            // Rule 1: P has exactly one successor
            let p_succs = cfg.succs.get(&pred_id).map(|s| s.len()).unwrap_or(0);
            if p_succs != 1 {
                continue;
            }

            // Rule 2: B has exactly one predecessor
            let b_preds = cfg.preds.get(succ_id).map(|p| p.len()).unwrap_or(0);
            if b_preds != 1 {
                continue;
            }

            // Rule 3 & 4: No atomic boundaries (simplified - check for atomic ops)
            // For now, we don't have explicit atomic markers in MIR statements
            // so we skip this check. In a full implementation, we'd check for
            // AtomicBegin/AtomicCommit markers.

            // Rule 5: Must not be self-loop
            if pred_id == *succ_id {
                continue;
            }

            // Rule 6: Can't fuse entry block away (but can fuse INTO entry)
            // The entry block can be the predecessor but not the successor to remove

            candidates.push((pred_id, *succ_id));
        }
    }

    candidates
}

/// Update all references from old_id to new_id in terminators.
fn update_block_references(
    func: &mut x3_mir::mir::MirFunction,
    old_id: MirBlockId,
    new_id: MirBlockId,
) {
    for block in &mut func.blocks {
        if let Some(ref mut term) = block.terminator {
            match term {
                MirTerminator::Goto(target) => {
                    if *target == old_id {
                        *target = new_id;
                    }
                }
                MirTerminator::Branch {
                    then_block,
                    else_block,
                    ..
                } => {
                    if *then_block == old_id {
                        *then_block = new_id;
                    }
                    if *else_block == old_id {
                        *else_block = new_id;
                    }
                }
                MirTerminator::Return(_) => {}
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use x3_common::{Literal, Span};
    use x3_mir::mir::{MirBlock, MirFunction, MirRhs, MirStatement, MirValue, SymbolId};

    fn dummy_span() -> Span {
        Span::new(0, 0)
    }

    fn make_func(blocks: Vec<MirBlock>) -> MirFunction {
        MirFunction {
            symbol: SymbolId(0),
            params: vec![],
            entry: MirBlockId(0),
            blocks,
            span: dummy_span(),
        }
    }

    #[test]
    fn test_simple_chain_fusion() {
        // B0: x = 1; goto B1
        // B1: y = 2; goto B2
        // B2: return
        // Should become: B0: x = 1; y = 2; return
        let blocks = vec![
            MirBlock {
                id: MirBlockId(0),
                statements: vec![MirStatement {
                    target: MirValue(0),
                    rhs: MirRhs::Literal(Literal::Integer(1)),
                }],
                terminator: Some(MirTerminator::Goto(MirBlockId(1))),
            },
            MirBlock {
                id: MirBlockId(1),
                statements: vec![MirStatement {
                    target: MirValue(1),
                    rhs: MirRhs::Literal(Literal::Integer(2)),
                }],
                terminator: Some(MirTerminator::Goto(MirBlockId(2))),
            },
            MirBlock {
                id: MirBlockId(2),
                statements: vec![],
                terminator: Some(MirTerminator::Return(None)),
            },
        ];

        let mut module = MirModule {
            functions: vec![make_func(blocks)],
            span: dummy_span(),
        };

        let pass = BlockFusionPass;
        let result = pass.run(&mut module).unwrap();

        assert!(result.changed);
        // Should have fused down to 1 block
        assert_eq!(module.functions[0].blocks.len(), 1);

        let fused = &module.functions[0].blocks[0];
        assert_eq!(fused.statements.len(), 2);
        assert!(matches!(
            fused.terminator,
            Some(MirTerminator::Return(None))
        ));
    }

    #[test]
    fn test_no_fusion_multiple_predecessors() {
        // B0: Branch(cond, B1, B2)
        // B1: goto B3
        // B2: goto B3
        // B3: return  <- has 2 predecessors, can't fuse
        let blocks = vec![
            MirBlock {
                id: MirBlockId(0),
                statements: vec![MirStatement {
                    target: MirValue(0),
                    rhs: MirRhs::Literal(Literal::Bool(true)),
                }],
                terminator: Some(MirTerminator::Branch {
                    cond: MirValue(0),
                    then_block: MirBlockId(1),
                    else_block: MirBlockId(2),
                }),
            },
            MirBlock {
                id: MirBlockId(1),
                statements: vec![],
                terminator: Some(MirTerminator::Goto(MirBlockId(3))),
            },
            MirBlock {
                id: MirBlockId(2),
                statements: vec![],
                terminator: Some(MirTerminator::Goto(MirBlockId(3))),
            },
            MirBlock {
                id: MirBlockId(3),
                statements: vec![],
                terminator: Some(MirTerminator::Return(None)),
            },
        ];

        let mut module = MirModule {
            functions: vec![make_func(blocks)],
            span: dummy_span(),
        };

        let pass = BlockFusionPass;
        let result = pass.run(&mut module).unwrap();

        // B3 has 2 preds, but B1 and B2 each have 1 pred and 1 succ
        // So B1→B3 and B2→B3 can't fuse, but nothing else can either
        // Actually wait - B1 has 1 pred (B0) but B3 has 2 preds, so no fusion
        assert!(!result.changed);
    }

    #[test]
    fn test_no_fusion_multiple_successors() {
        // B0: Branch(cond, B1, B2) <- has 2 successors
        // B1: return
        // B2: return
        let blocks = vec![
            MirBlock {
                id: MirBlockId(0),
                statements: vec![MirStatement {
                    target: MirValue(0),
                    rhs: MirRhs::Literal(Literal::Bool(true)),
                }],
                terminator: Some(MirTerminator::Branch {
                    cond: MirValue(0),
                    then_block: MirBlockId(1),
                    else_block: MirBlockId(2),
                }),
            },
            MirBlock {
                id: MirBlockId(1),
                statements: vec![],
                terminator: Some(MirTerminator::Return(None)),
            },
            MirBlock {
                id: MirBlockId(2),
                statements: vec![],
                terminator: Some(MirTerminator::Return(None)),
            },
        ];

        let mut module = MirModule {
            functions: vec![make_func(blocks)],
            span: dummy_span(),
        };

        let pass = BlockFusionPass;
        let result = pass.run(&mut module).unwrap();

        // B0 has 2 successors, so nothing fuses
        assert!(!result.changed);
        assert_eq!(module.functions[0].blocks.len(), 3);
    }

    #[test]
    fn test_fusion_preserves_order() {
        // B0: a = 1; goto B1
        // B1: b = a + 1; return b
        // Fused should be: a = 1; b = a + 1; return b
        let blocks = vec![
            MirBlock {
                id: MirBlockId(0),
                statements: vec![MirStatement {
                    target: MirValue(0),
                    rhs: MirRhs::Literal(Literal::Integer(1)),
                }],
                terminator: Some(MirTerminator::Goto(MirBlockId(1))),
            },
            MirBlock {
                id: MirBlockId(1),
                statements: vec![MirStatement {
                    target: MirValue(1),
                    rhs: MirRhs::Binary(x3_ast::BinaryOp::Add, MirValue(0), MirValue(0)),
                }],
                terminator: Some(MirTerminator::Return(Some(MirValue(1)))),
            },
        ];

        let mut module = MirModule {
            functions: vec![make_func(blocks)],
            span: dummy_span(),
        };

        let pass = BlockFusionPass;
        let result = pass.run(&mut module).unwrap();

        assert!(result.changed);
        assert_eq!(module.functions[0].blocks.len(), 1);

        let fused = &module.functions[0].blocks[0];
        // First statement: v0 = 1
        assert_eq!(fused.statements[0].target, MirValue(0));
        // Second statement: v1 = v0 + v0
        assert_eq!(fused.statements[1].target, MirValue(1));
        // Terminator: return v1
        assert!(matches!(
            fused.terminator,
            Some(MirTerminator::Return(Some(MirValue(1))))
        ));
    }

    #[test]
    fn test_no_self_loop_fusion() {
        // B0: goto B0 (infinite loop - don't try to fuse with self)
        let blocks = vec![MirBlock {
            id: MirBlockId(0),
            statements: vec![],
            terminator: Some(MirTerminator::Goto(MirBlockId(0))),
        }];

        let mut module = MirModule {
            functions: vec![make_func(blocks)],
            span: dummy_span(),
        };

        let pass = BlockFusionPass;
        let result = pass.run(&mut module).unwrap();

        assert!(!result.changed);
    }
}
