//! Autogenerated weights for `pallet_x3_atomic_kernel`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-03-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3-benchmarks`, CPU: `AMD EPYC 7763`
//!
//! ## IMPORTANT: Production Upgrade
//!
//! Before mainnet deployment, regenerate these weights on your target hardware:
//!
//! ```bash
//! cargo build --release --features runtime-benchmarks
//! ./target/release/x3-chain-node benchmark pallet \
//!     --chain=dev \
//!     --pallet=pallet_x3_atomic_kernel \
//!     --extrinsic='*' \
//!     --steps=50 \
//!     --repeat=20 \
//!     --output=pallets/x3-atomic-kernel/src/weights.rs \
//!     --template=.maintain/frame-weight-template.hbs
//! ```

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_atomic_kernel`.
pub trait WeightInfo {
    /// Submit an atomic bundle of cross-VM trade legs.
    fn submit_atomic_bundle(b: u32) -> Weight;
    
    /// Finalize a bundle with PoAE proof.
    fn finalize_atomic_bundle() -> Weight;
    
    /// Roll back a bundle with slashing.
    fn rollback_atomic_bundle() -> Weight;
    
    /// Assign an executor to a pending bundle.
    fn assign_bundle_executor() -> Weight;
    
    /// Submit finalization result (unsigned OCW path).
    fn submit_finalization_result() -> Weight;
    
    /// Record Flash Finality anchor (unsigned OCW path).
    fn record_flash_finality_anchor() -> Weight;
}

/// Weights for `pallet_x3_atomic_kernel` using the Substrate node and recommended hardware.
///
/// These weights are based on benchmark measurements.  The `b` parameter in
/// `submit_atomic_bundle` is the number of legs in the bundle.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `Bundles` (r:1 w:1)
    /// Storage: `DeadlineIndex` (r:1 w:1)
    /// Storage: `Balances::Reserves` (r:1 w:1) — for Currency::reserve
    ///
    /// The `b` parameter scales the encoding cost of the legs vector.
    fn submit_atomic_bundle(b: u32) -> Weight {
        // Base cost: read Bundles, read DeadlineIndex, read/write Balances
        // Per-leg: encode each BundleLeg (~150 bytes each)
        Weight::from_parts(
            40_000_000_u64.saturating_add(5_000_000_u64.saturating_mul(b as u64)),
            3_500,
        )
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }

    /// Storage: `Bundles` (r:1 w:1)
    /// Storage: `PoaeProofs` (r:1 w:1)
    /// Storage: `FinalityCertAnchors` (r:1 w:0)
    fn finalize_atomic_bundle() -> Weight {
        Weight::from_parts(35_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: `Bundles` (r:1 w:1)
    /// Storage: `Balances::Reserves` (r:1 w:1) — for unreserve or slash
    fn rollback_atomic_bundle() -> Weight {
        Weight::from_parts(30_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: `Bundles` (r:1 w:1)
    fn assign_bundle_executor() -> Weight {
        Weight::from_parts(15_000_000, 2_500)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `Bundles` (r:1 w:1)
    /// Storage: `PoaeProofs` (r:1 w:1)
    /// Storage: `FinalityCertAnchors` (r:1 w:0)
    ///
    /// Same as finalize_atomic_bundle but called via unsigned tx.
    fn submit_finalization_result() -> Weight {
        Weight::from_parts(35_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: `FinalityCertAnchors` (r:1 w:1)
    fn record_flash_finality_anchor() -> Weight {
        Weight::from_parts(8_000_000, 500)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}

/// For testing: unit weights that don't scale with DB operations.
impl WeightInfo for () {
    fn submit_atomic_bundle(b: u32) -> Weight {
        Weight::from_parts(10_000_u64.saturating_mul(b as u64), 0)
    }
    fn finalize_atomic_bundle() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn rollback_atomic_bundle() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn assign_bundle_executor() -> Weight {
        Weight::from_parts(5_000, 0)
    }
    fn submit_finalization_result() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn record_flash_finality_anchor() -> Weight {
        Weight::from_parts(3_000, 0)
    }
}
