use crate::error::FoundryError;
use crate::templates::{Template, TemplateRegistry};
use crate::types::{
    DAppType, FeeMode, PricingTier, ProjectState, RevenueConfig,
};
use chrono::Utc;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use tracing::{info, warn};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArchitecturePlan {
    pub dapp_type: DAppType,
    pub name: String,
    pub description: String,
    pub features: Vec<String>,
    pub template_id: String,
    pub required_contracts: Vec<String>,
    pub frontend_framework: String,
    pub target_chains: Vec<String>,
    pub architecture_diagram: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContractOutput {
    pub contracts: HashMap<String, String>,
    pub abi: HashMap<String, String>,
    pub bytecode_hashes: HashMap<String, String>,
    pub deployment_order: Vec<String>,
    pub constructor_args: HashMap<String, Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FrontendOutput {
    pub component_tree: String,
    pub routes: Vec<String>,
    pub theme: HashMap<String, String>,
    pub api_endpoints: Vec<String>,
    pub contract_hooks: Vec<String>,
    pub build_config: HashMap<String, String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TokenomicsOutput {
    pub revenue_config: RevenueConfig,
    pub token_distribution: HashMap<String, f64>,
    pub pricing_tier: PricingTier,
    pub fairness_score: u8,
    pub sustainability_analysis: String,
    pub fee_explanation: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeploymentPackage {
    pub manifest: HashMap<String, String>,
    pub env_vars: HashMap<String, String>,
    pub scripts: Vec<String>,
    pub docker_config: Option<String>,
    pub cicd_config: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketplaceOutput {
    pub title: String,
    pub description: String,
    pub tagline: String,
    pub tags: Vec<String>,
    pub documentation: String,
    pub screenshot_descriptions: Vec<String>,
    pub demo_instructions: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComplianceReport {
    pub passed: bool,
    pub warnings: Vec<String>,
    pub violations: Vec<String>,
    pub restricted_jurisdictions: Vec<String>,
    pub scam_detected: bool,
    pub terms_violation: bool,
    pub compliance_score: u8,
}

pub struct ProductArchitectAgent;
impl ProductArchitectAgent {
    pub fn new() -> Self { Self }
    pub fn generate(&self, prompt: &str, registry: &TemplateRegistry) -> Result<ArchitecturePlan, FoundryError> {
        info!("ProductArchitectAgent: analyzing prompt: {}", prompt);
        let prompt_lower = prompt.to_lowercase();
        let dapp_type = self.classify_prompt(&prompt_lower);
        let template = self.find_best_template(&dapp_type, registry)?;
        let features = self.extract_features(&prompt_lower, &dapp_type);
        let name = self.generate_name(&prompt_lower, &dapp_type);
        let description = format!("{} - A {} dApp generated by X3 Foundry from prompt: {}", name, dapp_type.label(), prompt);
        let architecture_diagram = format!("Architecture: {} -> Smart Contracts ({}) -> Frontend ({}) -> Chain ({})", name, template.required_contracts.join(", "), template.frontend_framework, template.chain_support.join(", "));
        Ok(ArchitecturePlan { dapp_type, name, description, features, template_id: template.id.clone(), required_contracts: template.required_contracts.clone(), frontend_framework: template.frontend_framework.clone(), target_chains: template.chain_support.clone(), architecture_diagram })
    }
    fn classify_prompt(&self, prompt: &str) -> DAppType {
        if prompt.contains("token")||prompt.contains("launchpad")||prompt.contains("presale")||prompt.contains("meme"){DAppType::TokenLaunchpad}
        else if prompt.contains("nft")||prompt.contains("marketplace")||prompt.contains("collectible")||prompt.contains("auction"){DAppType::NFTMarketplace}
        else if prompt.contains("stak")||prompt.contains("pool")||prompt.contains("reward"){DAppType::StakingPool}
        else if prompt.contains("subscription")||prompt.contains("saas")||prompt.contains("recurring")||prompt.contains("billing"){DAppType::SubscriptionApp}
        else if prompt.contains("escrow")||prompt.contains("dispute")||prompt.contains("milestone")||prompt.contains("payment"){DAppType::EscrowApp}
        else if prompt.contains("ai")||prompt.contains("image")||prompt.contains("generate")||prompt.contains("gpu"){DAppType::AiImageSaaS}
        else if prompt.contains("trading")||prompt.contains("bot")||prompt.contains("vault")||prompt.contains("strategy"){DAppType::TradingBotVault}
        else if prompt.contains("yield")||prompt.contains("optimize")||prompt.contains("compound")||prompt.contains("vault"){DAppType::YieldOptimizer}
        else if(prompt.contains("cross")&&prompt.contains("chain"))||prompt.contains("payout")||prompt.contains("bridge"){DAppType::CrossChainPayout}
        else if prompt.contains("domain")||prompt.contains("registry")||prompt.contains("name")||prompt.contains("dns"){DAppType::DomainRegistry}
        else if prompt.contains("prediction")||prompt.contains("market")||prompt.contains("bet")||prompt.contains("forecast"){DAppType::PredictionMarket}
        else if prompt.contains("affiliate")||prompt.contains("referral")||prompt.contains("commission"){DAppType::AffiliateApp}
        else if(prompt.contains("data")&&prompt.contains("marketplace"))||prompt.contains("dataset"){DAppType::DataMarketplace}
        else{DAppType::Custom(format!("CustomApp-{}",&prompt[..prompt.len().min(20)]))}
    }
    fn find_best_template<'a>(&self, dapp_type: &DAppType, registry: &'a TemplateRegistry) -> Result<&'a Template, FoundryError> {
        let templates = registry.list_by_category(dapp_type);
        if let Some(t) = templates.first() { Ok(t) }
        else { let all = registry.list_templates(); all.first().ok_or_else(|| FoundryError::TemplateNotFound(format!("No template found for {:?}", dapp_type))) }
    }
    fn extract_features(&self, prompt: &str, dapp_type: &DAppType) -> Vec<String> {
        let mut features: Vec<String> = match dapp_type {
            DAppType::TokenLaunchpad => vec!["Token creation and management".into(),"Presale with multiple phases".into(),"Vesting schedule".into(),"Liquidity locking".into(),"Anti-bot protection".into()],
            DAppType::NFTMarketplace => vec!["NFT minting".into(),"Buy/sell listings".into(),"English and Dutch auctions".into(),"Royalty enforcement".into(),"Collection verification".into()],
            DAppType::StakingPool => vec!["Flexible staking pools".into(),"Tiered reward rates".into(),"Lock period configuration".into(),"Compound staking".into(),"Reward claiming".into()],
            DAppType::SubscriptionApp => vec!["Tiered subscription plans".into(),"Recurring billing".into(),"Token-gated access".into(),"Plan upgrade/downgrade".into(),"Payment history".into()],
            DAppType::EscrowApp => vec!["Milestone-based payments".into(),"Dispute resolution".into(),"Multi-sig approval".into(),"Transaction history".into(),"Arbitration panel".into()],
            DAppType::AiImageSaaS => vec!["AI image generation".into(),"GPU compute integration".into(),"Pay-per-use billing".into(),"Image gallery".into(),"NFT minting".into()],
            DAppType::TradingBotVault => vec!["Automated trading strategies".into(),"Investor onboarding".into(),"Performance tracking".into(),"Profit/loss sharing".into(),"Risk management".into()],
            DAppType::YieldOptimizer => vec!["Multi-pool yield aggregation".into(),"Auto-compounding".into(),"Risk scoring".into(),"Strategy backtesting".into(),"Performance analytics".into()],
            DAppType::CrossChainPayout => vec!["Multi-chain payout support".into(),"Streaming payments".into(),"Batch settlement".into(),"Cross-chain bridging".into(),"Payment scheduling".into()],
            DAppType::DomainRegistry => vec!["Domain registration".into(),"Domain auctions".into(),"Decentralized DNS".into(),"Domain trading".into(),"Subdomain management".into()],
            DAppType::PredictionMarket => vec!["Market creation".into(),"Automated market making".into(),"Oracle resolution".into(),"Liquidity provision".into(),"Position trading".into()],
            DAppType::AffiliateApp => vec!["Multi-level affiliate tracking".into(),"Commission distribution".into(),"Referral links".into(),"Performance dashboard".into(),"Automated payouts".into()],
            DAppType::DataMarketplace => vec!["Data tokenization".into(),"Access control".into(),"Privacy computation".into(),"Data verification".into(),"Revenue sharing".into()],
            DAppType::Custom(_) => vec!["Custom smart contract logic".into(),"User-defined features".into(),"Flexible configuration".into()],
        };
        if prompt.contains("analytics"){features.push("Built-in analytics dashboard".into());}
        if prompt.contains("mobile")||prompt.contains("app"){features.push("Mobile-responsive design".into());}
        if prompt.contains("multi")&&prompt.contains("language"){features.push("Multi-language support".into());}
        if prompt.contains("social")||prompt.contains("login"){features.push("Social login integration".into());}
        if prompt.contains("email")||prompt.contains("notification"){features.push("Email notification system".into());}
        features
    }
    fn generate_name(&self, prompt: &str, dapp_type: &DAppType) -> String {
        let words: Vec<&str> = prompt.split_whitespace().collect();
        for (i, w) in words.iter().enumerate() {
            if w.eq_ignore_ascii_case("called")||w.eq_ignore_ascii_case("named")||w.eq_ignore_ascii_case("name") {
                if i+1<words.len(){let n=words[i+1].trim_matches(|c:char|c.is_ascii_punctuation());if!n.is_empty()&&n.len()>=2{return n.to_string();}}
            }
        }
        format!("{}-{}",dapp_type.label().replace(' ',""),&uuid::Uuid::new_v4().to_string()[..6])
    }
}
impl Default for ProductArchitectAgent{fn default()->Self{Self::new()}}

pub struct ContractEngineerAgent;
impl ContractEngineerAgent {
    pub fn new()->Self{Self}
    pub fn generate(&self,plan:&ArchitecturePlan)->Result<ContractOutput,FoundryError>{
        info!("ContractEngineerAgent: generating contracts for {}",plan.name);
        let mut contracts=HashMap::new();let mut abi=HashMap::new();let mut bytecode_hashes=HashMap::new();let mut deployment_order=Vec::new();let mut constructor_args=HashMap::new();
        for cn in &plan.required_contracts{
            let src=self.generate_contract_source(cn,&plan.dapp_type);
            contracts.insert(cn.clone(),src.clone());
            abi.insert(cn.clone(),self.generate_abi(cn));
            bytecode_hashes.insert(cn.clone(),self.compute_bytecode_hash(&src));
            deployment_order.push(cn.clone());
            constructor_args.insert(cn.clone(),vec![]);
        }
        Ok(ContractOutput{contracts,abi,bytecode_hashes,deployment_order,constructor_args})
    }
    fn generate_contract_source(&self,cn:&str,dt:&DAppType)->String{
        let ts=Utc::now().to_rfc3339();
        format!("// SPDX-License-Identifier: Apache-2.0\n// Auto-generated by X3 Foundry\n// {ts}\n// {dt}\n// {cn}\npragma solidity ^0.8.20;\ncontract {cn}{{\naddress public owner;\nevent Init(address indexed o);\nmodifier onlyOwner(){{require(msg.sender==owner,\"Not owner\");_;}}\nconstructor(){{owner=msg.sender;emit Init(msg.sender);}}\nfunction getInfo()external view returns(string memory,address){{\nreturn(\"{cn}\",owner);\n}}\nreceive()external payable{{}}\nfallback()external payable{{}}\n}}",ts=ts,dt=dt.label(),cn=cn)
    }
    fn generate_abi(&self,cn:&str)->String{
        format!(r#"{{"cn":"{cn}","abi":[{{"type":"constructor","inputs":[],"stateMutability":"nonpayable"}},{{"type":"function","name":"owner","inputs":[],"outputs":[{{"type":"address"}}],"stateMutability":"view"}}]}}"#,cn=cn)
    }
    fn compute_bytecode_hash(&self,src:&str)->String{
        use sha2::{Digest,Sha256};let mut h=Sha256::new();h.update(src.as_bytes());hex::encode(h.finalize())
    }
}
impl Default for ContractEngineerAgent{fn default()->Self{Self::new()}}

pub struct FrontendEngineerAgent;
impl FrontendEngineerAgent {
    pub fn new()->Self{Self}
    pub fn generate(&self,plan:&ArchitecturePlan)->Result<FrontendOutput,FoundryError>{
        info!("FrontendEngineerAgent: generating frontend for {}",plan.name);
        let ct=self.build_component_tree(&plan.dapp_type);
        let routes=self.build_routes(&plan.dapp_type);
        let mut theme=HashMap::new();
        theme.insert("primary".into(),"#6366f1".into());theme.insert("secondary".into(),"#8b5cf6".into());
        theme.insert("accent".into(),"#06b6d4".into());theme.insert("background".into(),"#0f172a".into());
        theme.insert("surface".into(),"#1e293b".into());theme.insert("text".into(),"#f8fafc".into());
        theme.insert("success".into(),"#22c55e".into());theme.insert("warning".into(),"#eab308".into());
        theme.insert("error".into(),"#ef4444".into());
        let api=vec![format!("/api/{}",plan.name.to_lowercase().replace(' ',"-")),"/api/auth".into(),"/api/analytics".into()];
        let hooks=plan.required_contracts.iter().map(|c|format!("use{}Contract",c)).collect();
        let mut bc=HashMap::new();bc.insert("framework".into(),plan.frontend_framework.clone());bc.insert("build".into(),"npm run build".into());bc.insert("output".into(),"dist".into());bc.insert("node".into(),"18".into());
        Ok(FrontendOutput{component_tree:ct,routes,theme,api_endpoints:api,contract_hooks:hooks,build_config:bc})
    }
    fn build_component_tree(&self,dt:&DAppType)->String{
        match dt{
            DAppType::TokenLaunchpad=>"App->Header,Main->TokenCreator,PresalePanel,VestingDashboard,LiquidityManager,Footer".into(),
            DAppType::NFTMarketplace=>"App->Header,Main->NFTGrid,NFTDetail,MintPage,AuctionHouse,ProfilePage,Footer".into(),
            DAppType::StakingPool=>"App->Header,Main->PoolList,PoolDetail,StakeForm,RewardsDashboard,Footer".into(),
            DAppType::SubscriptionApp=>"App->Header,Main->PlanSelector,PaymentForm,SubscriptionStatus,AccessGate,Footer".into(),
            DAppType::EscrowApp=>"App->Header,Main->EscrowForm,MilestoneTracker,DisputePanel,TransactionHistory,Footer".into(),
            DAppType::AiImageSaaS=>"App->Header,Main->ImageGenerator,Gallery,PricingPlans,ComputeStatus,Footer".into(),
            DAppType::TradingBotVault=>"App->Header,Main->VaultOverview,StrategyConfig,PerformanceChart,InvestorPortal,Footer".into(),
            DAppType::YieldOptimizer=>"App->Header,Main->VaultList,VaultDetail,StrategyAllocation,RiskDashboard,Footer".into(),
            DAppType::CrossChainPayout=>"App->Header,Main->PayoutForm,StreamManager,BatchSettlement,CrossChainStatus,Footer".into(),
            DAppType::DomainRegistry=>"App->Header,Main->DomainSearch,DomainDetail,AuctionList,MyDomains,Footer".into(),
            DAppType::PredictionMarket=>"App->Header,Main->MarketList,MarketDetail,CreateMarket,Portfolio,Footer".into(),
            DAppType::AffiliateApp=>"App->Header,Main->Dashboard,LinkGenerator,CommissionTracker,PayoutHistory,Footer".into(),
            DAppType::DataMarketplace=>"App->Header,Main->DataCatalog,DataDetail,UploadData,AccessManager,Footer".into(),
            DAppType::Custom(_)=>"App->Header,Main->CustomComponent,Footer".into(),
        }
    }
    fn build_routes(&self,dt:&DAppType)->Vec<String>{
        match dt{
            DAppType::TokenLaunchpad=>vec!["/","/create","/presale","/vesting","/liquidity"],
            DAppType::NFTMarketplace=>vec!["/","/explore","/nft/:id","/mint","/auctions","/profile"],
            DAppType::StakingPool=>vec!["/","/pools","/pools/:id","/stake","/rewards"],
            DAppType::SubscriptionApp=>vec!["/","/plans","/subscribe","/manage","/billing"],
            DAppType::EscrowApp=>vec!["/","/create","/escrow/:id","/disputes","/history"],
            DAppType::AiImageSaaS=>vec!["/","/generate","/gallery","/pricing","/settings"],
            DAppType::TradingBotVault=>vec!["/","/vaults","/vaults/:id","/strategies","/invest"],
            DAppType::YieldOptimizer=>vec!["/","/vaults","/vaults/:id","/strategies","/risk"],
            DAppType::CrossChainPayout=>vec!["/","/payouts","/streams","/batch","/bridges"],
            DAppType::DomainRegistry=>vec!["/","/search","/domain/:name","/auctions","/my-domains"],
            DAppType::PredictionMarket=>vec!["/","/markets","/markets/:id","/create","/portfolio"],
            DAppType::AffiliateApp=>vec!["/","/dashboard","/links","/commissions","/payouts"],
            DAppType::DataMarketplace=>vec!["/","/catalog","/data/:id","/upload","/access"],
            DAppType::Custom(_)=>vec!["/"],
        }.into_iter().map(String::from).collect()
    }
}
impl Default for FrontendEngineerAgent{fn default()->Self{Self::new()}}

pub struct TokenomicsAgent;
impl TokenomicsAgent {
    pub fn new()->Self{Self}
    pub fn generate(&self,plan:&ArchitecturePlan,cw:&str)->Result<TokenomicsOutput,FoundryError>{
        info!("TokenomicsAgent: designing tokenomics for {}",plan.name);
        let rc=self.design_revenue_config(cw,&plan.dapp_type);
        let td=self.design_token_distribution(&plan.dapp_type);
        let pt=self.recommend_pricing_tier(&plan.dapp_type);
        let fs=self.calculate_fairness_score(&rc);
        let sa=self.analyze_sustainability(&plan.dapp_type,&rc);
        let fe=self.explain_fee_structure(&rc);
        Ok(TokenomicsOutput{revenue_config:rc,token_distribution:td,pricing_tier:pt,fairness_score:fs,sustainability_analysis:sa,fee_explanation:fe})
    }
    fn design_revenue_config(&self,cw:&str,dt:&DAppType)->RevenueConfig{
        let(pf,cf)=match dt{
            DAppType::TokenLaunchpad=>(300,9600),DAppType::NFTMarketplace=>(250,9650),DAppType::StakingPool=>(200,9700),
            DAppType::SubscriptionApp=>(150,9750),DAppType::EscrowApp=>(100,9800),DAppType::AiImageSaaS=>(500,9300),
            DAppType::TradingBotVault=>(300,9500),DAppType::YieldOptimizer=>(200,9700),DAppType::CrossChainPayout=>(150,9750),
            DAppType::DomainRegistry=>(250,9600),DAppType::PredictionMarket=>(300,9500),DAppType::AffiliateApp=>(200,9700),
            DAppType::DataMarketplace=>(250,9600),DAppType::Custom(_)=>(200,9700),
        };
        RevenueConfig{platform_fee_bps:pf,creator_fee_bps:cf,ai_agent_fee_bps:Some(50),maintenance_fee_bps:Some(50),referral_fee_bps:Some(50),treasury_wallet:"0xTreasury".into(),creator_wallet:cw.into(),maintenance_wallet:"0xMaintenance".into(),ai_agent_wallet:"0xAiAgent".into(),referral_wallet:"0xReferral".into(),fee_token:"X3".into(),fee_mode:FeeMode::GrossRevenue}
    }
    fn design_token_distribution(&self,dt:&DAppType)->HashMap<String,f64>{
        let mut d=HashMap::new();
        match dt{
            DAppType::TokenLaunchpad=>{d.insert("Public Sale".into(),40.0);d.insert("Team".into(),15.0);d.insert("Liquidity".into(),20.0);d.insert("Treasury".into(),15.0);d.insert("Marketing".into(),10.0);}
            DAppType::NFTMarketplace=>{d.insert("Community Rewards".into(),30.0);d.insert("Team".into(),20.0);d.insert("Treasury".into(),25.0);d.insert("Liquidity".into(),15.0);d.insert("Marketing".into(),10.0);}
            _=>{d.insert("Ecosystem".into(),40.0);d.insert("Team".into(),20.0);d.insert("Treasury".into(),20.0);d.insert("Liquidity".into(),10.0);d.insert("Marketing".into(),10.0);}
        }
        d
    }
    fn recommend_pricing_tier(&self,dt:&DAppType)->PricingTier{
        match dt{
            DAppType::AiImageSaaS|DAppType::TradingBotVault|DAppType::DataMarketplace|DAppType::CrossChainPayout=>PricingTier::Enterprise,
            DAppType::NFTMarketplace|DAppType::SubscriptionApp|DAppType::YieldOptimizer|DAppType::DomainRegistry|DAppType::PredictionMarket=>PricingTier::Pro,
            DAppType::TokenLaunchpad|DAppType::StakingPool|DAppType::EscrowApp|DAppType::AffiliateApp=>PricingTier::Builder,
            DAppType::Custom(_)=>PricingTier::Free,
        }
    }
    fn calculate_fairness_score(&self,rc:&RevenueConfig)->u8{
        let mut s:u8=100;
        if rc.platform_fee_bps>500{s=s.saturating_sub(20);}
        if rc.creator_fee_bps<9000{s=s.saturating_sub(15);}
        if rc.ai_agent_fee_bps.unwrap_or(0)>100{s=s.saturating_sub(10);}
        if rc.maintenance_fee_bps.unwrap_or(0)>100{s=s.saturating_sub(5);}
        s
    }
    fn analyze_sustainability(&self,dt:&DAppType,rc:&RevenueConfig)->String{
        format!("Sustainability: {} platform {:.2}% creator {:.2}%. Sustainable with >100 daily tx.",dt.label(),rc.platform_fee_bps as f64/100.0,rc.creator_fee_bps as f64/100.0)
    }
    fn explain_fee_structure(&self,rc:&RevenueConfig)->String{
        format!("Fees: Platform={}bps Creator={}bps AI={:?}bps Maint={:?}bps Ref={:?}bps Mode={:?}",rc.platform_fee_bps,rc.creator_fee_bps,rc.ai_agent_fee_bps,rc.maintenance_fee_bps,rc.referral_fee_bps,rc.fee_mode)
    }
}
impl Default for TokenomicsAgent{fn default()->Self{Self::new()}}

pub struct DeploymentAgent;
impl DeploymentAgent {
    pub fn new()->Self{Self}
    pub fn generate(&self,plan:&ArchitecturePlan)->Result<DeploymentPackage,FoundryError>{
        info!("DeploymentAgent: packaging deployment for {}",plan.name);
        let mut m=HashMap::new();m.insert("name".into(),plan.name.clone());m.insert("version".into(),"1.0.0".into());m.insert("type".into(),plan.dapp_type.to_string());m.insert("chain".into(),plan.target_chains.first().cloned().unwrap_or_default());
        let mut e=HashMap::new();e.insert("NODE_ENV".into(),"production".into());e.insert("RPC_URL".into(),"https://rpc.x3-chain.io".into());
        Ok(DeploymentPackage{manifest:m,env_vars:e,scripts:vec!["deploy.sh".into(),"verify.sh".into()],docker_config:Some("Node 18".into()),cicd_config:Some("GitHub Actions".into())})
    }
}
impl Default for DeploymentAgent{fn default()->Self{Self::new()}}

pub struct MarketplaceAgent;
impl MarketplaceAgent {
    pub fn new()->Self{Self}
    pub fn generate(&self,plan:&ArchitecturePlan,tok:&TokenomicsOutput)->Result<MarketplaceOutput,FoundryError>{
        info!("MarketplaceAgent: creating listing for {}",plan.name);
        let t=plan.name.clone();let tag=format!("A {} dApp",plan.dapp_type.label());
        let desc=format!("{} is a {} built on X3 Chain. Features: {}. Tier: {}.",plan.name,plan.dapp_type.label(),plan.features.join(", "),tok.pricing_tier.label());
        let tags=vec![plan.dapp_type.to_string(),"x3-foundry".into(),"dapp".into()];
        let docs=format!("# {}\n{}\n## Features\n{}\n## License\nApache-2.0",t,desc,plan.features.iter().map(|f|format!("- {}",f)).collect::<Vec<_>>().join("\n"));
        Ok(MarketplaceOutput{title:t,description:desc,tagline:tag,tags,documentation:docs,screenshot_descriptions:vec!["Dashboard".into(),"Main view".into(),"Settings".into()],demo_instructions:"Deploy and launch.".into()})
    }
}
impl Default for MarketplaceAgent{fn default()->Self{Self::new()}}

pub struct ComplianceGuardAgent;
impl ComplianceGuardAgent {
    pub fn new()->Self{Self}
    pub fn generate(&self,plan:&ArchitecturePlan,prompt:&str)->Result<ComplianceReport,FoundryError>{
        info!("ComplianceGuardAgent: checking compliance for {}",plan.name);
        let pl=prompt.to_lowercase();let mut w=Vec::new();let mut v=Vec::new();let mut rj=Vec::new();let mut sd=false;let mut tv=false;
        for kw in &["rug","pump and dump","guaranteed returns","get rich quick","ponzi","pyramid","money laundering"]{if pl.contains(kw){sd=true;v.push(format!("Scam: '{}'",kw));}}
        for kw in &["illegal","drug","weapon","terrorism","fraud","gambling","unlicensed","hacking","malware"]{if pl.contains(kw){tv=true;v.push(format!("Illegal: '{}'",kw));}}
        for kw in &["fake","impersonate","deceive","mislead","spoof","phishing"]{if pl.contains(kw){w.push(format!("Deceptive: '{}'",kw));}}
        for kw in &["north korea","iran","syria","cuba","crimea"]{if pl.contains(kw){rj.push(kw.to_string());v.push(format!("Restricted: '{}'",kw));}}
        for nm in &["uniswap","pancakeswap","opensea","binance","coinbase","metamask"]{if plan.name.to_lowercase().contains(nm){w.push(format!("Impersonation: '{}'",nm));}}
        let passed=v.is_empty();
        let cs=if passed{100u8.saturating_sub((w.len()as u8).saturating_mul(10))}else{0};
        Ok(ComplianceReport{passed,warnings:w,violations:v,restricted_jurisdictions:rj,scam_detected:sd,terms_violation:tv,compliance_score:cs})
    }
}
impl Default for ComplianceGuardAgent{fn default()->Self{Self::new()}}

pub struct Generator {
    pub architect: ProductArchitectAgent,
    pub contract_engineer: ContractEngineerAgent,
    pub frontend_engineer: FrontendEngineerAgent,
    pub tokenomics: TokenomicsAgent,
    pub deployment: DeploymentAgent,
    pub marketplace: MarketplaceAgent,
    pub compliance: ComplianceGuardAgent,
    pub template_registry: TemplateRegistry,
}

impl Generator {
    pub fn new() -> Self {
        Self {
            architect: ProductArchitectAgent::new(),
            contract_engineer: ContractEngineerAgent::new(),
            frontend_engineer: FrontendEngineerAgent::new(),
            tokenomics: TokenomicsAgent::new(),
            deployment: DeploymentAgent::new(),
            marketplace: MarketplaceAgent::new(),
            compliance: ComplianceGuardAgent::new(),
            template_registry: TemplateRegistry::default_registry(),
        }
    }

    pub fn generate_all(&self, prompt: &str, creator_wallet: &str) -> Result<(ArchitecturePlan, ContractOutput, FrontendOutput, TokenomicsOutput, DeploymentPackage, MarketplaceOutput, ComplianceReport), FoundryError> {
        info!("Generator: starting full generation pipeline for prompt: {}", prompt);
        let plan = self.architect.generate(prompt, &self.template_registry)?;
        let compliance = self.compliance.generate(&plan, prompt)?;
        if !compliance.passed {
            return Err(FoundryError::ComplianceFailed(format!("Compliance check failed: {:?}", compliance.violations)));
        }
        let contracts = self.contract_engineer.generate(&plan)?;
        let frontend = self.frontend_engineer.generate(&plan)?;
        let tokenomics = self.tokenomics.generate(&plan, creator_wallet)?;
        let deployment = self.deployment.generate(&plan)?;
        let marketplace = self.marketplace.generate(&plan, &tokenomics)?;
        Ok((plan, contracts, frontend, tokenomics, deployment, marketplace, compliance))
    }
}

impl Default for Generator { fn default() -> Self { Self::new() } }
