//! Autogenerated weights for pallet_x3_dex
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-04-29, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `x3-dev`, CPU: `AMD EPYC 7742`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/x3 benchmark pallet --chain=dev --steps=50 --repeat=20 --pallet=pallet_x3_dex --extrinsic=* --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=./pallets/x3-dex/src/weights.rs --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_x3_dex.
pub trait WeightInfo {
	fn create_pool() -> Weight;
	fn add_liquidity() -> Weight;
	fn remove_liquidity() -> Weight;
	fn swap() -> Weight;
}

/// Weights for pallet_x3_dex using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Pools` (r:1 w:1)
	/// Proof: `Pools` (`max_values`: None, `max_size`: Some(109), added: 584, mode: `MaxEncodedLen`)
	/// Storage: `NextPoolId` (r:1 w:0)
	/// Proof: `NextPoolId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn create_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `75`
		//  Estimated: `1087`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(36_000_000, 1087)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Pools` (r:1 w:1)
	/// Proof: `Pools` (`max_values`: None, `max_size`: Some(109), added: 584, mode: `MaxEncodedLen`)
	/// Storage: `LPPositions` (r:0 w:1)
	/// Proof: `LPPositions` (`max_values`: None, `max_size`: Some(40), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `NextPositionId` (r:1 w:1)
	/// Proof: `NextPositionId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn add_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `1602`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(46_000_000, 1602)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `LPPositions` (r:1 w:1)
	/// Proof: `LPPositions` (`max_values`: None, `max_size`: Some(40), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Pools` (r:1 w:1)
	/// Proof: `Pools` (`max_values`: None, `max_size`: Some(109), added: 584, mode: `MaxEncodedLen`)
	fn remove_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `1099`
		// Minimum execution time: 40_000_000 picoseconds.
		Weight::from_parts(41_000_000, 1099)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Pools` (r:1 w:1)
	/// Proof: `Pools` (`max_values`: None, `max_size`: Some(109), added: 584, mode: `MaxEncodedLen`)
	fn swap() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `75`
		//  Estimated: `584`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 584)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `Pools` (r:1 w:1)
	/// Proof: `Pools` (`max_values`: None, `max_size`: Some(109), added: 584, mode: `MaxEncodedLen`)
	/// Storage: `NextPoolId` (r:1 w:0)
	/// Proof: `NextPoolId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn create_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `75`
		//  Estimated: `1087`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(36_000_000, 1087)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Pools` (r:1 w:1)
	/// Proof: `Pools` (`max_values`: None, `max_size`: Some(109), added: 584, mode: `MaxEncodedLen`)
	/// Storage: `LPPositions` (r:0 w:1)
	/// Proof: `LPPositions` (`max_values`: None, `max_size`: Some(40), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `NextPositionId` (r:1 w:1)
	/// Proof: `NextPositionId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn add_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `1602`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(46_000_000, 1602)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `LPPositions` (r:1 w:1)
	/// Proof: `LPPositions` (`max_values`: None, `max_size`: Some(40), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Pools` (r:1 w:1)
	/// Proof: `Pools` (`max_values`: None, `max_size`: Some(109), added: 584, mode: `MaxEncodedLen`)
	fn remove_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `1099`
		// Minimum execution time: 40_000_000 picoseconds.
		Weight::from_parts(41_000_000, 1099)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Pools` (r:1 w:1)
	/// Proof: `Pools` (`max_values`: None, `max_size`: Some(109), added: 584, mode: `MaxEncodedLen`)
	fn swap() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `75`
		//  Estimated: `584`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 584)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}