#!/usr/bin/env bash
# Cross-artifact invariant: no sidecar-backlog method may also appear as an
# allowed direct-read method for the same route in the frontend route
# allowlist. Both artifacts are generated by `launchops scan`; if they ever
# overlap, the scanner has promoted a backlog RPC to direct-read without a
# human review step.
set -euo pipefail

allowlist=${ALLOWLIST_FILE:-.launchops/frontend_route_allowlist.json}
backlog=${BACKLOG_FILE:-.launchops/sidecar_adapter_backlog.json}

if [[ ! -f "$allowlist" ]]; then
  echo "::error::missing $allowlist; run 'cargo run -p launchops -- scan' first"
  exit 1
fi
if [[ ! -f "$backlog" ]]; then
  echo "::error::missing $backlog; run 'cargo run -p launchops -- scan' first"
  exit 1
fi

python3 - "$allowlist" "$backlog" <<'PY'
import json
import sys

allowlist_path, backlog_path = sys.argv[1], sys.argv[2]

with open(allowlist_path, encoding="utf-8") as handle:
    allowlist = json.load(handle)
with open(backlog_path, encoding="utf-8") as handle:
    backlog = json.load(handle)

allowed = {
    route["route_id"]: set(route.get("allowed_methods", []))
    for route in allowlist.get("routes", [])
}

overlaps = []
for entry in backlog.get("backlog", []):
    route_id = entry.get("route_id")
    method = entry.get("method")
    if route_id is None or method is None:
        continue
    if method in allowed.get(route_id, set()):
        overlaps.append((route_id, method))

if overlaps:
    print(
        "::error::sidecar backlog methods appear in the frontend allowlist "
        "for the same route; this contradicts sidecar ownership"
    )
    for route_id, method in overlaps:
        print(f"  - route={route_id} method={method}")
    sys.exit(1)

print("LaunchOps allowlist/backlog disjoint invariant: OK")
PY
