//! Autogenerated weights for pallet_x3_oracle
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-04-29, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `x3-dev`, CPU: `AMD EPYC 7742`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/x3 benchmark pallet --chain=dev --steps=50 --repeat=20 --pallet=pallet_x3_oracle --extrinsic=* --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=./pallets/x3-oracle/src/weights.rs --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_x3_oracle.
pub trait WeightInfo {
	fn authorize_oracle() -> Weight;
	fn deauthorize_oracle() -> Weight;
	fn submit_price() -> Weight;
}

/// Weights for pallet_x3_oracle using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `AuthorizedOracles` (r:1 w:1)
	/// Proof: `AuthorizedOracles` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn authorize_oracle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AuthorizedOracles` (r:1 w:1)
	/// Proof: `AuthorizedOracles` (`max_values`: None, `max_size`: `Some(52)`, added: 2527, mode: `MaxEncodedLen`)
	fn deauthorize_oracle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `2527`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 2527)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AuthorizedOracles` (r:1 w:0)
	/// Proof: `AuthorizedOracles` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `SubmissionsThisBlock` (r:1 w:1)
	/// Proof: `SubmissionsThisBlock` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `PriceSubmissions` (r:0 w:1)
	/// Proof: `PriceSubmissions` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	fn submit_price() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `5026`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 5026)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `AuthorizedOracles` (r:1 w:1)
	/// Proof: `AuthorizedOracles` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn authorize_oracle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AuthorizedOracles` (r:1 w:1)
	/// Proof: `AuthorizedOracles` (`max_values`: None, `max_size`: `Some(52)`, added: 2527, mode: `MaxEncodedLen`)
	fn deauthorize_oracle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `2527`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 2527)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AuthorizedOracles` (r:1 w:0)
	/// Proof: `AuthorizedOracles` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `SubmissionsThisBlock` (r:1 w:1)
	/// Proof: `SubmissionsThisBlock` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `PriceSubmissions` (r:0 w:1)
	/// Proof: `PriceSubmissions` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	fn submit_price() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `5026`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 5026)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}