#!/bin/bash
# X3 Bridge Relayer - Testnet Deployment Script
# Phase 13d: Testnet Go-Live
# 
# Usage: ./deploy-testnet.sh <infura_key>
# Example: ./deploy-testnet.sh 1a2b3c4d5e6f7g8h9i0j

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RELAYER_BIN="${PROJECT_ROOT}/target/release/x3-relayer"
CONFIG_FILE="${PROJECT_ROOT}/crates/x3-relayer/relayer-config.deployment.yaml"
LOG_FILE="${PROJECT_ROOT}/relayer.log"
DEPLOYMENT_TIME=$(date +%Y-%m-%d_%H-%M-%S)

# Functions
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

check_prerequisites() {
    log_info "Checking prerequisites..."
    
    # Check Infura key provided
    if [[ -z "${1:-}" ]]; then
        log_error "Infura API key required"
        echo "Usage: ./deploy-testnet.sh <infura_key>"
        exit 1
    fi
    
    # Check Rust is installed
    if ! command -v cargo &> /dev/null; then
        log_error "Rust not found. Install from https://rustup.rs/"
        exit 1
    fi
    
    # Check X3 node is running
    if ! curl -s http://localhost:9933 \
        -H "Content-Type: application/json" \
        -d '{"jsonrpc":"2.0","method":"system_health","params":[],"id":1}' &> /dev/null; then
        log_warn "X3 node at http://localhost:9933 not responding"
        log_info "Make sure X3 testnet is running: cargo run --release --bin x3-chain-node -- --testnet"
    else
        log_success "X3 testnet node is accessible"
    fi
    
    # Check RPC endpoints
    log_info "Checking RPC endpoints..."
    
    if curl -s "https://sepolia.infura.io/v3/${1}" \
        -X POST \
        -H "Content-Type: application/json" \
        -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' | grep -q "0x.*"; then
        log_success "Sepolia RPC is accessible"
    else
        log_error "Sepolia RPC not responding. Check your Infura key."
        exit 1
    fi
    
    if curl -s https://api.testnet.solana.com \
        -X POST \
        -H "Content-Type: application/json" \
        -d '{"jsonrpc":"2.0","method":"getHealth","params":[],"id":1}' | grep -q "ok"; then
        log_success "Solana testnet RPC is accessible"
    else
        log_warn "Solana testnet RPC not responding (optional, continues anyway)"
    fi
    
    log_success "Prerequisites check complete"
}

build_binary() {
    log_info "Building relayer binary (release mode)..."
    
    cd "${PROJECT_ROOT}"
    if cargo build --package x3-relayer --release 2>&1 | tail -5; then
        if [[ -f "${RELAYER_BIN}" ]]; then
            log_success "Relayer binary built: ${RELAYER_BIN}"
        else
            log_error "Build succeeded but binary not found"
            exit 1
        fi
    else
        log_error "Build failed"
        exit 1
    fi
}

create_config() {
    local infura_key="$1"
    
    log_info "Creating deployment configuration..."
    
    cat > "${CONFIG_FILE}" << EOF
# X3 Relayer Configuration - Testnet Deployment ($(date))
# Auto-generated by deploy-testnet.sh

x3:
  rpc_url: "http://localhost:9933"
  relayer_account: "5GrwvaEF5zXb26Fz9rcQkEvVkd7FcWI4twpBD6CFPhxGwwQ"

evm_chains:
  - name: "Sepolia Testnet"
    chain_id: 11155111
    x3_domain_id: 200
    rpc_endpoint: "https://sepolia.infura.io/v3/${infura_key}"
    state_root_contract: "0x0000000000000000000000000000000000000000"
    finality_threshold: 12
    block_poll_interval_ms: 13000
    max_concurrent_requests: 5

svm_clusters:
  - name: "Solana Testnet"
    cluster_name: "testnet"
    x3_domain_id: 501
    rpc_endpoint: "https://api.testnet.solana.com"
    finality_threshold: 32
    slot_poll_interval_ms: 15000
    max_concurrent_requests: 5

submission:
  batch_size: 1
  timeout_secs: 60
  max_retries: 3
  retry_backoff_ms: 1000

governance:
  poll_interval_secs: 5
  enable_graceful_shutdown: true

logging:
  level: "debug"
  format: "default"
EOF
    
    log_success "Configuration created: ${CONFIG_FILE}"
}

setup_environment() {
    log_info "Setting up environment variables..."
    
    export X3_LOG_LEVEL="debug"
    export X3_RPC_URL="http://localhost:9933"
    export X3_CONFIG_PATH="${CONFIG_FILE}"
    export RUST_LOG="x3_relayer=debug,x3_chain_runtime=info"
    
    log_success "Environment variables set:"
    echo "  X3_LOG_LEVEL=$X3_LOG_LEVEL"
    echo "  X3_RPC_URL=$X3_RPC_URL"
    echo "  X3_CONFIG_PATH=$X3_CONFIG_PATH"
    echo "  RUST_LOG=$RUST_LOG"
}

run_relayer() {
    log_info "Starting relayer service..."
    log_info "Logs will be written to: ${LOG_FILE}"
    
    # Backup previous log if it exists
    if [[ -f "${LOG_FILE}" ]]; then
        mv "${LOG_FILE}" "${LOG_FILE}.${DEPLOYMENT_TIME}"
        log_info "Previous log archived to: ${LOG_FILE}.${DEPLOYMENT_TIME}"
    fi
    
    # Run relayer with logging to both stdout and file
    {
        echo "==================================================================="
        echo "X3 Bridge Relayer - Testnet Deployment"
        echo "Started: $(date)"
        echo "Config: ${CONFIG_FILE}"
        echo "Binary: ${RELAYER_BIN}"
        echo "==================================================================="
        echo ""
    } | tee -a "${LOG_FILE}"
    
    log_success "Relayer service starting..."
    echo ""
    echo -e "${BLUE}Monitor logs with:${NC}"
    echo "  tail -f ${LOG_FILE}"
    echo ""
    echo -e "${BLUE}Key metrics to watch:${NC}"
    echo "  - blocks_polled (should increment every ~13s)"
    echo "  - blocks_finalized (should increment periodically)"
    echo "  - proofs_submitted (should increment after finalization)"
    echo ""
    echo -e "${YELLOW}Press Ctrl+C to stop the relayer${NC}"
    echo ""
    
    # Run the relayer
    exec "${RELAYER_BIN}" 2>&1 | tee -a "${LOG_FILE}"
}

# Main execution
main() {
    local infura_key="${1:-}"
    
    clear
    echo -e "${BLUE}"
    echo "╔════════════════════════════════════════════════════════════════╗"
    echo "║  X3 Bridge Relayer - Testnet Go-Live (Phase 13d)              ║"
    echo "║  Deployment Script                                            ║"
    echo "╚════════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    
    check_prerequisites "${infura_key}"
    build_binary
    create_config "${infura_key}"
    setup_environment
    run_relayer
}

# Run main
main "$@"
