// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";

/// @title FoundryReferralRouter — Referral/Affiliate System for X3 Foundry
/// @notice Referral/affiliate system that maps users to referrers and tracks referral revenue
/// @dev Uses pull-over-push pattern for reward claims
contract FoundryReferralRouter is Ownable, ReentrancyGuard {
    // ── Types ────────────────────────────────────────────────────────────────

    /// @notice Referral statistics for a referrer
    struct ReferralStats {
        uint256 totalReferrals;         // Total number of referred users
        uint256 activeReferrals;        // Number of active referred users
        uint256 totalRevenueGenerated;  // Total revenue generated by referrals (wei)
        uint256 totalRewardsClaimed;    // Total rewards claimed by referrer (wei)
        uint256 pendingRewards;         // Unclaimed rewards (wei)
        uint256 lastClaimTime;          // Timestamp of last claim
    }

    // ── State ────────────────────────────────────────────────────────────────

    /// @notice User address => referrer address
    mapping(address => address) public referrerOf;

    /// @notice Referrer address => ReferralStats
    mapping(address => ReferralStats) private _referralStats;

    /// @notice Whether a user has already set a referrer
    mapping(address => bool) private _hasReferrer;

    /// @notice List of all referrers
    address[] private _referrers;

    /// @notice Whether an address is tracked as a referrer
    mapping(address => bool) private _isReferrer;

    /// @notice Default referral reward basis points (e.g., 500 = 5%)
    uint256 public defaultRewardBps;

    /// @notice Maximum basis points
    uint256 public constant MAX_BPS = 10000;

    /// @notice Minimum referral reward basis points
    uint256 public constant MIN_REWARD_BPS = 100; // 1%

    /// @notice Maximum referral reward basis points
    uint256 public constant MAX_REWARD_BPS = 3000; // 30%

    // ── Events ───────────────────────────────────────────────────────────────

    /// @notice Emitted when a referrer is set for a user
    event ReferrerSet(
        address indexed user,
        address indexed referrer,
        uint256 timestamp
    );

    /// @notice Emitted when a referral is recorded (revenue generated)
    event ReferralRecorded(
        address indexed referrer,
        address indexed referredUser,
        uint256 revenueAmount,
        uint256 rewardAmount,
        uint256 timestamp
    );

    /// @notice Emitted when a referrer claims rewards
    event ReferralRewardsClaimed(
        address indexed referrer,
        uint256 amount,
        uint256 timestamp
    );

    /// @notice Emitted when default reward basis points are updated
    event DefaultRewardBpsUpdated(uint256 oldBps, uint256 newBps, uint256 timestamp);

    // ── Errors ───────────────────────────────────────────────────────────────

    error ZeroAddress();
    error SelfReferral();
    error ReferrerAlreadySet(address user);
    error ReferrerCannotBeZero();
    error InvalidRewardBps(uint256 bps);
    error NoRewardsToClaim();
    error TransferFailed();

    // ── Constructor ──────────────────────────────────────────────────────────

    constructor(uint256 _defaultRewardBps) {
        _transferOwnership(msg.sender);
        if (_defaultRewardBps < MIN_REWARD_BPS || _defaultRewardBps > MAX_REWARD_BPS) {
            revert InvalidRewardBps(_defaultRewardBps);
        }
        defaultRewardBps = _defaultRewardBps;
    }

    // ── Admin Functions ──────────────────────────────────────────────────────

    /// @notice Set the default referral reward basis points
    /// @param newBps The new reward basis points
    function setDefaultRewardBps(uint256 newBps) external onlyOwner {
        if (newBps < MIN_REWARD_BPS || newBps > MAX_REWARD_BPS) {
            revert InvalidRewardBps(newBps);
        }
        uint256 oldBps = defaultRewardBps;
        defaultRewardBps = newBps;
        emit DefaultRewardBpsUpdated(oldBps, newBps, block.timestamp);
    }

    // ── Core Functions ───────────────────────────────────────────────────────

    /// @notice Set a referrer for the caller
    /// @param referrer The referrer address
    function setReferrer(address referrer) external {
        if (referrer == address(0)) revert ZeroAddress();
        if (referrer == msg.sender) revert SelfReferral();
        if (_hasReferrer[msg.sender]) revert ReferrerAlreadySet(msg.sender);

        referrerOf[msg.sender] = referrer;
        _hasReferrer[msg.sender] = true;

        ReferralStats storage stats = _referralStats[referrer];
        stats.totalReferrals++;
        stats.activeReferrals++;

        if (!_isReferrer[referrer]) {
            _isReferrer[referrer] = true;
            _referrers.push(referrer);
        }

        emit ReferrerSet(msg.sender, referrer, block.timestamp);
    }

    /// @notice Record a referral event (revenue generated by a referred user)
    /// @param referredUser The user who generated revenue
    /// @param revenueAmount The revenue amount in wei
    function recordReferral(address referredUser, uint256 revenueAmount) external payable nonReentrant {
        if (referredUser == address(0)) revert ZeroAddress();
        if (revenueAmount == 0 && msg.value == 0) revert("NO_VALUE");

        address referrer = referrerOf[referredUser];
        if (referrer == address(0)) revert ReferrerCannotBeZero();

        uint256 actualAmount = revenueAmount > 0 ? revenueAmount : msg.value;
        uint256 rewardAmount = (actualAmount * defaultRewardBps) / MAX_BPS;

        ReferralStats storage stats = _referralStats[referrer];
        stats.totalRevenueGenerated += actualAmount;
        stats.pendingRewards += rewardAmount;

        emit ReferralRecorded(referrer, referredUser, actualAmount, rewardAmount, block.timestamp);
    }

    /// @notice Claim pending referral rewards (pull-over-push)
    /// @param amount The amount to claim
    function claimReferralRewards(uint256 amount) external nonReentrant {
        ReferralStats storage stats = _referralStats[msg.sender];
        if (stats.pendingRewards == 0) revert NoRewardsToClaim();
        if (amount > stats.pendingRewards) amount = stats.pendingRewards;

        stats.pendingRewards -= amount;
        stats.totalRewardsClaimed += amount;
        stats.lastClaimTime = block.timestamp;

        (bool success,) = payable(msg.sender).call{value: amount}("");
        if (!success) revert TransferFailed();

        emit ReferralRewardsClaimed(msg.sender, amount, block.timestamp);
    }

    /// @notice Claim all pending referral rewards
    function claimAllReferralRewards() external nonReentrant {
        ReferralStats storage stats = _referralStats[msg.sender];
        uint256 amount = stats.pendingRewards;
        if (amount == 0) revert NoRewardsToClaim();

        stats.pendingRewards = 0;
        stats.totalRewardsClaimed += amount;
        stats.lastClaimTime = block.timestamp;

        (bool success,) = payable(msg.sender).call{value: amount}("");
        if (!success) revert TransferFailed();

        emit ReferralRewardsClaimed(msg.sender, amount, block.timestamp);
    }

    // ── View Functions ───────────────────────────────────────────────────────

    /// @notice Get the referrer for a user
    /// @param user The user address
    /// @return The referrer address (address(0) if none)
    function getReferrer(address user) external view returns (address) {
        return referrerOf[user];
    }

    /// @notice Get referral stats for a referrer
    /// @param referrer The referrer address
    /// @return ReferralStats struct
    function getReferralStats(address referrer) external view returns (ReferralStats memory) {
        return _referralStats[referrer];
    }

    /// @notice Check if a user has a referrer set
    /// @param user The user address
    /// @return True if referrer is set
    function hasReferrer(address user) external view returns (bool) {
        return _hasReferrer[user];
    }

    /// @notice Get total number of referrers
    /// @return count The referrer count
    function getReferrerCount() external view returns (uint256) {
        return _referrers.length;
    }

    /// @notice Get referrer at index
    /// @param index The index
    /// @return referrer The referrer address
    function getReferrerAt(uint256 index) external view returns (address) {
        return _referrers[index];
    }

    /// @notice Calculate the reward amount for a given revenue
    /// @param revenueAmount The revenue amount
    /// @return rewardAmount The calculated reward
    function calculateReward(uint256 revenueAmount) external view returns (uint256) {
        return (revenueAmount * defaultRewardBps) / MAX_BPS;
    }
}
