export interface GrantAngleCategory {
  category: string
  icon: string
  color: string
  items: { title: string; desc: string; status: string }[]
}

export const GRANT_ANGLES: GrantAngleCategory[] = [
  {
    category: 'X3 Atomic Star L1 Chain',
    icon: '⬡',
    color: '#00c8ff',
    items: [
      { title: 'Core Blockchain Development', desc: 'Substrate FRAME runtime, pallets, node infrastructure', status: 'active' },
      { title: 'Public Testnet', desc: 'Multi-validator testnet with bootstrap tooling and documentation', status: 'active' },
      { title: 'Mainnet Readiness', desc: 'Launch gate enforcement, invariant hardening, security review', status: 'in-progress' },
      { title: 'Validator Onboarding', desc: 'Independent operator recruitment, setup automation, monitoring', status: 'in-progress' },
      { title: 'Chain Launch Infrastructure', desc: 'Genesis config, bootnodes, DNS, CI/CD pipelines', status: 'planned' },
    ],
  },
  {
    category: 'Cross-VM Atomic Settlement',
    icon: '⟁',
    color: '#8b5cf6',
    items: [
      { title: 'EVM Adapter', desc: 'Frontier-based EVM execution via X3Evm domain', status: 'active' },
      { title: 'SVM / Solana Adapter', desc: 'Solana BPF execution via X3Svm domain', status: 'active' },
      { title: 'BTC Integration', desc: 'Bitcoin script verification through BTC Fortress vault', status: 'in-progress' },
      { title: 'Substrate / Polkadot Interop', desc: 'XCMP-like cross-chain messaging for Substrate chains', status: 'in-progress' },
      { title: 'Cosmos / CosmWasm Adapter', desc: 'IBC-compatible cross-chain settlement', status: 'planned' },
      { title: 'X3VM Native', desc: 'Native execution domain for X3 runtime', status: 'active' },
    ],
  },
  {
    category: 'Atomic Swap / Bridge System',
    icon: '⇋',
    color: '#f97316',
    items: [
      { title: 'HTLC Atomicity', desc: 'Hash Time Locked Contracts for atomic cross-chain swaps', status: 'active' },
      { title: 'Lock / Claim / Refund Paths', desc: 'Complete settlement lifecycle with timeout-safe refund', status: 'active' },
      { title: 'Timeout Engine', desc: 'Configurable timeout enforcement with automatic refund' },
      { title: 'Cross-Chain Proof Ledger', desc: 'Verifiable evidence log for every cross-chain action', status: 'in-progress' },
      { title: 'Finality Oracle', desc: 'Multi-source finality verification before execution', status: 'in-progress' },
      { title: 'Relayer Swarm', desc: 'Decentralized relayer coordination with attestation', status: 'planned' },
      { title: 'RPC Quorum', desc: 'Multi-endpoint RPC validation to prevent single-source failure', status: 'planned' },
      { title: 'Slashing for Misbehavior', desc: 'Economic penalty for invalid attestations', status: 'planned' },
      { title: 'Chain Health Monitor', desc: 'Cross-chain health tracking with alerting', status: 'planned' },
    ],
  },
  {
    category: 'x3-lang Intent Language',
    icon: '⟨⟩',
    color: '#22c55e',
    items: [
      { title: '.x3 Language / Compiler', desc: 'Cross-chain intent language with Rust compiler pipeline', status: 'active' },
      { title: 'Cross-Chain Intent Language', desc: 'Declarative syntax for multi-VM contract intents', status: 'active' },
      { title: 'Bridge / Swap Commands', desc: 'Built-in primitives for atomic swaps and bridge actions', status: 'in-progress' },
      { title: 'Governance & Treasury Commands', desc: 'On-chain governance and treasury intent instructions', status: 'planned' },
      { title: 'Agent / Swarm Instructions', desc: 'AI agent orchestration primitives in .x3', status: 'planned' },
      { title: 'GPU Validation Hooks', desc: 'GPU-accelerated proof verification callbacks', status: 'planned' },
      { title: 'Testnet-Safe Scripting', desc: 'Sandboxed execution environment for testnet development', status: 'planned' },
    ],
  },
  {
    category: 'GPU Validator Swarm',
    icon: '◈',
    color: '#ef4444',
    items: [
      { title: 'GPU-Accelerated Validation', desc: 'GPU-based transaction validation and proof generation', status: 'in-progress' },
      { title: 'Signature Batching', desc: 'Batch signature verification using GPU parallelism', status: 'planned' },
      { title: 'Parallel Execution', desc: 'GPU-assisted parallel transaction execution research', status: 'planned' },
      { title: 'Benchmark Reports', desc: 'Standardized GPU validator performance benchmarks', status: 'active' },
      { title: 'Validator Performance Layer', desc: 'GPU telemetry and performance scoring infrastructure', status: 'in-progress' },
      { title: 'Hardware / Cloud Compute Grants', desc: 'GPU sponsorship and cloud credit programs for validators', status: 'active' },
    ],
  },
  {
    category: 'X3 Testnet',
    icon: '◎',
    color: '#4a6a88',
    items: [
      { title: 'Incentivized Testnet', desc: 'Reward programs for testnet participation and bug discovery', status: 'planned' },
      { title: 'Validator Labs', desc: 'Physical validator lab with standardized hardware setups', status: 'active' },
      { title: 'Node Bootstrap Kits', desc: 'Automated node deployment scripts and documentation', status: 'active' },
      { title: 'Public Testnet Dashboard', desc: 'Live testnet health, validator, and explorer dashboards', status: 'in-progress' },
      { title: 'Chaos Testing', desc: 'Network fault injection and failure scenario simulations', status: 'planned' },
      { title: 'Benchmarking Framework', desc: 'Standardized benchmark suite for testnet performance', status: 'in-progress' },
      { title: 'Attestation Proof System', desc: 'Validator attestation of testnet execution with proofs', status: 'planned' },
    ],
  },
  {
    category: 'Validator Infrastructure',
    icon: '▪',
    color: '#3b82f6',
    items: [
      { title: 'Bare-Metal Machines', desc: 'Physical servers for validator and archive node operation', status: 'active' },
      { title: 'RPC Nodes', desc: 'Load-balanced public RPC endpoint infrastructure', status: 'active' },
      { title: 'Archive Nodes', desc: 'Full chain history nodes for explorer and developer access', status: 'in-progress' },
      { title: 'Networking Gear', desc: 'Switches, routers, and 10GbE+ networking equipment', status: 'active' },
      { title: 'Storage', desc: 'NVMe and SSD storage for blockchain data and indexing', status: 'active' },
      { title: 'Power Backups', desc: 'UPS and redundant power for validator lab', status: 'in-progress' },
      { title: 'Hardware Wallets', desc: 'Hardware security modules and signing devices', status: 'in-progress' },
      { title: 'Recycled Server Sponsorships', desc: 'Repurposed enterprise server donation program', status: 'active' },
    ],
  },
  {
    category: 'RPC Infrastructure',
    icon: '↗',
    color: '#06b6d4',
    items: [
      { title: 'Self-Hosted RPCs', desc: 'Dedicated RPC nodes with high availability configuration', status: 'active' },
      { title: 'Paid RPC Support', desc: 'Premium RPC tier for developers with SLA guarantees', status: 'planned' },
      { title: 'RPC Failover', desc: 'Automatic RPC endpoint failover for uninterrupted service', status: 'planned' },
      { title: 'RPC Quorum', desc: 'Multi-node RPC consensus for critical operations', status: 'planned' },
      { title: 'Rate-Limit Protection', desc: 'DDoS mitigation and fair-use rate limiting for public RPC', status: 'in-progress' },
      { title: 'Mainnet-Grade Routing', desc: 'Geo-distributed load balancing with latency optimization', status: 'planned' },
    ],
  },
  {
    category: 'X3 Proof Dashboard',
    icon: '⊞',
    color: '#84cc16',
    items: [
      { title: 'Feature Completion Scoreboard', desc: 'Live readiness scoreboard for all tracked features', status: 'active' },
      { title: 'Proof-of-Work-Done Ledger', desc: 'Machine-readable evidence ledger for milestone completion', status: 'in-progress' },
      { title: 'TPS / Finality Dashboard', desc: 'Real-time transaction throughput and finality visualization', status: 'active' },
      { title: 'Failed Transaction Rate', desc: 'Transaction failure tracking with root cause analysis', status: 'in-progress' },
      { title: 'Invariant Checks', desc: 'Live system invariant monitoring with alerting', status: 'in-progress' },
      { title: 'Cross-VM Settlement Proof', desc: 'Verified cross-VM settlement evidence dashboard', status: 'planned' },
      { title: 'Public Transparency Portal', desc: 'Open access to all proof records and progress data', status: 'planned' },
    ],
  },
  {
    category: 'Security & Audits',
    icon: '⊟',
    color: '#f59e0b',
    items: [
      { title: 'Security Audits', desc: 'External audit preparation and independent security review', status: 'active' },
      { title: 'Formal Verification', desc: 'Formal proof of core invariants and atomicity properties', status: 'planned' },
      { title: 'Invariant Testing', desc: 'Comprehensive invariant test suite for all system properties', status: 'in-progress' },
      { title: 'Bridge Security', desc: 'Cross-chain gateway security hardening and attack surface reduction', status: 'active' },
      { title: 'Fuzzing Infrastructure', desc: 'Continuous fuzz testing of runtime and pallet code', status: 'planned' },
      { title: 'Red-Team Testing', desc: 'Adversarial security testing against X3 infrastructure', status: 'planned' },
      { title: 'No-Mock / No-Fake Proof Gates', desc: 'Gate enforcement preventing stub and placeholder code', status: 'active' },
    ],
  },
  {
    category: 'Open Source Public Goods',
    icon: '⎔',
    color: '#14b8a6',
    items: [
      { title: 'Developer SDKs', desc: 'TypeScript and Rust SDKs for X3 chain interaction', status: 'active' },
      { title: 'Documentation', desc: 'Developer guides, API references, and integration tutorials', status: 'active' },
      { title: 'Example Apps', desc: 'Reference implementations for common X3 use cases', status: 'active' },
      { title: 'Testnet Tooling', desc: 'Faucet, explorer, and developer tools for testnet', status: 'in-progress' },
      { title: 'Chain Explorer', desc: 'Open-source block explorer for X3 testnet and mainnet', status: 'in-progress' },
      { title: 'Wallet Integrations', desc: 'Multi-wallet support for X3 token and contract interaction', status: 'in-progress' },
      { title: 'Builder Onboarding', desc: 'Starter guides and workshops for new X3 developers', status: 'active' },
    ],
  },
  {
    category: 'X3 Agent Runtime',
    icon: '◉',
    color: '#a855f7',
    items: [
      { title: 'Agent Registry', desc: 'On-chain registry for AI agent identity and permissions', status: 'active' },
      { title: 'Model Registry', desc: 'Registry for AI models with versioning and attestation', status: 'planned' },
      { title: 'Task Market', desc: 'Decentralized marketplace for agent task bidding and execution', status: 'planned' },
      { title: 'Agent Staking', desc: 'Economic stake for agent accountability and reliability', status: 'planned' },
      { title: 'Proof-of-Work Attestations', desc: 'Verifiable execution proofs for agent actions', status: 'in-progress' },
      { title: 'Reputation System', desc: 'On-chain reputation scoring for agents and operators', status: 'planned' },
      { title: 'On-Chain Payments for AI', desc: 'Token-based payment rail for AI agent services', status: 'planned' },
    ],
  },
  {
    category: 'AI Builder Swarm',
    icon: '◉',
    color: '#ec4899',
    items: [
      { title: 'Code-Writing Agents', desc: 'Multi-agent coding assistants for X3 development', status: 'active' },
      { title: 'Auditor Agents', desc: 'Automated security and compliance auditing agents', status: 'active' },
      { title: 'Grant-Finder Agents', desc: 'AI-powered grant opportunity discovery and matching', status: 'in-progress' },
      { title: 'Docsmith Agents', desc: 'Automated documentation generation and maintenance', status: 'active' },
      { title: 'Test Agents', desc: 'Autonomous test generation and execution agents', status: 'in-progress' },
      { title: 'Security Agents', desc: 'Continuous security monitoring and threat detection agents', status: 'in-progress' },
      { title: 'Proof-Mode Coding Workflows', desc: 'AI-assisted development with proof requirement enforcement', status: 'active' },
    ],
  },
  {
    category: 'X3 Funding OS',
    icon: '⊡',
    color: '#0ea5e9',
    items: [
      { title: 'Grant Crawler', desc: 'Automated grant opportunity scraping and filtering', status: 'in-progress' },
      { title: 'Eligibility Scorer', desc: 'AI-powered grant eligibility assessment and scoring', status: 'planned' },
      { title: 'Proposal Writer', desc: 'AI-assisted grant proposal generation with evidence linking', status: 'planned' },
      { title: 'Evidence-Pack Builder', desc: 'Automated milestone evidence compilation from code', status: 'in-progress' },
      { title: 'Submission Tracker', desc: 'Multi-grant submission status tracking and reminders', status: 'planned' },
      { title: 'Funder-Update System', desc: 'Automated milestone reporting and funder communication', status: 'planned' },
      { title: 'Compliance Archive', desc: 'Grant compliance documentation and audit trail storage', status: 'planned' },
      { title: 'CRM for Funders', desc: 'Funder relationship management and outreach automation', status: 'planned' },
    ],
  },
  {
    category: 'Auditor Grants',
    icon: '⌂',
    color: '#64748b',
    items: [
      { title: 'Security Audit Funding', desc: 'Grant funding for external security audits', status: 'active' },
      { title: 'Independent Review Funding', desc: 'Third-party code review and architecture assessment', status: 'active' },
      { title: 'Compliance Review Funding', desc: 'Regulatory compliance and standards alignment audits', status: 'planned' },
      { title: 'Proof Reports for Funders', desc: 'Machine-readable audit reports for grant compliance', status: 'in-progress' },
    ],
  },
  {
    category: 'Cloud / GPU Credits',
    icon: '⊡',
    color: '#38bdf8',
    items: [
      { title: 'NVIDIA GPU Programs', desc: 'NVIDIA Inception GPU credits and developer tools', status: 'active' },
      { title: 'Google / AWS / Azure Credits', desc: 'Cloud startup credits for infrastructure and compute', status: 'active' },
      { title: 'GPU Cloud Credits', desc: 'Specialized GPU cloud provider sponsorship programs', status: 'active' },
      { title: 'Database / Software Credits', desc: 'Infrastructure software and database service credits', status: 'in-progress' },
      { title: 'Monitoring / Observability Credits', desc: 'Grafana, Datadog, and monitoring service credits', status: 'in-progress' },
    ],
  },
  {
    category: 'STARDEX / X3 DeFi Layer',
    icon: '◈',
    color: '#f43f5e',
    items: [
      { title: 'Native AMM DEX', desc: 'AXE DEX with concentrated liquidity and flash loans', status: 'active' },
      { title: 'Cross-Chain Routing', desc: 'Multi-VM swap routing via Atomic Gateway', status: 'in-progress' },
      { title: 'Intent Routing', desc: 'Declarative swap intent execution via solver marketplace', status: 'planned' },
      { title: 'Solver Marketplace', desc: 'Competitive solver bidding for complex trade execution', status: 'planned' },
      { title: 'Liquidity Tooling', desc: 'Liquidity provision incentives and management tools', status: 'in-progress' },
      { title: 'Launchpad', desc: 'Token presale and launch platform for ecosystem projects', status: 'in-progress' },
      { title: 'Treasury Fees', desc: 'Protocol fee management and treasury allocation', status: 'planned' },
    ],
  },
  {
    category: 'Universal Asset Kernel',
    icon: '⎔',
    color: '#10b981',
    items: [
      { title: 'Lock / Mint / Burn / Release', desc: 'Canonical cross-chain asset lifecycle with invariant checks', status: 'active' },
      { title: 'Canonical Asset Handling', desc: 'Unified asset accounting across all execution domains', status: 'active' },
      { title: 'Cross-Chain Asset Movement', desc: 'Atomic asset transfer between VM domains', status: 'active' },
      { title: 'Proof-Backed Settlement', desc: 'Cryptographically verified settlement for all asset moves', status: 'in-progress' },
    ],
  },
  {
    category: 'Atomic Gateway',
    icon: '⤚',
    color: '#6366f1',
    items: [
      { title: 'Bridge Gateway', desc: 'Governance-gated cross-chain bridge infrastructure', status: 'active' },
      { title: 'Multi-VM Settlement Portal', desc: 'Unified settlement interface across VMs', status: 'in-progress' },
      { title: 'Cross-Chain Route Execution', desc: 'End-to-end cross-chain message delivery with proofs', status: 'active' },
      { title: 'BTC / EVM / SVM / X3VM Interop', desc: 'Full interoperability matrix for all supported VMs', status: 'in-progress' },
    ],
  },
  {
    category: 'Governance & Treasury',
    icon: '⌘',
    color: '#eab308',
    items: [
      { title: 'On-Chain Treasury', desc: 'DAO-managed treasury for ecosystem funding allocation', status: 'active' },
      { title: 'Grant Distribution', desc: 'On-chain grant distribution with milestone verification', status: 'in-progress' },
      { title: 'Builder Funding', desc: 'Direct funding mechanism for ecosystem developers', status: 'in-progress' },
      { title: 'Validator Rewards', desc: 'Automated validator reward distribution from fees', status: 'active' },
      { title: 'DAO Public Goods Funding', desc: 'Community-voted public goods funding allocation', status: 'planned' },
    ],
  },
  {
    category: 'X3 Starport & 3D Frontend',
    icon: '★',
    color: '#fbbf24',
    items: [
      { title: 'Playable Chain Explorer', desc: '3D interactive blockchain explorer with visual block flow', status: 'active' },
      { title: 'Wallet Dashboard', desc: 'Unified wallet interface for multi-VM token management', status: 'active' },
      { title: 'Validator Forest', desc: '3D validator visualization with real-time health indicators', status: 'active' },
      { title: 'DEX Arena', desc: '3D trading interface for AXE DEX visualization', status: 'in-progress' },
      { title: 'Treasury Vault', desc: 'Treasury management and visualization dashboard', status: 'planned' },
      { title: 'Developer Grant Tower', desc: 'Grant opportunity visualization and tracking interface', status: 'planned' },
      { title: 'Compute Cluster View', desc: 'GPU compute utilization and validator performance viz', status: 'planned' },
    ],
  },
  {
    category: 'Media & Community',
    icon: '≡',
    color: '#78716c',
    items: [
      { title: 'Donation Portal', desc: 'Direct donation acceptance with transparent use reporting', status: 'active' },
      { title: 'Hardware Sponsorship Portal', desc: 'Hardware donation intake and sponsor recognition', status: 'active' },
      { title: 'Public Milestone Pages', desc: 'Public-facing milestone completion and progress tracking', status: 'in-progress' },
      { title: 'Media Outreach', desc: 'Technical content, case studies, and community building', status: 'active' },
      { title: 'Funder Transparency Pages', desc: 'Public funder recognition and use-of-funds reporting', status: 'planned' },
    ],
  },
  {
    category: 'Green / Recycled Compute',
    icon: '♻',
    color: '#22c55e',
    items: [
      { title: 'Recycled Servers', desc: 'Repurposed enterprise hardware for validator operations', status: 'active' },
      { title: 'Efficient Validator Labs', desc: 'Low-power validator configuration research', status: 'active' },
      { title: 'Lower-Cost Infrastructure', desc: 'Cost-optimized infrastructure design for decentralization', status: 'active' },
      { title: 'Green Compute Sponsorships', desc: 'Carbon-aware compute scheduling and renewable energy', status: 'planned' },
    ],
  },
  {
    category: 'BTC Integration',
    icon: '₿',
    color: '#f7931a',
    items: [
      { title: 'BTC Adapter', desc: 'Bitcoin script verification and transaction parsing', status: 'active' },
      { title: 'BTC Proof / Guard Layer', desc: 'Bitcoin PoW verification and SPV proof validation', status: 'active' },
      { title: 'Testnet-First BTC Support', desc: 'Bitcoin testnet integration with full state machine', status: 'active' },
      { title: 'Atomic BTC Settlement Path', desc: 'Canonical xBTC with Atomic Kernel supply enforcement', status: 'in-progress' },
    ],
  },
  // ─── 10 NEW GRANT ANGLES ─────────────────────────────────────────────────
  {
    category: 'Zero-Knowledge Proof Layer',
    icon: '⊡',
    color: '#a78bfa',
    items: [
      { title: 'ZK Settlement Proofs', desc: 'Zero-knowledge proofs for cross-chain settlement verification', status: 'planned' },
      { title: 'ZK Bridge Proofs', desc: 'ZK-based bridge attestation for trust-minimized cross-chain messages', status: 'planned' },
      { title: 'ZK Attestation', desc: 'ZK proof of validator attestation for privacy-preserving verification', status: 'planned' },
      { title: 'Proof Compression', desc: 'ZK proof aggregation and compression for cross-chain scalability', status: 'planned' },
    ],
  },
  {
    category: 'Decentralized Identity & Reputation',
    icon: '⊛',
    color: '#06b6d4',
    items: [
      { title: 'Builder IDs', desc: 'Self-sovereign identity for X3 ecosystem developers and contributors', status: 'planned' },
      { title: 'Validator Reputation', desc: 'On-chain validator reliability and performance scoring', status: 'planned' },
      { title: 'Agent Reputation', desc: 'Reputation tracking for AI agent reliability and task completion', status: 'planned' },
      { title: 'Anti-Sybil Scoring', desc: 'Sybil resistance mechanisms for grant distribution and governance', status: 'planned' },
    ],
  },
  {
    category: 'MEV Protection & Fair Ordering',
    icon: '⇌',
    color: '#f43f5e',
    items: [
      { title: 'Fair Sequencing', desc: 'Transaction ordering fairness mechanisms to prevent frontrunning', status: 'planned' },
      { title: 'Private Mempool', desc: 'Encrypted transaction mempool for user protection', status: 'planned' },
      { title: 'MEV-Resistant Routing', desc: 'Solver-agnostic routing with MEV mitigation', status: 'planned' },
      { title: 'Solver Fairness', desc: 'Equal-access solver marketplace with transparent matching', status: 'planned' },
      { title: 'User Protection', desc: 'Transaction simulation and sandboxing for user safety', status: 'planned' },
    ],
  },
  {
    category: 'Cross-Chain Incident Response Lab',
    icon: '⚠',
    color: '#ef4444',
    items: [
      { title: 'Emergency Rollback Drills', desc: 'Simulated chain halt and recovery scenario training', status: 'planned' },
      { title: 'Bridge Exploit Simulations', desc: 'Red-team bridge attack simulations and defense hardening', status: 'planned' },
      { title: 'Chain Halt Policies', desc: 'Documented and tested chain halt and resume procedures', status: 'planned' },
      { title: 'Disaster Testing', desc: 'Adversarial infrastructure failure testing and recovery validation', status: 'planned' },
    ],
  },
  {
    category: 'Academic Research Partnerships',
    icon: '⌨',
    color: '#8b5cf6',
    items: [
      { title: 'Cross-VM Execution Research', desc: 'University partnerships for cross-VM execution model research', status: 'planned' },
      { title: 'Distributed Systems Grants', desc: 'Academic research on blockchain consensus and networking', status: 'planned' },
      { title: 'GPU Validation Research', desc: 'GPU-accelerated transaction validation academic collaboration', status: 'planned' },
      { title: 'Formal Methods Research', desc: 'Formal verification and proof theory research partnerships', status: 'planned' },
      { title: 'Agentic Blockchain Research', desc: 'AI agent coordination on blockchain academic programs', status: 'planned' },
    ],
  },
  {
    category: 'Developer Education Program',
    icon: '⌂',
    color: '#14b8a6',
    items: [
      { title: 'X3 Academy', desc: 'Structured developer education program for X3 ecosystem', status: 'planned' },
      { title: '.x3 Tutorials', desc: 'Hands-on tutorials for cross-chain intent language development', status: 'in-progress' },
      { title: 'Validator Bootcamp', desc: 'Training program for independent validator operators', status: 'planned' },
      { title: 'Grant-Writing Bootcamp', desc: 'Ecosystem grant writing and proposal development training', status: 'planned' },
      { title: 'Builder Certification', desc: 'Certification program for X3 ecosystem developers and operators', status: 'planned' },
    ],
  },
  {
    category: 'Decentralized Archive / Indexing',
    icon: '▣',
    color: '#0ea5e9',
    items: [
      { title: 'Archive Nodes', desc: 'Dedicated archive infrastructure for full chain history', status: 'in-progress' },
      { title: 'Proof Indexing', desc: 'Indexed proof records for cross-chain settlement verification', status: 'planned' },
      { title: 'Cross-Chain Event Indexing', desc: 'Unified event index across all supported VM domains', status: 'planned' },
      { title: 'Replayable Settlement Logs', desc: 'Deterministic replay of settlement history for audit', status: 'planned' },
      { title: 'Public Data APIs', desc: 'Open APIs for blockchain data access and integration', status: 'in-progress' },
    ],
  },
  {
    category: 'Regulatory Transparency Tooling',
    icon: '▤',
    color: '#64748b',
    items: [
      { title: 'Fund-Use Reporting', desc: 'Automated grant fund utilization reports with evidence links', status: 'planned' },
      { title: 'Treasury Dashboards', desc: 'Public treasury transaction dashboard with categorization', status: 'planned' },
      { title: 'Audit Trails', desc: 'Immutable audit trail for all treasury and grant operations', status: 'planned' },
      { title: 'Foundation Paperwork', desc: 'Regulatory compliance documentation and filing automation', status: 'planned' },
      { title: 'Grant Compliance Automation', desc: 'Automated compliance checks for grant milestone reporting', status: 'planned' },
    ],
  },
  {
    category: 'Public Benchmark Commons',
    icon: '⊞',
    color: '#84cc16',
    items: [
      { title: 'TPS Benchmark Datasets', desc: 'Open dataset of standardized TPS measurements and methodology', status: 'in-progress' },
      { title: 'Finality Benchmarks', desc: 'Cross-chain finality measurement and comparison data', status: 'planned' },
      { title: 'Bridge Safety Metrics', desc: 'Open benchmark framework for bridge security evaluation', status: 'planned' },
      { title: 'RPC Reliability Dataset', desc: 'Geographic RPC latency and reliability measurement data', status: 'planned' },
      { title: 'GPU Validation Benchmarks', desc: 'GPU validator performance comparison benchmarks', status: 'planned' },
      { title: 'Agent Performance Data', desc: 'AI agent task execution performance benchmark datasets', status: 'planned' },
    ],
  },
  {
    category: 'Real-World Pilot Grants',
    icon: '⊡',
    color: '#f97316',
    items: [
      { title: 'University Pilots', desc: 'Paid pilot programs with universities using X3 testnet', status: 'planned' },
      { title: 'Municipal Pilots', desc: 'Public sector pilot programs for blockchain infrastructure', status: 'planned' },
      { title: 'Public-Good Org Pilots', desc: 'Nonprofit and public-good organization testnet pilots', status: 'planned' },
      { title: 'Open-Source Group Pilots', desc: 'Open-source project collaboration and integration pilots', status: 'planned' },
      { title: 'Fintech/Blockchain Pilots', desc: 'Small-scale fintech pilots testing X3 settlement infrastructure', status: 'planned' },
    ],
  },
]

export const TOTAL_ANGLES = GRANT_ANGLES.reduce((sum, c) => sum + c.items.length, 0)
