#!/usr/bin/env bash
set -euo pipefail

echo "=================================================="
echo " X3 SWARM YOLO BUILD"
echo " The Chain That Builds Itself"
echo "=================================================="

mkdir -p reports logs/swarm data/agent-memory

forbidden_found=$(find . \
  -path './.git' -prune -o \
  -path '*/target' -prune -o \
  -path '*/node_modules' -prune -o \
  \( -name '.env' -o -name '.env.*' -o -name '*.key' -o -name '*_seed*' -o -name '*-seed*' -o -name '*private_key*' \) \
  -print)

echo "[1/9] Validate forbidden safety files"
if [ -n "$forbidden_found" ]; then
  printf "%s\n" "$forbidden_found" > reports/swarm_secret_warning.md
  echo "WARNING: Possible secret files found. Swarm must not read or edit them."
fi

echo "[2/9] Ensure memory files"
for f in builder auditor breaker fixer benchmark marketing grants lessons; do
  touch "data/agent-memory/${f}.jsonl"
done

echo "[3/9] GPU inventory"
if [ -x scripts/gpu/gpu_inventory.sh ]; then
  scripts/gpu/gpu_inventory.sh > reports/gpu_inventory_report.md || true
fi

echo "[4/9] Swarm scan"
if [ -x scripts/swarm/swarm_scan.sh ]; then
  scripts/swarm/swarm_scan.sh
fi

echo "[5/9] Rust swarm tests"
if cargo test -p x3-swarm-core -- --nocapture; then
  echo "Swarm core tests passed."
else
  echo "Swarm core tests failed." >&2
fi

echo "[6/9] Swarm API health"
if [ -x scripts/swarm/swarm_health.sh ]; then
  scripts/swarm/swarm_health.sh || true
fi

echo "[7/9] Generate task queue"
if cargo run -p x3-readiness -- swarm-tasks --out reports; then
  echo "Generated swarm task queue."
elif [ -x scripts/swarm/swarm_task_queue.sh ]; then
  scripts/swarm/swarm_task_queue.sh > reports/swarm_task_queue.json || true
fi

echo "[8/9] Generate swarm report"
cat > reports/swarm_build_report.md <<REPORT
# X3 Swarm Build Report

Generated by scripts/swarm/yolo_build_swarm.sh

Required components:
- crates/x3-swarm-core
- crates/x3-swarm-core/services/x3-swarm-api
- crates/x3-swarm-core/services/x3-swarm-worker
- scripts/swarm
- scripts/gpu
- data/agent-memory
- apps/tauri-os/src/apps/SwarmCommand
- reports/swarm_task_queue.json
- reports/swarm_build_report.md

Hard safety:
- Mainnet edits blocked
- BTC mainnet blocked
- External bridge mainnet blocked
- Keys and .env blocked
- Runtime/pallet/bridge edits require approval
REPORT

echo "[9/9] Done"
echo "Swarm YOLO build complete. Check reports/swarm_build_report.md"
