//! Production EVM receipt proof verifier.
//!
//! This module provides `ProductionEvmReceiptVerifier`, the verifier that
//! `X3-contracts/evm/contracts/X3ExternalGateway.sol` and the
//! `pallet-x3-crosschain-gateway` pallet both rely on for the
//! `X3_DEPOSIT_V1` ↔ `WithdrawalReleased` round-trip. The previous verifier
//! in this crate was a structural stub that only checked for a non-empty
//! payload — it would have accepted any random bytes as a valid proof.
//!
//! The verifier here performs the four real checks:
//!
//!   1. **Decoding.** The payload is a 16-byte header followed by a
//!      4-tuple of length-prefixed sections: `[header | receipt |
//!      receipt_index | inclusion_proof]`. Each section is decoded with
//!      the standard Ethereum RLP codec.
//!   2. **Merkle Patricia inclusion.** The receipt is verified to be
//!      included in the block whose `receipts_root` the caller asserts.
//!      The proof is the sequence of trie nodes from the receipt trie
//!      root down to the leaf, encoded as a flat RLP list of node byte
//!      strings.
//!   3. **Receipt semantics.** The decoded receipt is required to encode
//!      exactly one log whose first topic equals the configured event
//!      selector, and whose data decodes to a uint256 amount matching
//!      `expected_amount`. The log's address is bound to the caller-
//!      supplied gateway address.
//!   4. **Confirmations.** The block height and current chain head (the
//!      head is supplied at verify time because it is a runtime
//!      concern) are checked against `min_confirmations`.
//!
//! Production builds MUST register this verifier; the legacy
//! `NonEmptyPayloadVerifier` is retained for unit tests only and is
//! feature-gated behind `test-verifier` in the router.

extern crate alloc;

use alloc::vec::Vec;
use core::fmt::{Display, Formatter};
use core::option::Option;
use core::option::Option::{None, Some};
use core::result::Result;
use core::result::Result::{Err, Ok};

use tiny_keccak::{Hasher, Keccak};

use crate::{
    ChainKind, ProofEnvelope, VerificationError, VerificationOutcome, VerificationStrategy,
    Verifier,
};

// ── Public error type ──────────────────────────────────────────────────────

/// Errors specific to EVM receipt verification. The `Verifier` trait
/// collapses these into `VerificationError::MalformedProof` (or
/// `UnsupportedChain`) so callers see a unified error surface, but the
/// variants are useful for tests and for richer on-chain event metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EvmReceiptError {
    /// Payload was too short to contain the wire header.
    TooShort,
    /// The RLP header did not parse.
    BadHeader,
    /// The RLP receipt did not parse.
    BadReceipt,
    /// The Merkle Patricia proof did not parse as a list of node byte
    /// strings.
    BadProof,
    /// The receipt was not included in the asserted receipts root.
    InclusionFailed,
    /// The receipt did not contain exactly one log.
    WrongLogCount,
    /// The log's first topic did not match the expected event selector.
    BadSelector,
    /// The log data was not decodable as a single uint256 amount.
    BadAmount,
    /// The block has not accumulated enough confirmations.
    InsufficientConfirmations { have: u64, need: u64 },
    /// The receipt was generated by a chain the verifier is not bound to.
    WrongChain { expected: u64, got: u64 },
}

impl From<rlp::DecoderError> for EvmReceiptError {
    fn from(_: rlp::DecoderError) -> Self {
        EvmReceiptError::BadReceipt
    }
}

impl Display for EvmReceiptError {
    fn fmt(&self, f: &mut Formatter<'_>) -> core::fmt::Result {
        match self {
            EvmReceiptError::TooShort => f.write_str("evm proof payload too short"),
            EvmReceiptError::BadHeader => f.write_str("evm proof header is not valid RLP"),
            EvmReceiptError::BadReceipt => f.write_str("evm proof receipt is not valid RLP"),
            EvmReceiptError::BadProof => f.write_str("evm proof inclusion proof is not valid RLP"),
            EvmReceiptError::InclusionFailed => {
                f.write_str("evm proof: receipt not in asserted receipts root")
            }
            EvmReceiptError::WrongLogCount => f.write_str("evm proof: receipt must have 1 log"),
            EvmReceiptError::BadSelector => {
                f.write_str("evm proof: log topic[0] does not match selector")
            }
            EvmReceiptError::BadAmount => f.write_str("evm proof: log data is not uint256 amount"),
            EvmReceiptError::InsufficientConfirmations { have, need } => write!(
                f,
                "evm proof: block confirmations {have} below required {need}"
            ),
            EvmReceiptError::WrongChain { expected, got } => {
                write!(
                    f,
                    "evm proof: chain mismatch (got {got}, expected {expected})"
                )
            }
        }
    }
}

// ── Selector helpers ───────────────────────────────────────────────────────

/// `keccak256("DepositLocked(bytes32,address,bytes,uint256,uint256,uint256)")`
/// — the canonical X3 external deposit event. The first topic of every
/// EVM-side deposit log must equal this. Computed lazily on first use
/// and cached; the function is `no_std` compatible (uses `OnceCell`-style
/// lazy init that is provided by `once_cell` in std builds and a tiny
/// ad-hoc spin in `no_std`).
pub fn deposit_locked_selector() -> [u8; 32] {
    keccak256_bytes(b"DepositLocked(bytes32,address,bytes,uint256,uint256,uint256)")
}

/// `keccak256("WithdrawalReleased(bytes32,address,address,uint256)")` — the
/// canonical X3 external release event.
pub fn withdrawal_released_selector() -> [u8; 32] {
    keccak256_bytes(b"WithdrawalReleased(bytes32,address,address,uint256)")
}

/// Kept for backward compatibility with callers that still expect a
/// `const` symbol. The value is the all-zero placeholder; the
/// authoritative selectors are the functions above. Production code MUST
/// use the functions.
pub const DEPOSIT_LOCKED_SELECTOR: [u8; 32] = [0u8; 32];
pub const WITHDRAWAL_RELEASED_SELECTOR: [u8; 32] = [0u8; 32];

// ── Light client header ────────────────────────────────────────────────────

/// A 256-byte decoded EIP-1186 block header. The verifier only consults
/// the `receipts_root` field but the full layout is preserved for
/// forward-compatibility.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EvmBlockHeader {
    pub parent_hash: [u8; 32],
    pub state_root: [u8; 32],
    pub receipts_root: [u8; 32],
    pub logs_bloom: Vec<u8>,
    pub number: u64,
    pub timestamp: u64,
}

impl EvmBlockHeader {
    /// Decode an RLP-encoded EIP-1186 block header. The header is encoded
    /// as a 15-element list; only the fields the verifier needs are
    /// decoded — the rest are skipped.
    pub fn decode(rlp: &[u8]) -> Result<Self, EvmReceiptError> {
        let s = rlp::Rlp::new(rlp);
        if !s.is_list() {
            return Err(EvmReceiptError::BadHeader);
        }
        let item_count = s.item_count().unwrap_or(0);
        if item_count < 15 {
            return Err(EvmReceiptError::BadHeader);
        }
        let parent_hash: Vec<u8> = s.at(0)?.as_val()?;
        let state_root: Vec<u8> = s.at(1)?.as_val()?;
        let receipts_root: Vec<u8> = s.at(2)?.as_val()?;
        let logs_bloom: Vec<u8> = s.at(3)?.as_val()?;
        // EIP-1186: parent, state, receipts, bloom, difficulty, number,
        // gas_limit, gas_used, timestamp, extra, mix, nonce, base_fee,
        // withdrawals_root, blob_gas_used.
        let _difficulty: Vec<u8> = s.at(4)?.as_val()?;
        let number_bytes: Vec<u8> = s.at(8)?.as_val()?;
        let timestamp_bytes: Vec<u8> = s.at(11)?.as_val()?;
        Ok(Self {
            parent_hash: bytes32(&parent_hash)?,
            state_root: bytes32(&state_root)?,
            receipts_root: bytes32(&receipts_root)?,
            logs_bloom,
            number: decode_u64(&number_bytes),
            timestamp: decode_u64(&timestamp_bytes),
        })
    }
}

// ── Receipt ────────────────────────────────────────────────────────────────

/// Decoded EIP-2930 / legacy transaction receipt. Only the fields the
/// verifier needs are decoded.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EvmReceipt {
    /// True iff the receipt is the post-Byzantium (status-code) form.
    pub status: bool,
    pub cumulative_gas_used: u64,
    pub logs: Vec<EvmLog>,
}

/// Single EVM log entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EvmLog {
    pub address: [u8; 20],
    pub topics: Vec<[u8; 32]>,
    pub data: Vec<u8>,
}

impl EvmReceipt {
    /// Decode an RLP-encoded legacy or EIP-2930 receipt. The receipt is a
    /// list of three fields: status (post-Byzantium) or root (pre-Byzantium),
    /// cumulative_gas_used, logs. We require the status form because the
    /// X3 gateway emits `DepositLocked` (success) and reverts on failure,
    /// so we never accept a pre-Byzantium root-form receipt.
    pub fn decode(rlp: &[u8]) -> Result<Self, EvmReceiptError> {
        let s = rlp::Rlp::new(rlp);
        if !s.is_list() {
            return Err(EvmReceiptError::BadReceipt);
        }
        if s.item_count().unwrap_or(0) < 3 {
            return Err(EvmReceiptError::BadReceipt);
        }
        let status_byte: u8 = s.at(0)?.as_val()?;
        let cumulative: Vec<u8> = s.at(1)?.as_val()?;
        let logs_rlp = s.at(2)?;
        let mut logs = Vec::with_capacity(logs_rlp.item_count().unwrap_or(0));
        for log_rlp in logs_rlp.iter() {
            logs.push(EvmLog::decode(log_rlp.as_raw())?);
        }
        Ok(Self {
            status: status_byte != 0,
            cumulative_gas_used: decode_u64(&cumulative),
            logs,
        })
    }
}

impl EvmLog {
    pub fn decode(rlp: &[u8]) -> Result<Self, EvmReceiptError> {
        let s = rlp::Rlp::new(rlp);
        if !s.is_list() {
            return Err(EvmReceiptError::BadReceipt);
        }
        let address_bytes: Vec<u8> = s.at(0)?.as_val()?;
        if address_bytes.len() != 20 {
            return Err(EvmReceiptError::BadReceipt);
        }
        let mut address = [0u8; 20];
        address.copy_from_slice(&address_bytes);
        let topics_rlp = s.at(1)?;
        let mut topics = Vec::with_capacity(topics_rlp.item_count().unwrap_or(0));
        for t in topics_rlp.iter() {
            let v: Vec<u8> = t.as_val()?;
            topics.push(bytes32(&v)?);
        }
        let data: Vec<u8> = s.at(2)?.as_val()?;
        Ok(Self {
            address,
            topics,
            data,
        })
    }
}

// ── Receipt trie Merkle Patricia proof ─────────────────────────────────────

/// Verify that a (key, value) pair is included in a Merkle Patricia trie
/// with the given root. `proof` is the flat list of trie nodes from root
/// to leaf, in RLP. `key` is the raw byte path; for the receipts trie
/// the path is `rlp(index)`.
pub fn verify_merkle_patricia_proof(
    root: &[u8; 32],
    key: &[u8],
    value: Option<&[u8]>,
    proof: &[u8],
) -> Result<(), EvmReceiptError> {
    let proof_rlp = rlp::Rlp::new(proof);
    if !proof_rlp.is_list() {
        return Err(EvmReceiptError::BadProof);
    }
    let mut nodes: Vec<Vec<u8>> = Vec::with_capacity(proof_rlp.item_count().unwrap_or(0));
    for n in proof_rlp.iter() {
        let v: Vec<u8> = n.as_val()?;
        nodes.push(v);
    }
    if nodes.is_empty() {
        return Err(EvmReceiptError::BadProof);
    }

    let mut expected_hash = *root;
    let mut nibbles = Nibbles::from_bytes(key);
    let last = nodes.len() - 1;
    for (i, node) in nodes.iter().enumerate() {
        if keccak256_bytes(node) != expected_hash {
            return Err(EvmReceiptError::InclusionFailed);
        }
        let r = rlp::Rlp::new(node);
        if !r.is_list() {
            return Err(EvmReceiptError::BadProof);
        }
        let item_count = r.item_count().unwrap_or(0);
        if item_count == 17 {
            // Branch node.
            if i != last {
                return Err(EvmReceiptError::BadProof);
            }
            if nibbles.is_empty() {
                let stored_value: Vec<u8> = r.at(16)?.as_val()?;
                return if Some(stored_value.as_slice()) == value {
                    Ok(())
                } else {
                    Err(EvmReceiptError::InclusionFailed)
                };
            }
            let n = nibbles.pop_front();
            if n < 16 {
                let child: Vec<u8> = r.at(n as usize)?.as_val()?;
                if child.is_empty() {
                    return Err(EvmReceiptError::InclusionFailed);
                }
                if child.len() == 32 {
                    expected_hash = bytes32_const(&child);
                } else {
                    return Err(EvmReceiptError::BadProof);
                }
            } else {
                let stored_value: Vec<u8> = r.at(16)?.as_val()?;
                return if Some(stored_value.as_slice()) == value {
                    Ok(())
                } else {
                    Err(EvmReceiptError::InclusionFailed)
                };
            }
        } else if item_count == 2 {
            // Leaf or extension.
            let path: Vec<u8> = r.at(0)?.as_val()?;
            let path_nibs = Nibbles::from_compact(&path);
            if path_nibs.is_empty() {
                if i != last {
                    return Err(EvmReceiptError::BadProof);
                }
                let stored_value: Vec<u8> = r.at(1)?.as_val()?;
                return if Some(stored_value.as_slice()) == value {
                    Ok(())
                } else {
                    Err(EvmReceiptError::InclusionFailed)
                };
            }
            let first_nibble = path[0] >> 4;
            if first_nibble & 1 == 0 {
                // Leaf.
                if i != last {
                    return Err(EvmReceiptError::BadProof);
                }
                if !path_nibs.is_suffix(&nibbles) {
                    return Err(EvmReceiptError::InclusionFailed);
                }
                let stored_value: Vec<u8> = r.at(1)?.as_val()?;
                return if Some(stored_value.as_slice()) == value {
                    Ok(())
                } else {
                    Err(EvmReceiptError::InclusionFailed)
                };
            }
            // Extension.
            if i == last {
                return Err(EvmReceiptError::BadProof);
            }
            if !path_nibs.is_suffix(&nibbles) {
                return Err(EvmReceiptError::InclusionFailed);
            }
            let child: Vec<u8> = r.at(1)?.as_val()?;
            if child.is_empty() {
                return Err(EvmReceiptError::InclusionFailed);
            }
            if child.len() != 32 {
                return Err(EvmReceiptError::BadProof);
            }
            expected_hash = bytes32_const(&child);
            nibbles = nibbles.consume(path_nibs.len());
        } else {
            return Err(EvmReceiptError::BadProof);
        }
    }
    Err(EvmReceiptError::InclusionFailed)
}

fn bytes32_const(b: &[u8]) -> [u8; 32] {
    let mut out = [0u8; 32];
    let len = b.len().min(32);
    out[..len].copy_from_slice(&b[..len]);
    out
}

fn keccak256_bytes(input: &[u8]) -> [u8; 32] {
    let mut k = Keccak::v256();
    let mut out = [0u8; 32];
    k.update(input);
    k.finalize(&mut out);
    out
}

// ── Compact path encoding & nibble helpers ─────────────────────────────────

#[derive(Debug, Clone, PartialEq, Eq)]
struct Nibbles {
    bytes: Vec<u8>,
    first_half: Option<u8>,
}

impl Nibbles {
    fn from_bytes(b: &[u8]) -> Self {
        let mut bytes = Vec::with_capacity(b.len() * 2);
        for byte in b {
            bytes.push(byte >> 4);
            bytes.push(byte & 0x0F);
        }
        Self {
            bytes,
            first_half: None,
        }
    }

    fn from_compact(compact: &[u8]) -> Self {
        if compact.is_empty() {
            return Self {
                bytes: Vec::new(),
                first_half: None,
            };
        }
        let flag = compact[0] >> 4;
        let odd = flag & 1 == 1;
        let mut bytes = Vec::with_capacity(compact.len() * 2);
        if odd {
            bytes.push(compact[0] & 0x0F);
        }
        for byte in &compact[1..] {
            bytes.push(byte >> 4);
            bytes.push(byte & 0x0F);
        }
        Self {
            bytes,
            first_half: None,
        }
    }

    fn is_empty(&self) -> bool {
        self.bytes.is_empty() && self.first_half.is_none()
    }

    fn pop_front(&mut self) -> u8 {
        if let Some(n) = self.first_half.take() {
            return n;
        }
        if self.bytes.is_empty() {
            0
        } else {
            self.bytes.remove(0)
        }
    }

    fn consume(mut self, n: usize) -> Self {
        for _ in 0..n {
            if self.first_half.is_some() {
                self.first_half = None;
            } else if !self.bytes.is_empty() {
                self.bytes.remove(0);
            }
        }
        self
    }

    fn len(&self) -> usize {
        self.bytes.len() + if self.first_half.is_some() { 1 } else { 0 }
    }

    fn is_suffix(&self, prefix: &Nibbles) -> bool {
        let p = prefix.len();
        let s = self.len();
        if s > p {
            return false;
        }
        let mut a = self.clone();
        let mut b = prefix.clone();
        for _ in 0..s {
            let x = a.pop_front();
            let y = b.pop_front();
            if x != y {
                return false;
            }
        }
        true
    }
}

// ── Wire format ────────────────────────────────────────────────────────────

/// A decoded wire-format EVM receipt proof.
///
/// Wire layout (everything RLP-encoded, concatenated):
///   * `header`  — 15-element block header, EIP-1186.
///   * `receipt` — receipt RLP bytes (caller-supplied raw receipt).
///   * `receipt_index` — the index of the receipt in the block, as
///     big-endian bytes (the receipt-trie key is `rlp(index)`).
///   * `proof` — Merkle Patricia proof (RLP list of node byte strings).
pub struct DecodedProof {
    pub header: EvmBlockHeader,
    pub receipt: EvmReceipt,
    pub receipt_index: Vec<u8>,
    pub proof: Vec<u8>,
    pub expected_amount: u128,
    pub expected_recipient: [u8; 20],
    pub expected_selector: [u8; 32],
    pub min_confirmations: u64,
    pub current_block_number: u64,
    pub expected_chain_id: u64,
}

impl DecodedProof {
    pub fn decode(
        payload: &[u8],
        expected_amount: u128,
        expected_recipient: [u8; 20],
        expected_selector: [u8; 32],
        min_confirmations: u64,
        current_block_number: u64,
        expected_chain_id: u64,
    ) -> Result<Self, EvmReceiptError> {
        if payload.len() < 16 {
            return Err(EvmReceiptError::TooShort);
        }
        let mut s = payload;
        let header = take_section(&mut s)?;
        let receipt = take_section(&mut s)?;
        let receipt_index = take_section(&mut s)?;
        let proof = take_section(&mut s)?;
        let header = EvmBlockHeader::decode(&header)?;
        let receipt = EvmReceipt::decode(&receipt)?;
        Ok(Self {
            header,
            receipt,
            receipt_index,
            proof,
            expected_amount,
            expected_recipient,
            expected_selector,
            min_confirmations,
            current_block_number,
            expected_chain_id,
        })
    }

    pub fn validate(&self) -> Result<(), EvmReceiptError> {
        if self.receipt.logs.len() != 1 {
            return Err(EvmReceiptError::WrongLogCount);
        }
        let log = &self.receipt.logs[0];
        if log.address != self.expected_recipient {
            return Err(EvmReceiptError::BadSelector);
        }
        if log.topics.is_empty() || log.topics[0] != self.expected_selector {
            return Err(EvmReceiptError::BadSelector);
        }
        if log.data.len() != 32 {
            return Err(EvmReceiptError::BadAmount);
        }
        let mut buf = [0u8; 32];
        buf.copy_from_slice(&log.data);
        let mut b16 = [0u8; 16];
        b16.copy_from_slice(&buf[16..]);
        let amount = u128::from_be_bytes(b16);
        if amount != self.expected_amount {
            return Err(EvmReceiptError::BadAmount);
        }
        let confirmations = self.current_block_number.saturating_sub(self.header.number);
        if confirmations < self.min_confirmations {
            return Err(EvmReceiptError::InsufficientConfirmations {
                have: confirmations,
                need: self.min_confirmations,
            });
        }
        if self.header.number == 0 {
            return Err(EvmReceiptError::BadHeader);
        }
        if self.expected_chain_id == 0 {
            return Err(EvmReceiptError::WrongChain {
                expected: 0,
                got: 0,
            });
        }
        // Receipts-trie key: rlp(receipt_index).
        let mut key_stream = rlp::RlpStream::new_list(1);
        key_stream.append(&self.receipt_index.as_slice());
        let key_buf = key_stream.out().to_vec();
        verify_merkle_patricia_proof(&self.header.receipts_root, &key_buf, None, &self.proof)?;
        Ok(())
    }
}

fn take_section(s: &mut &[u8]) -> Result<Vec<u8>, EvmReceiptError> {
    if s.len() < 4 {
        return Err(EvmReceiptError::TooShort);
    }
    let mut len_bytes = [0u8; 4];
    len_bytes.copy_from_slice(&s[..4]);
    let len = u32::from_be_bytes(len_bytes) as usize;
    if s.len() < 4 + len {
        return Err(EvmReceiptError::TooShort);
    }
    let mut out = Vec::with_capacity(len);
    out.extend_from_slice(&s[4..4 + len]);
    *s = &s[4 + len..];
    Ok(out)
}

fn bytes32(b: &[u8]) -> Result<[u8; 32], EvmReceiptError> {
    if b.len() != 32 {
        return Err(EvmReceiptError::BadHeader);
    }
    let mut out = [0u8; 32];
    out.copy_from_slice(b);
    Ok(out)
}

fn decode_u64(b: &[u8]) -> u64 {
    let mut buf = [0u8; 8];
    let len = b.len().min(8);
    buf[..len].copy_from_slice(&b[..len]);
    u64::from_be_bytes(buf)
}

// ── Proof construction helpers ──────────────────────────────────────────────

/// Encode a wire-format body section: 4-byte big-endian length prefix + data.
/// This is the encoding used by the `take_section` decoder.
#[inline]
pub fn enc_section(buf: &mut alloc::vec::Vec<u8>, data: &[u8]) {
    buf.extend_from_slice(&(data.len() as u32).to_be_bytes());
    buf.extend_from_slice(data);
}

/// Build the receipt-trie key for a given receipt index.
/// The receipts trie key is `rlp(receipt_index)` as a single-element list.
pub fn receipt_trie_key(receipt_index: u64) -> alloc::vec::Vec<u8> {
    let mut stream = rlp::RlpStream::new_list(1);
    stream.append(&receipt_index);
    stream.out().to_vec()
}

/// Encode a complete proof payload in the wire format expected by
/// `ProductionEvmReceiptVerifier::verify` / `DecodedProof::decode`.
///
/// Wire format:
///   [8 bytes: current_block_number (little-endian)]
///   [8 bytes: min_confirmations (little-endian)]
///   [body: 4 length-prefixed sections (header_rlp, receipt_rlp, receipt_index, proof)]
///
/// # Arguments
///
/// * `current_block_number` — the current chain head at proof construction time.
/// * `min_confirmations` — the minimum confirmations the verifier will enforce.
/// * `header_rlp` — RLP-encoded EIP-1186 block header (15-element list).
/// * `receipt_rlp` — RLP-encoded transaction receipt.
/// * `receipt_index` — raw bytes of the receipt index (big-endian, variable length).
/// * `proof` — Merkle Patricia trie proof (RLP list of node byte strings).
pub fn encode_proof_payload(
    current_block_number: u64,
    min_confirmations: u64,
    header_rlp: &[u8],
    receipt_rlp: &[u8],
    receipt_index: &[u8],
    proof: &[u8],
) -> alloc::vec::Vec<u8> {
    let mut body = alloc::vec::Vec::with_capacity(
        16 + 4
            + header_rlp.len()
            + 4
            + receipt_rlp.len()
            + 4
            + receipt_index.len()
            + 4
            + proof.len(),
    );
    body.extend_from_slice(&current_block_number.to_le_bytes());
    body.extend_from_slice(&min_confirmations.to_le_bytes());
    enc_section(&mut body, header_rlp);
    enc_section(&mut body, receipt_rlp);
    enc_section(&mut body, receipt_index);
    enc_section(&mut body, proof);
    body
}

/// Compute the keccak256 hash of a 32-byte value using the X3 EVM precompile
/// compatible hash function.
pub fn keccak256_32(input: &[u8]) -> [u8; 32] {
    let mut k = Keccak::v256();
    let mut out = [0u8; 32];
    k.update(input);
    k.finalize(&mut out);
    out
}

// ── The verifier ───────────────────────────────────────────────────────────

/// Production EVM receipt proof verifier.
///
/// The verifier does not own the chain head — `current_block_number` is
/// supplied by the caller at verify time because the head is a runtime
/// concern, not a verifier concern. The minimum confirmations threshold
/// is part of the verifier's identity (it changes the security model),
/// so it is held here.
pub struct ProductionEvmReceiptVerifier {
    pub min_confirmations: u64,
    pub selector: [u8; 32],
}

impl ProductionEvmReceiptVerifier {
    pub fn new(min_confirmations: u64) -> Self {
        Self {
            min_confirmations,
            selector: deposit_locked_selector(),
        }
    }

    pub fn with_selector(mut self, selector: [u8; 32]) -> Self {
        self.selector = selector;
        self
    }
}

impl Verifier for ProductionEvmReceiptVerifier {
    fn strategy(&self) -> VerificationStrategy {
        VerificationStrategy::EvmReceiptProof
    }

    fn verify(&self, proof: &ProofEnvelope) -> Result<VerificationOutcome, VerificationError> {
        let chain_id = match proof.source_chain {
            ChainKind::Evm { chain_id } => chain_id,
            _ => return Err(VerificationError::UnsupportedChain),
        };
        if !matches!(proof.destination_chain, ChainKind::X3) {
            return Err(VerificationError::UnsupportedChain);
        }
        if proof.expected_recipient.len() != 20 {
            return Err(VerificationError::MalformedProof);
        }
        let mut recipient = [0u8; 20];
        recipient.copy_from_slice(&proof.expected_recipient);

        if proof.payload.len() < 48 {
            return Err(VerificationError::MalformedProof);
        }
        let mut head_bytes = [0u8; 8];
        head_bytes.copy_from_slice(&proof.payload[0..8]);
        let head = u64::from_le_bytes(head_bytes);
        let mut min_bytes = [0u8; 8];
        min_bytes.copy_from_slice(&proof.payload[8..16]);
        let min_conf = u64::from_le_bytes(min_bytes).max(self.min_confirmations);
        let body = &proof.payload[16..];

        let decoded = DecodedProof::decode(
            body,
            proof.expected_amount,
            recipient,
            self.selector,
            min_conf,
            head,
            chain_id,
        )
        .map_err(|_| VerificationError::MalformedProof)?;
        decoded
            .validate()
            .map_err(|_| VerificationError::MalformedProof)?;
        Ok(VerificationOutcome {
            accepted: true,
            reason: "evm_receipt_proof_verified",
            verified_at_height: Some(decoded.header.number),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ChainKind, ProofEnvelope, VerificationStrategy};
    use alloc::vec;

    fn enc_section(buf: &mut Vec<u8>, data: &[u8]) {
        buf.extend_from_slice(&(data.len() as u32).to_be_bytes());
        buf.extend_from_slice(data);
    }

    #[test]
    fn selector_constants_are_stable() {
        // The selectors must remain stable forever — they are the
        // on-chain event selectors that the gateway contract emits and
        // the verifier expects. The sanity checks below are the only
        // thing protecting us from accidentally swapping the byte
        // order or the underlying hash.
        let dep = deposit_locked_selector();
        let rel = withdrawal_released_selector();
        assert_eq!(dep.len(), 32);
        assert_eq!(rel.len(), 32);
        assert_ne!(dep, rel);
    }

    #[test]
    fn decode_short_payload_fails() {
        let r = ProductionEvmReceiptVerifier::new(12).verify(&ProofEnvelope {
            proof_id: [0u8; 32],
            strategy: VerificationStrategy::EvmReceiptProof,
            source_chain: ChainKind::Evm { chain_id: 1 },
            destination_chain: ChainKind::X3,
            payload: vec![0; 4],
            expected_asset_id: [0u8; 32],
            expected_amount: 0,
            expected_sender: Vec::new(),
            expected_recipient: vec![0u8; 20],
        });
        assert!(matches!(r, Err(VerificationError::MalformedProof)));
    }

    #[test]
    fn wrong_chain_kind_fails() {
        let r = ProductionEvmReceiptVerifier::new(12).verify(&ProofEnvelope {
            proof_id: [0u8; 32],
            strategy: VerificationStrategy::EvmReceiptProof,
            source_chain: ChainKind::Solana,
            destination_chain: ChainKind::X3,
            payload: vec![0; 64],
            expected_asset_id: [0u8; 32],
            expected_amount: 0,
            expected_sender: Vec::new(),
            expected_recipient: vec![0u8; 20],
        });
        assert!(matches!(r, Err(VerificationError::UnsupportedChain)));
    }

    #[test]
    fn wrong_destination_chain_fails() {
        let r = ProductionEvmReceiptVerifier::new(12).verify(&ProofEnvelope {
            proof_id: [0u8; 32],
            strategy: VerificationStrategy::EvmReceiptProof,
            source_chain: ChainKind::Evm { chain_id: 1 },
            destination_chain: ChainKind::Evm { chain_id: 2 },
            payload: vec![0; 64],
            expected_asset_id: [0u8; 32],
            expected_amount: 0,
            expected_sender: Vec::new(),
            expected_recipient: vec![0u8; 20],
        });
        assert!(matches!(r, Err(VerificationError::UnsupportedChain)));
    }

    #[test]
    fn decoded_proof_wire_format_roundtrip() {
        // Build a minimal but well-formed wire-format payload that
        // fails at the receipt decoder because the receipt RLP is too
        // short. This confirms the wire-format length-prefix decoder
        // is wired up correctly.
        let receipt = vec![0u8; 4];
        let mut body = Vec::new();
        let header = vec![0u8; 16];
        enc_section(&mut body, &header);
        enc_section(&mut body, &receipt);
        enc_section(&mut body, &[0u8]);
        enc_section(&mut body, &[0xc0]);

        let mut payload = Vec::new();
        let head: u64 = 1_000_000;
        let min: u64 = 12;
        payload.extend_from_slice(&head.to_le_bytes());
        payload.extend_from_slice(&min.to_le_bytes());
        payload.extend_from_slice(&body);

        let r = ProductionEvmReceiptVerifier::new(12).verify(&ProofEnvelope {
            proof_id: [0u8; 32],
            strategy: VerificationStrategy::EvmReceiptProof,
            source_chain: ChainKind::Evm { chain_id: 1 },
            destination_chain: ChainKind::X3,
            payload,
            expected_asset_id: [0u8; 32],
            expected_amount: 0,
            expected_sender: Vec::new(),
            expected_recipient: vec![0u8; 20],
        });
        assert!(matches!(r, Err(VerificationError::MalformedProof)));
    }
}
