//! Production EVM receipt proof verifier.
//!
//! This module provides `ProductionEvmReceiptVerifier`, the verifier that
//! `X3-contracts/evm/contracts/X3ExternalGateway.sol` and the
//! `pallet-x3-crosschain-gateway` pallet both rely on for the
//! `X3_DEPOSIT_V1` ↔ `WithdrawalReleased` round-trip. The previous verifier
//! in this crate was a structural stub that only checked for a non-empty
//! payload — it would have accepted any random bytes as a valid proof.
//!
//! The verifier here performs the four real checks:
//!
//!   1. **Decoding.** The payload is a 16-byte header followed by a
//!      4-tuple of length-prefixed sections: `[header | receipt |
//!      receipt_index | inclusion_proof]`. Each section is decoded with
//!      the standard Ethereum RLP codec.
//!   2. **Merkle Patricia inclusion.** The receipt is verified to be
//!      included in the block whose `receipts_root` the caller asserts.
//!      The proof is the sequence of trie nodes from the receipt trie
//!      root down to the leaf, encoded as a flat RLP list of node byte
//!      strings.
//!   3. **Receipt semantics.** The decoded receipt is required to encode
//!      exactly one log whose first topic equals the configured event
//!      selector, and whose data decodes to a uint256 amount matching
//!      `expected_amount`. The log's address is bound to the caller-
//!      supplied gateway address.
//!   4. **Confirmations.** The block height and current chain head (the
//!      head is supplied at verify time because it is a runtime
//!      concern) are checked against `min_confirmations`.
//!
//! Production builds MUST register this verifier; the legacy
//! `NonEmptyPayloadVerifier` is retained for unit tests only and is
//! feature-gated behind `test-verifier` in the router.

extern crate alloc;

use alloc::boxed::Box;
use alloc::vec::Vec;
use core::fmt::{Display, Formatter};
use core::option::Option;
use core::option::Option::{None, Some};
use core::result::Result;
use core::result::Result::{Err, Ok};

use tiny_keccak::{Hasher, Keccak};

use crate::{
    ChainKind, ProofEnvelope, VerificationError, VerificationOutcome, VerificationStrategy,
    Verifier,
};

// ── Public error type ──────────────────────────────────────────────────────

/// Errors specific to EVM receipt verification. The `Verifier` trait
/// collapses these into `VerificationError::MalformedProof` (or
/// `UnsupportedChain`) so callers see a unified error surface, but the
/// variants are useful for tests and for richer on-chain event metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EvmReceiptError {
    /// Payload was too short to contain the wire header.
    TooShort,
    /// The RLP header did not parse.
    BadHeader,
    /// The RLP receipt did not parse.
    BadReceipt,
    /// The Merkle Patricia proof did not parse as a list of node byte
    /// strings.
    BadProof,
    /// The receipt was not included in the asserted receipts root.
    InclusionFailed,
    /// The header this proof is about is not one the chain has attested, so the
    /// proof is about a block of the prover's own choosing.
    UnanchoredHeader,
    /// The receipt did not contain exactly one log.
    WrongLogCount,
    /// The log's first topic did not match the expected event selector.
    BadSelector,
    /// The log data was not decodable as a single uint256 amount.
    BadAmount,
    /// The block has not accumulated enough confirmations.
    InsufficientConfirmations { have: u64, need: u64 },
    /// The receipt was generated by a chain the verifier is not bound to.
    WrongChain { expected: u64, got: u64 },
}

impl From<rlp::DecoderError> for EvmReceiptError {
    fn from(_: rlp::DecoderError) -> Self {
        EvmReceiptError::BadReceipt
    }
}

impl Display for EvmReceiptError {
    fn fmt(&self, f: &mut Formatter<'_>) -> core::fmt::Result {
        match self {
            EvmReceiptError::TooShort => f.write_str("evm proof payload too short"),
            EvmReceiptError::BadHeader => f.write_str("evm proof header is not valid RLP"),
            EvmReceiptError::BadReceipt => f.write_str("evm proof receipt is not valid RLP"),
            EvmReceiptError::BadProof => f.write_str("evm proof inclusion proof is not valid RLP"),
            EvmReceiptError::InclusionFailed => {
                f.write_str("evm proof: receipt not in asserted receipts root")
            }
            EvmReceiptError::WrongLogCount => f.write_str("evm proof: receipt must have 1 log"),
            EvmReceiptError::BadSelector => {
                f.write_str("evm proof: log topic[0] does not match selector")
            }
            EvmReceiptError::BadAmount => f.write_str("evm proof: log data is not uint256 amount"),
            EvmReceiptError::InsufficientConfirmations { have, need } => write!(
                f,
                "evm proof: block confirmations {have} below required {need}"
            ),
            EvmReceiptError::UnanchoredHeader => f.write_str(
                "evm proof: the header is not one the chain has attested",
            ),
            EvmReceiptError::WrongChain { expected, got } => {
                write!(
                    f,
                    "evm proof: chain mismatch (got {got}, expected {expected})"
                )
            }
        }
    }
}

// ── Selector helpers ───────────────────────────────────────────────────────

/// `keccak256("DepositLocked(bytes32,address,bytes,uint256,uint256,uint256)")`
/// — the canonical X3 external deposit event. The first topic of every
/// EVM-side deposit log must equal this. Computed lazily on first use
/// and cached; the function is `no_std` compatible (uses `OnceCell`-style
/// lazy init that is provided by `once_cell` in std builds and a tiny
/// ad-hoc spin in `no_std`).
pub fn deposit_locked_selector() -> [u8; 32] {
    keccak256_bytes(b"DepositLocked(bytes32,address,bytes,uint256,uint256,uint256)")
}

/// `keccak256("WithdrawalReleased(bytes32,address,address,uint256)")` — the
/// canonical X3 external release event.
pub fn withdrawal_released_selector() -> [u8; 32] {
    keccak256_bytes(b"WithdrawalReleased(bytes32,address,address,uint256)")
}

/// Kept for backward compatibility with callers that still expect a
/// `const` symbol. The value is the all-zero placeholder; the
/// authoritative selectors are the functions above. Production code MUST
/// use the functions.
pub const DEPOSIT_LOCKED_SELECTOR: [u8; 32] = [0u8; 32];
pub const WITHDRAWAL_RELEASED_SELECTOR: [u8; 32] = [0u8; 32];

// ── Light client header ────────────────────────────────────────────────────

/// A 256-byte decoded EIP-1186 block header. The verifier only consults
/// the `receipts_root` field but the full layout is preserved for
/// forward-compatibility.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EvmBlockHeader {
    pub parent_hash: [u8; 32],
    pub state_root: [u8; 32],
    pub receipts_root: [u8; 32],
    pub logs_bloom: Vec<u8>,
    pub number: u64,
    pub timestamp: u64,
}

impl EvmBlockHeader {
    /// Decode an RLP-encoded EIP-1186 block header. The header is encoded
    /// as a 15-element list; only the fields the verifier needs are
    /// decoded — the rest are skipped.
    pub fn decode(rlp: &[u8]) -> Result<Self, EvmReceiptError> {
        let s = rlp::Rlp::new(rlp);
        if !s.is_list() {
            return Err(EvmReceiptError::BadHeader);
        }
        let item_count = s.item_count().unwrap_or(0);
        if item_count < 15 {
            return Err(EvmReceiptError::BadHeader);
        }
        // The header's field order, per the yellow paper: parentHash(0),
        // sha3Uncles(1), beneficiary(2), stateRoot(3), transactionsRoot(4),
        // receiptsRoot(5), logsBloom(6), difficulty(7), number(8), gasLimit(9),
        // gasUsed(10), timestamp(11), extraData(12), mixHash(13), nonce(14), then
        // the fork additions (baseFeePerGas, withdrawalsRoot, blobGasUsed, …).
        //
        // These reads used to be 1/2/3/4 for state root, receipts root, bloom and
        // difficulty — the *abbreviated* field list this function's doc comment
        // carried, not the header's real layout. `receipts_root` was therefore the
        // `beneficiary` address, so the receipts-trie walk `validate` performs
        // could never match a genuine header: the verifier rejected every real
        // proof, and no test noticed because none of them got past decoding
        // (TICKET-064).
        let parent_hash: Vec<u8> = s.at(0)?.as_val()?;
        let state_root: Vec<u8> = s.at(3)?.as_val()?;
        let receipts_root: Vec<u8> = s.at(5)?.as_val()?;
        let logs_bloom: Vec<u8> = s.at(6)?.as_val()?;
        let number_bytes: Vec<u8> = s.at(8)?.as_val()?;
        let timestamp_bytes: Vec<u8> = s.at(11)?.as_val()?;
        Ok(Self {
            parent_hash: bytes32(&parent_hash)?,
            state_root: bytes32(&state_root)?,
            receipts_root: bytes32(&receipts_root)?,
            logs_bloom,
            number: decode_u64(&number_bytes),
            timestamp: decode_u64(&timestamp_bytes),
        })
    }
}

// ── Receipt ────────────────────────────────────────────────────────────────

/// Decoded EIP-2930 / legacy transaction receipt. Only the fields the
/// verifier needs are decoded.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EvmReceipt {
    /// True iff the receipt is the post-Byzantium (status-code) form.
    pub status: bool,
    pub cumulative_gas_used: u64,
    pub logs: Vec<EvmLog>,
}

/// Single EVM log entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EvmLog {
    pub address: [u8; 20],
    pub topics: Vec<[u8; 32]>,
    pub data: Vec<u8>,
}

impl EvmReceipt {
    /// Decode an RLP-encoded legacy or EIP-2930 receipt. The receipt is a
    /// list of three fields: status (post-Byzantium) or root (pre-Byzantium),
    /// cumulative_gas_used, logs. We require the status form because the
    /// X3 gateway emits `DepositLocked` (success) and reverts on failure,
    /// so we never accept a pre-Byzantium root-form receipt.
    pub fn decode(rlp: &[u8]) -> Result<Self, EvmReceiptError> {
        // EIP-2718: a typed receipt is `type || rlp(payload)` — `0x01` for
        // EIP-2930, `0x02` for EIP-1559, `0x03` for EIP-4844 — and the type byte
        // is part of the consensus encoding, so it is skipped here rather than
        // stripped from the bytes the caller keeps (the trie leaf commits to the
        // whole thing, type byte included). Refusing typed receipts meant this
        // verifier could only ever accept a leg whose transaction was sent by a
        // legacy signer; every wallet since 2021 emits `0x02`.
        let body = match rlp.first() {
            Some(byte) if TYPED_RECEIPT_TYPES.contains(byte) => &rlp[1..],
            _ => rlp,
        };
        let s = rlp::Rlp::new(body);
        if !s.is_list() {
            return Err(EvmReceiptError::BadReceipt);
        }
        if s.item_count().unwrap_or(0) < 3 {
            return Err(EvmReceiptError::BadReceipt);
        }
        let status_byte: u8 = s.at(0)?.as_val()?;
        let cumulative: Vec<u8> = s.at(1)?.as_val()?;
        let logs_rlp = s.at(2)?;
        let mut logs = Vec::with_capacity(logs_rlp.item_count().unwrap_or(0));
        for log_rlp in logs_rlp.iter() {
            logs.push(EvmLog::decode(log_rlp.as_raw())?);
        }
        Ok(Self {
            status: status_byte != 0,
            cumulative_gas_used: decode_u64(&cumulative),
            logs,
        })
    }
}

impl EvmLog {
    pub fn decode(rlp: &[u8]) -> Result<Self, EvmReceiptError> {
        let s = rlp::Rlp::new(rlp);
        if !s.is_list() {
            return Err(EvmReceiptError::BadReceipt);
        }
        let address_bytes: Vec<u8> = s.at(0)?.as_val()?;
        if address_bytes.len() != 20 {
            return Err(EvmReceiptError::BadReceipt);
        }
        let mut address = [0u8; 20];
        address.copy_from_slice(&address_bytes);
        let topics_rlp = s.at(1)?;
        let mut topics = Vec::with_capacity(topics_rlp.item_count().unwrap_or(0));
        for t in topics_rlp.iter() {
            let v: Vec<u8> = t.as_val()?;
            topics.push(bytes32(&v)?);
        }
        let data: Vec<u8> = s.at(2)?.as_val()?;
        Ok(Self {
            address,
            topics,
            data,
        })
    }
}

// ── Receipt trie Merkle Patricia proof ─────────────────────────────────────

/// Verify that a (key, value) pair is included in a Merkle Patricia trie
/// with the given root. `proof` is the flat list of trie nodes from root
/// to leaf, in RLP. `key` is the raw byte path; for the receipts trie
/// the path is `rlp(index)`.
pub fn verify_merkle_patricia_proof(
    root: &[u8; 32],
    key: &[u8],
    value: Option<&[u8]>,
    proof: &[u8],
) -> Result<(), EvmReceiptError> {
    let proof_rlp = rlp::Rlp::new(proof);
    if !proof_rlp.is_list() {
        return Err(EvmReceiptError::BadProof);
    }
    let mut nodes: Vec<Vec<u8>> = Vec::with_capacity(proof_rlp.item_count().unwrap_or(0));
    for n in proof_rlp.iter() {
        let v: Vec<u8> = n.as_val()?;
        nodes.push(v);
    }
    if nodes.is_empty() {
        return Err(EvmReceiptError::BadProof);
    }

    let mut expected_hash = *root;
    let mut nibbles = Nibbles::from_bytes(key);
    let last = nodes.len() - 1;
    for (i, node) in nodes.iter().enumerate() {
        if keccak256_bytes(node) != expected_hash {
            return Err(EvmReceiptError::InclusionFailed);
        }
        let r = rlp::Rlp::new(node);
        if !r.is_list() {
            return Err(EvmReceiptError::BadProof);
        }
        let item_count = r.item_count().unwrap_or(0);
        if item_count == 17 {
            // Branch node.
            //
            // A branch is a real node in the middle of the walk, not a terminal
            // one. This used to require `i == last`, which made every proof for a
            // block with more than one transaction unverifiable: the path from the
            // receipts root to a receipt is *root branch → … → leaf*, so the branch
            // was never last and every such proof came back `BadProof`. The only
            // proof the walk accepted was a single leaf at the root — a one-receipt
            // block — which is why this survived: no live path had ever fed it a
            // proof built from a real block.
            if nibbles.is_empty() {
                let stored_value: Vec<u8> = r.at(16)?.as_val()?;
                return if Some(stored_value.as_slice()) == value {
                    Ok(())
                } else {
                    Err(EvmReceiptError::InclusionFailed)
                };
            }
            let n = nibbles.pop_front();
            let child: Vec<u8> = r.at(n as usize)?.as_val()?;
            if child.is_empty() {
                return Err(EvmReceiptError::InclusionFailed);
            }
            if child.len() != 32 {
                // A child whose RLP is shorter than 32 bytes is embedded in the
                // branch rather than referenced by hash. Real receipts are far
                // larger than that, so this is refused rather than mis-walked.
                return Err(EvmReceiptError::BadProof);
            }
            expected_hash = bytes32_const(&child);
        } else if item_count == 2 {
            // Leaf or extension.
            let path: Vec<u8> = r.at(0)?.as_val()?;
            let path_nibs = Nibbles::from_compact(&path);
            if path_nibs.is_empty() {
                if i != last {
                    return Err(EvmReceiptError::BadProof);
                }
                let stored_value: Vec<u8> = r.at(1)?.as_val()?;
                return if Some(stored_value.as_slice()) == value {
                    Ok(())
                } else {
                    Err(EvmReceiptError::InclusionFailed)
                };
            }
            let first_nibble = path[0] >> 4;
            // Hex-prefix flags (yellow paper appendix C): the first nibble is
            // `2 * leaf + odd`. So the *low* bit says whether the path length is
            // odd and the second bit says leaf-vs-extension. This read `& 1`,
            // which is the odd/even bit, so a leaf whose remaining path happened
            // to be an odd number of nibbles was walked as an extension — its
            // receipt read as a child hash — and refused with `BadProof`. Keys
            // are `rlp(index)`, whose nibble length is always even, so the bug
            // only showed on leaves that sit at an odd depth: which is most
            // leaves in any block with more than one transaction.
            let is_leaf = first_nibble & 0x2 != 0;
            if is_leaf {
                // Leaf.
                if i != last {
                    return Err(EvmReceiptError::BadProof);
                }
                if !path_nibs.is_suffix(&nibbles) {
                    return Err(EvmReceiptError::InclusionFailed);
                }
                let stored_value: Vec<u8> = r.at(1)?.as_val()?;
                return if Some(stored_value.as_slice()) == value {
                    Ok(())
                } else {
                    Err(EvmReceiptError::InclusionFailed)
                };
            }
            // Extension.
            if i == last {
                return Err(EvmReceiptError::BadProof);
            }
            if !path_nibs.is_suffix(&nibbles) {
                return Err(EvmReceiptError::InclusionFailed);
            }
            let child: Vec<u8> = r.at(1)?.as_val()?;
            if child.is_empty() {
                return Err(EvmReceiptError::InclusionFailed);
            }
            if child.len() != 32 {
                return Err(EvmReceiptError::BadProof);
            }
            expected_hash = bytes32_const(&child);
            nibbles = nibbles.consume(path_nibs.len());
        } else {
            return Err(EvmReceiptError::BadProof);
        }
    }
    Err(EvmReceiptError::InclusionFailed)
}

fn bytes32_const(b: &[u8]) -> [u8; 32] {
    let mut out = [0u8; 32];
    let len = b.len().min(32);
    out[..len].copy_from_slice(&b[..len]);
    out
}

fn keccak256_bytes(input: &[u8]) -> [u8; 32] {
    let mut k = Keccak::v256();
    let mut out = [0u8; 32];
    k.update(input);
    k.finalize(&mut out);
    out
}

// ── Compact path encoding & nibble helpers ─────────────────────────────────

#[derive(Debug, Clone, PartialEq, Eq)]
struct Nibbles {
    bytes: Vec<u8>,
    first_half: Option<u8>,
}

impl Nibbles {
    fn from_bytes(b: &[u8]) -> Self {
        let mut bytes = Vec::with_capacity(b.len() * 2);
        for byte in b {
            bytes.push(byte >> 4);
            bytes.push(byte & 0x0F);
        }
        Self {
            bytes,
            first_half: None,
        }
    }

    fn from_compact(compact: &[u8]) -> Self {
        if compact.is_empty() {
            return Self {
                bytes: Vec::new(),
                first_half: None,
            };
        }
        let flag = compact[0] >> 4;
        let odd = flag & 1 == 1;
        let mut bytes = Vec::with_capacity(compact.len() * 2);
        if odd {
            bytes.push(compact[0] & 0x0F);
        }
        for byte in &compact[1..] {
            bytes.push(byte >> 4);
            bytes.push(byte & 0x0F);
        }
        Self {
            bytes,
            first_half: None,
        }
    }

    fn is_empty(&self) -> bool {
        self.bytes.is_empty() && self.first_half.is_none()
    }

    fn pop_front(&mut self) -> u8 {
        if let Some(n) = self.first_half.take() {
            return n;
        }
        if self.bytes.is_empty() {
            0
        } else {
            self.bytes.remove(0)
        }
    }

    fn consume(mut self, n: usize) -> Self {
        for _ in 0..n {
            if self.first_half.is_some() {
                self.first_half = None;
            } else if !self.bytes.is_empty() {
                self.bytes.remove(0);
            }
        }
        self
    }

    fn len(&self) -> usize {
        self.bytes.len() + if self.first_half.is_some() { 1 } else { 0 }
    }

    fn is_suffix(&self, prefix: &Nibbles) -> bool {
        let p = prefix.len();
        let s = self.len();
        if s > p {
            return false;
        }
        let mut a = self.clone();
        let mut b = prefix.clone();
        for _ in 0..s {
            let x = a.pop_front();
            let y = b.pop_front();
            if x != y {
                return false;
            }
        }
        true
    }
}

/// The EIP-2718 receipt type bytes this code understands.
///
/// A typed receipt is `type || rlp(payload)`: EIP-2930 (`0x01`), EIP-1559
/// (`0x02`), EIP-4844 (`0x03`) and EIP-7702 (`0x04`). They share the same
/// payload shape as a legacy receipt — `[status, cumulativeGasUsed, logsBloom,
/// logs]` — which is all the structural checks look at. The list is explicit
/// rather than a range so an unknown type is refused instead of walked with
/// assumptions borrowed from a different one.
pub const TYPED_RECEIPT_TYPES: [u8; 4] = [0x01, 0x02, 0x03, 0x04];

// ── Receipts-trie construction ─────────────────────────────────────────────
//
// The verifier above answers "is this receipt in the tree with this root?". This
// section builds the other side of that question: given a block's receipts, the
// trie root (to compare against the header's `receiptsRoot`) and the inclusion
// proof for one of them.
//
// It belongs in this crate because the receipts trie is a wire format, and a
// producer that disagrees with the verifier in one detail (a different
// hex-prefix flag, the key encoded as a list instead of `rlp(index)`) produces
// proofs that never verify — with no way to tell which side is wrong. Here the
// two are tested against each other, and both are tested against a real block.

/// The root of an empty receipts trie: `keccak256(rlp(""))`, which is what a
/// block with no transactions carries.
pub const EMPTY_RECEIPTS_TRIE_ROOT: [u8; 32] = [
    0x56, 0xe8, 0x1f, 0x17, 0x1b, 0xcc, 0x55, 0xa6, 0xff, 0x83, 0x45, 0xe6, 0x92, 0xc0, 0xf8, 0x6e,
    0x5b, 0x48, 0xe0, 0x1b, 0x99, 0x6c, 0xad, 0xc0, 0x01, 0x62, 0x2f, 0xb5, 0xe3, 0x63, 0xb4, 0x21,
];

enum TrieNode {
    Leaf {
        path: Vec<u8>,
        value: Vec<u8>,
    },
    Extension {
        path: Vec<u8>,
        child: Box<TrieNode>,
    },
    Branch {
        children: [Option<Box<TrieNode>>; 16],
        value: Option<Vec<u8>>,
    },
}

/// Hex-prefix encoding of a nibble path (yellow paper appendix C).
fn hex_prefix(path: &[u8], leaf: bool) -> Vec<u8> {
    let odd = path.len() % 2 == 1;
    let flag = if leaf { 0x20 } else { 0x00 };
    let mut out = Vec::with_capacity(path.len() / 2 + 1);
    if odd {
        out.push(flag | 0x10 | path[0]);
        for pair in path[1..].chunks(2) {
            out.push((pair[0] << 4) | pair[1]);
        }
    } else {
        out.push(flag);
        for pair in path.chunks(2) {
            out.push((pair[0] << 4) | pair[1]);
        }
    }
    out
}

fn nibbles(bytes: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(bytes.len() * 2);
    for byte in bytes {
        out.push(byte >> 4);
        out.push(byte & 0x0F);
    }
    out
}

fn common_prefix_len(entries: &[(Vec<u8>, Vec<u8>)]) -> usize {
    let mut len = entries[0].0.len();
    for (key, _) in &entries[1..] {
        let mut shared = 0;
        while shared < len && shared < key.len() && key[shared] == entries[0].0[shared] {
            shared += 1;
        }
        len = shared;
    }
    len
}

fn build_node(entries: &[(Vec<u8>, Vec<u8>)]) -> Option<TrieNode> {
    match entries.len() {
        0 => None,
        1 => Some(TrieNode::Leaf {
            path: entries[0].0.clone(),
            value: entries[0].1.clone(),
        }),
        _ => {
            let shared = common_prefix_len(entries);
            if shared > 0 {
                let rest: Vec<(Vec<u8>, Vec<u8>)> = entries
                    .iter()
                    .map(|(key, value)| (key[shared..].to_vec(), value.clone()))
                    .collect();
                let child = build_node(&rest)?;
                return Some(TrieNode::Extension {
                    path: entries[0].0[..shared].to_vec(),
                    child: Box::new(child),
                });
            }

            let mut children: [Option<Box<TrieNode>>; 16] =
                core::array::from_fn(|_| Option::None);
            let mut value: Option<Vec<u8>> = Option::None;
            for (key, entry_value) in entries {
                let Some(first) = key.first().copied() else {
                    value = Some(entry_value.clone());
                    continue;
                };
                let group: Vec<(Vec<u8>, Vec<u8>)> = entries
                    .iter()
                    .filter(|(other, _)| other.first().copied() == Some(first))
                    .map(|(other, item)| (other[1..].to_vec(), item.clone()))
                    .collect();
                children[first as usize] = Some(Box::new(build_node(&group)?));
            }
            Some(TrieNode::Branch { children, value })
        }
    }
}

fn encode_node(node: &TrieNode) -> Vec<u8> {
    match node {
        TrieNode::Leaf { path, value } => {
            let mut stream = rlp::RlpStream::new_list(2);
            stream.append(&hex_prefix(path, true));
            stream.append(value);
            stream.out().to_vec()
        }
        TrieNode::Extension { path, child } => {
            let encoded_child = encode_node(child);
            let mut stream = rlp::RlpStream::new_list(2);
            stream.append(&hex_prefix(path, false));
            // A child whose RLP is at least 32 bytes is referenced by its hash;
            // anything shorter is embedded. `verify_merkle_patricia_proof` accepts
            // only the hash form, which is also the only form real receipts
            // produce: every leaf carries a whole receipt.
            if encoded_child.len() >= 32 {
                stream.append(&keccak256_bytes(&encoded_child).to_vec());
            } else {
                stream.append_raw(&encoded_child, 1);
            }
            stream.out().to_vec()
        }
        TrieNode::Branch { children, value } => {
            let mut stream = rlp::RlpStream::new_list(17);
            for child in children.iter() {
                match child {
                    Option::None => {
                        stream.append_empty_data();
                    }
                    Option::Some(child) => {
                        let encoded_child = encode_node(child);
                        if encoded_child.len() >= 32 {
                            stream.append(&keccak256_bytes(&encoded_child).to_vec());
                        } else {
                            stream.append_raw(&encoded_child, 1);
                        }
                    }
                }
            }
            match value {
                Option::Some(value) => {
                    stream.append(value);
                }
                Option::None => {
                    stream.append_empty_data();
                }
            }
            stream.out().to_vec()
        }
    }
}

fn entries_for(receipts: &[Vec<u8>]) -> Vec<(Vec<u8>, Vec<u8>)> {
    receipts
        .iter()
        .enumerate()
        .map(|(index, receipt)| {
            (
                nibbles(&receipt_trie_key(index as u64)),
                receipt.clone(),
            )
        })
        .collect()
}

/// The receipts-trie root of a block's receipts, in the order the block listed
/// them.
///
/// This is the value a prover compares against the block header's
/// `receiptsRoot` before it hands a proof to anyone: if they differ, the trie was
/// built over the wrong receipts (or the encoding is wrong), and no proof
/// produced from it can verify.
pub fn receipts_trie_root(receipts: &[Vec<u8>]) -> Result<[u8; 32], EvmReceiptError> {
    if receipts.is_empty() {
        return Ok(EMPTY_RECEIPTS_TRIE_ROOT);
    }
    let entries = entries_for(receipts);
    let root = build_node(&entries).ok_or(EvmReceiptError::BadProof)?;
    Ok(keccak256_bytes(&encode_node(&root)))
}

fn collect_path_nodes(node: &TrieNode, path: &[u8], nodes: &mut Vec<Vec<u8>>) {
    nodes.push(encode_node(node));
    match node {
        TrieNode::Leaf { .. } => {}
        TrieNode::Extension { path: skip, child } => {
            let next = if path.len() >= skip.len() {
                &path[skip.len()..]
            } else {
                &[]
            };
            collect_path_nodes(child, next, nodes);
        }
        TrieNode::Branch { children, .. } => {
            if let Some(first) = path.first() {
                if let Option::Some(child) = &children[*first as usize] {
                    collect_path_nodes(child, &path[1..], nodes);
                }
            }
        }
    }
}

/// The Merkle-Patricia inclusion proof for one receipt of a block, as the flat
/// RLP list of node byte strings that [`verify_merkle_patricia_proof`] expects.
///
/// `receipt_index` is the index the block listed the receipt at: the trie key is
/// `rlp(index)`, so the proof is only meaningful together with that index.
pub fn receipts_trie_proof(
    receipts: &[Vec<u8>],
    receipt_index: usize,
) -> Result<Vec<u8>, EvmReceiptError> {
    if receipt_index >= receipts.len() {
        return Err(EvmReceiptError::BadProof);
    }
    let entries = entries_for(receipts);
    let root = build_node(&entries).ok_or(EvmReceiptError::BadProof)?;
    let mut nodes = Vec::new();
    collect_path_nodes(&root, &entries[receipt_index].0, &mut nodes);

    let mut stream = rlp::RlpStream::new_list(nodes.len());
    for node in &nodes {
        stream.append(node);
    }
    Ok(stream.out().to_vec())
}

// ── Wire format ────────────────────────────────────────────────────────────

/// A decoded wire-format EVM receipt proof.
///
/// Wire layout (everything RLP-encoded, concatenated):
///   * `header`  — 15-element block header, EIP-1186.
///   * `receipt` — receipt RLP bytes (caller-supplied raw receipt).
///   * `receipt_index` — the index of the receipt in the block, as
///     big-endian bytes (the receipt-trie key is `rlp(index)`).
///   * `proof` — Merkle Patricia proof (RLP list of node byte strings).
pub struct DecodedProof {
    pub header: EvmBlockHeader,
    pub receipt: EvmReceipt,
    /// The receipt's RLP bytes, as the wire format carried them.
    ///
    /// Kept because the inclusion walk compares the leaf's stored value against
    /// the receipt: `EvmReceipt` is the decoded form and re-encoding it is not the
    /// same string. The walk was given `None` for the value, and every successful
    /// path in `verify_merkle_patricia_proof` ends in
    /// `Some(stored_value) == value` — `Some(_) == None` is false — so the
    /// verifier rejected every proof it was ever handed (TICKET-064).
    pub receipt_rlp: Vec<u8>,
    pub receipt_index: Vec<u8>,
    pub proof: Vec<u8>,
    pub expected_amount: u128,
    pub expected_recipient: [u8; 20],
    pub expected_selector: [u8; 32],
    pub min_confirmations: u64,
    pub current_block_number: u64,
    pub expected_chain_id: u64,
}

impl DecodedProof {
    pub fn decode(
        payload: &[u8],
        expected_amount: u128,
        expected_recipient: [u8; 20],
        expected_selector: [u8; 32],
        min_confirmations: u64,
        current_block_number: u64,
        expected_chain_id: u64,
    ) -> Result<Self, EvmReceiptError> {
        if payload.len() < 16 {
            return Err(EvmReceiptError::TooShort);
        }
        let mut s = payload;
        let header = take_section(&mut s)?;
        let receipt = take_section(&mut s)?;
        let receipt_index = take_section(&mut s)?;
        let proof = take_section(&mut s)?;
        let header = EvmBlockHeader::decode(&header)?;
        let receipt_decoded = EvmReceipt::decode(&receipt)?;
        Ok(Self {
            header,
            receipt_rlp: receipt,
            receipt: receipt_decoded,
            receipt_index,
            proof,
            expected_amount,
            expected_recipient,
            expected_selector,
            min_confirmations,
            current_block_number,
            expected_chain_id,
        })
    }

    /// The receipt checks: shape, amount, and inclusion in the header's
    /// receipts trie.
    ///
    /// Confirmation depth is **not** checked here. It has to be measured from
    /// the chain's attested head, and a `DecodedProof` carries the prover's own
    /// claim of that head — see [`DecodedProof::validate_against`].
    pub fn validate(&self) -> Result<(), EvmReceiptError> {
        if self.receipt.logs.len() != 1 {
            return Err(EvmReceiptError::WrongLogCount);
        }
        let log = &self.receipt.logs[0];
        if log.address != self.expected_recipient {
            return Err(EvmReceiptError::BadSelector);
        }
        if log.topics.is_empty() || log.topics[0] != self.expected_selector {
            return Err(EvmReceiptError::BadSelector);
        }
        if log.data.len() != 32 {
            return Err(EvmReceiptError::BadAmount);
        }
        let mut buf = [0u8; 32];
        buf.copy_from_slice(&log.data);
        let mut b16 = [0u8; 16];
        b16.copy_from_slice(&buf[16..]);
        let amount = u128::from_be_bytes(b16);
        if amount != self.expected_amount {
            return Err(EvmReceiptError::BadAmount);
        }
        if self.header.number == 0 {
            return Err(EvmReceiptError::BadHeader);
        }
        if self.expected_chain_id == 0 {
            return Err(EvmReceiptError::WrongChain {
                expected: 0,
                got: 0,
            });
        }
        // Receipts-trie key: rlp(receipt_index), from the index bytes the wire
        // format carries. One key builder, so the verifier cannot drift from the
        // convention `receipt_trie_key` states (TICKET-064).
        let key_buf = rlp_index_key(self.receipt_index.as_slice());
        verify_merkle_patricia_proof(
            &self.header.receipts_root,
            &key_buf,
            Some(&self.receipt_rlp),
            &self.proof,
        )?;
        Ok(())
    }

    /// Check the proof against the header the *chain* has attested, then
    /// [`DecodedProof::validate`].
    ///
    /// The header in the payload belongs to the prover: `receipts_root` is what
    /// the walk is checked against and the head height is what the depth was
    /// measured from. Both are fields of the proof, so on their own they establish
    /// only that the proof is self-consistent — a prover builds a trie containing
    /// a receipt they control, names its root, and picks a head height that
    /// satisfies the threshold. The anchor is what makes the header evidence: the
    /// root this proof is checked against, and the head its depth is measured
    /// from, come from the chain's own store.
    pub fn validate_against(
        &self,
        anchor: EvmHeaderAnchorSource,
    ) -> Result<(), EvmReceiptError> {
        let Some(anchored) = anchor.anchored(self.header.number) else {
            return Err(EvmReceiptError::UnanchoredHeader);
        };
        if anchored.receipts_root != self.header.receipts_root {
            return Err(EvmReceiptError::UnanchoredHeader);
        }
        let Some(head) = anchor.head() else {
            return Err(EvmReceiptError::UnanchoredHeader);
        };
        if head < anchored.number {
            // An attested head that predates the header it is meant to bound
            // cannot measure the depth of anything.
            return Err(EvmReceiptError::UnanchoredHeader);
        }
        let confirmations = head.saturating_sub(self.header.number);
        if confirmations < self.min_confirmations {
            return Err(EvmReceiptError::InsufficientConfirmations {
                have: confirmations,
                need: self.min_confirmations,
            });
        }
        self.validate()
    }
}

fn take_section(s: &mut &[u8]) -> Result<Vec<u8>, EvmReceiptError> {
    if s.len() < 4 {
        return Err(EvmReceiptError::TooShort);
    }
    let mut len_bytes = [0u8; 4];
    len_bytes.copy_from_slice(&s[..4]);
    let len = u32::from_be_bytes(len_bytes) as usize;
    if s.len() < 4 + len {
        return Err(EvmReceiptError::TooShort);
    }
    let mut out = Vec::with_capacity(len);
    out.extend_from_slice(&s[4..4 + len]);
    *s = &s[4 + len..];
    Ok(out)
}

fn bytes32(b: &[u8]) -> Result<[u8; 32], EvmReceiptError> {
    if b.len() != 32 {
        return Err(EvmReceiptError::BadHeader);
    }
    let mut out = [0u8; 32];
    out.copy_from_slice(b);
    Ok(out)
}

fn decode_u64(b: &[u8]) -> u64 {
    // Big-endian and *right*-aligned: RLP trims a value's leading zeros, so a
    // short value's bytes belong at the end of the word rather than at the front.
    // Copying them to the front read the header field `100` as
    // `0x6400000000000000`, which made every real header's `number` and
    // `timestamp` absurd — and the confirmations check
    // (`current_block_number - number`) then saturated to zero, so every genuine
    // proof was rejected as insufficiently confirmed. No test noticed because none
    // of them reached this code with a decodable header (TICKET-064).
    let mut buf = [0u8; 8];
    let len = b.len().min(8);
    buf[8 - len..].copy_from_slice(&b[b.len() - len..]);
    u64::from_be_bytes(buf)
}

// ── Proof construction helpers ──────────────────────────────────────────────

/// Encode a wire-format body section: 4-byte big-endian length prefix + data.
/// This is the encoding used by the `take_section` decoder.
#[inline]
pub fn enc_section(buf: &mut alloc::vec::Vec<u8>, data: &[u8]) {
    buf.extend_from_slice(&(data.len() as u32).to_be_bytes());
    buf.extend_from_slice(data);
}

/// The receipts-trie key for a receipt index, from its big-endian bytes.
///
/// The key is `rlp(index)` — the RLP encoding of the *integer*: index 0 is the
/// single byte `0x80`, index 1 is `0x01`, index 128 is `0x81 0x80`. This function
/// used to wrap the index in a list (`rlp([index])`, `0xc1 0x80` for zero), which
/// builds the path of a *different* key: the verifier below then computed a
/// nibble path no standard prover produces, so it could not accept a genuine
/// receipt proof — and its own tests could not notice, because they built their
/// proofs with this same helper. Two facts in the repository say which convention
/// is right: the doc comment on `DecodedProof::receipt_index` ("the receipt-trie
/// key is `rlp(index)`"), and `x3-lang/vm/src/bridge.rs`, whose verifier and whose
/// fixture use the raw encoding (their key for index 1 is the single byte `0x01`)
/// — the two implementations disagreed, and this is the one that was wrong
/// (TICKET-064).
pub fn rlp_index_key(index_be_bytes: &[u8]) -> alloc::vec::Vec<u8> {
    let significant = index_be_bytes
        .iter()
        .position(|byte| *byte != 0)
        .map(|first| &index_be_bytes[first..])
        .unwrap_or(&[]);
    match significant {
        // `rlp(0)` is the empty string's encoding, `0x80`.
        [] => alloc::vec![0x80],
        // A single byte below `0x80` is its own encoding.
        [single] if *single < 0x80 => alloc::vec![*single],
        bytes => {
            let mut out = alloc::vec![0x80 + bytes.len() as u8];
            out.extend_from_slice(bytes);
            out
        }
    }
}

/// Build the receipt-trie key for a given receipt index (`rlp(index)`).
pub fn receipt_trie_key(receipt_index: u64) -> alloc::vec::Vec<u8> {
    rlp_index_key(&receipt_index.to_be_bytes())
}

/// Encode a complete proof payload in the wire format expected by
/// `ProductionEvmReceiptVerifier::verify` / `DecodedProof::decode`.
///
/// Wire format:
///   [8 bytes: current_block_number (little-endian)]
///   [8 bytes: min_confirmations (little-endian)]
///   [body: 4 length-prefixed sections (header_rlp, receipt_rlp, receipt_index, proof)]
///
/// # Arguments
///
/// * `current_block_number` — the current chain head at proof construction time.
/// * `min_confirmations` — the minimum confirmations the verifier will enforce.
/// * `header_rlp` — RLP-encoded EIP-1186 block header (15-element list).
/// * `receipt_rlp` — RLP-encoded transaction receipt.
/// * `receipt_index` — raw bytes of the receipt index (big-endian, variable length).
/// * `proof` — Merkle Patricia trie proof (RLP list of node byte strings).
pub fn encode_proof_payload(
    current_block_number: u64,
    min_confirmations: u64,
    header_rlp: &[u8],
    receipt_rlp: &[u8],
    receipt_index: &[u8],
    proof: &[u8],
) -> alloc::vec::Vec<u8> {
    let mut body = alloc::vec::Vec::with_capacity(
        16 + 4
            + header_rlp.len()
            + 4
            + receipt_rlp.len()
            + 4
            + receipt_index.len()
            + 4
            + proof.len(),
    );
    body.extend_from_slice(&current_block_number.to_le_bytes());
    body.extend_from_slice(&min_confirmations.to_le_bytes());
    enc_section(&mut body, header_rlp);
    enc_section(&mut body, receipt_rlp);
    enc_section(&mut body, receipt_index);
    enc_section(&mut body, proof);
    body
}

/// Compute the keccak256 hash of a 32-byte value using the X3 EVM precompile
/// compatible hash function.
pub fn keccak256_32(input: &[u8]) -> [u8; 32] {
    let mut k = Keccak::v256();
    let mut out = [0u8; 32];
    k.update(input);
    k.finalize(&mut out);
    out
}

// ── The verifier ───────────────────────────────────────────────────────────

/// The chain's own view of an external EVM header.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AnchoredEvmHeader {
    pub number: u64,
    /// The receipt root this header commits to — the one a receipt proof must
    /// walk to.
    pub receipts_root: [u8; 32],
    pub state_root: [u8; 32],
    pub block_hash: [u8; 32],
}

/// Where a verifier gets the header it is allowed to accept.
///
/// Implementors are the chain's own store of attested headers (the validator
/// pallet on X3, a relayer's attested view off-chain). The verifier never takes
/// a header from the proof, so this is what decides which blocks a proof may be
/// about and how deep they have to be.
pub trait EvmHeaderAnchor {
    /// The header this chain has attested for `block_number`, if it has one.
    fn anchored_header(block_number: u64) -> Option<AnchoredEvmHeader>;
    /// The chain's attested head, for measuring confirmation depth.
    fn attested_head() -> Option<u64>;
}

/// [`EvmHeaderAnchor`] as function pointers, so a verifier can hold a chain's
/// header store without a type parameter or an allocation.
#[derive(Clone, Copy)]
pub struct EvmHeaderAnchorFns {
    pub header: fn(u64) -> Option<AnchoredEvmHeader>,
    pub head: fn() -> Option<u64>,
}

impl EvmHeaderAnchorFns {
    pub fn of<A: EvmHeaderAnchor>() -> Self {
        Self {
            header: A::anchored_header,
            head: A::attested_head,
        }
    }
}

/// The source a verifier resolves its anchor from.
#[derive(Clone, Copy)]
pub enum EvmHeaderAnchorSource {
    /// A chain store, addressed by block number.
    Store(EvmHeaderAnchorFns),
    /// One header and the head that contains it, held as data — for a caller
    /// that obtained the chain's view out of band and wants this proof checked
    /// against exactly that block.
    Fixed { header: AnchoredEvmHeader, head: u64 },
}

impl EvmHeaderAnchorSource {
    fn anchored(&self, block_number: u64) -> Option<AnchoredEvmHeader> {
        match self {
            Self::Store(fns) => (fns.header)(block_number),
            Self::Fixed { header, .. } => (header.number == block_number).then_some(*header),
        }
    }

    fn head(&self) -> Option<u64> {
        match self {
            Self::Store(fns) => (fns.head)(),
            Self::Fixed { head, .. } => Some(*head),
        }
    }
}

/// A source with no attested headers. Every proof is refused — the state to be
/// in until a real header store is wired in, rather than the one where the
/// prover supplies the header.
pub struct NoEvmHeaderAnchor;

impl EvmHeaderAnchor for NoEvmHeaderAnchor {
    fn anchored_header(_block_number: u64) -> Option<AnchoredEvmHeader> {
        None
    }

    fn attested_head() -> Option<u64> {
        None
    }
}

/// Production EVM receipt proof verifier.
///
/// Holds the attestation source it verifies against. There is deliberately no
/// constructor that omits one: an EVM receipt proof is a claim that a receipt is
/// in a block's receipts trie, and the whole question is *which block*. The proof
/// carries a header, so a verifier without an anchor would be checking the claim
/// against the claimant's own number — it would verify that a receipt the prover
/// built a trie for is in that trie.
///
/// The minimum confirmations threshold is part of the verifier's identity (it
/// changes the security model), so it is held here too.
pub struct ProductionEvmReceiptVerifier {
    pub min_confirmations: u64,
    pub selector: [u8; 32],
    anchor: EvmHeaderAnchorSource,
}

impl ProductionEvmReceiptVerifier {
    /// A verifier anchored to the header store `A`.
    pub fn anchored_by<A: EvmHeaderAnchor>(min_confirmations: u64) -> Self {
        Self::with_anchor(
            min_confirmations,
            EvmHeaderAnchorSource::Store(EvmHeaderAnchorFns::of::<A>()),
        )
    }

    /// A verifier anchored to a caller-assembled source.
    pub fn with_anchor(min_confirmations: u64, anchor: EvmHeaderAnchorSource) -> Self {
        Self {
            min_confirmations,
            selector: deposit_locked_selector(),
            anchor,
        }
    }

    pub fn with_selector(mut self, selector: [u8; 32]) -> Self {
        self.selector = selector;
        self
    }
}

impl Verifier for ProductionEvmReceiptVerifier {
    fn strategy(&self) -> VerificationStrategy {
        VerificationStrategy::EvmReceiptProof
    }

    fn verify(&self, proof: &ProofEnvelope) -> Result<VerificationOutcome, VerificationError> {
        let chain_id = match proof.source_chain {
            ChainKind::Evm { chain_id } => chain_id,
            _ => return Err(VerificationError::UnsupportedChain),
        };
        if !matches!(proof.destination_chain, ChainKind::X3) {
            return Err(VerificationError::UnsupportedChain);
        }
        if proof.expected_recipient.len() != 20 {
            return Err(VerificationError::MalformedProof);
        }
        let mut recipient = [0u8; 20];
        recipient.copy_from_slice(&proof.expected_recipient);

        if proof.payload.len() < 48 {
            return Err(VerificationError::MalformedProof);
        }
        // The wire format still opens with the prover's claimed head height and
        // its own minimum. The head is read for the format's sake and *not* used
        // to decide anything: depth is measured from the attestation source. The
        // prover's minimum is taken only when it raises the bar
        // (`max(self.min_confirmations)`), never when it lowers it.
        let mut head_bytes = [0u8; 8];
        head_bytes.copy_from_slice(&proof.payload[0..8]);
        let head = u64::from_le_bytes(head_bytes);
        let mut min_bytes = [0u8; 8];
        min_bytes.copy_from_slice(&proof.payload[8..16]);
        let min_conf = u64::from_le_bytes(min_bytes).max(self.min_confirmations);
        let body = &proof.payload[16..];

        let decoded = DecodedProof::decode(
            body,
            proof.expected_amount,
            recipient,
            self.selector,
            min_conf,
            head,
            chain_id,
        )
        .map_err(|_| VerificationError::MalformedProof)?;
        decoded
            .validate_against(self.anchor)
            .map_err(|_| VerificationError::MalformedProof)?;
        Ok(VerificationOutcome {
            accepted: true,
            reason: "evm_receipt_proof_verified",
            verified_at_height: Some(decoded.header.number),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ChainKind, ProofEnvelope, VerificationStrategy};
    use alloc::vec;

    fn enc_section(buf: &mut Vec<u8>, data: &[u8]) {
        buf.extend_from_slice(&(data.len() as u32).to_be_bytes());
        buf.extend_from_slice(data);
    }

    // ── Proof builders ─────────────────────────────────────────────────────
    //
    // The positive test below builds a receipts-trie proof from the *standard*
    // convention rather than from `receipt_trie_key`: a key of `rlp(index)` and a
    // leaf node of `rlp([compact_leaf_path(nibbles(key)), receipt_rlp])`. A test
    // that used the helper on both sides would agree with the helper's bug, which
    // is how the list-wrapped key survived (TICKET-064).

    fn rlp_bytes(bytes: &[u8]) -> Vec<u8> {
        let mut stream = rlp::RlpStream::new();
        stream.append(&bytes.to_vec());
        stream.out().to_vec()
    }

    fn rlp_list(items: &[Vec<u8>]) -> Vec<u8> {
        let mut stream = rlp::RlpStream::new_list(items.len());
        for item in items {
            stream.append_raw(item, 1);
        }
        stream.out().to_vec()
    }

    /// Hex-prefix encoding of a leaf path (yellow paper appendix C).
    fn compact_leaf_path(key: &[u8]) -> Vec<u8> {
        let mut nibbles = Vec::with_capacity(key.len() * 2);
        for byte in key {
            nibbles.push(byte >> 4);
            nibbles.push(byte & 0x0F);
        }
        let mut out = Vec::new();
        if nibbles.len() % 2 == 0 {
            out.push(0x20 | (nibbles.len() / 2) as u8);
            for pair in nibbles.chunks(2) {
                out.push((pair[0] << 4) | pair[1]);
            }
        } else {
            out.push(0x30 | (nibbles.len() / 2) as u8);
            out.push(nibbles[0] << 4 | nibbles[1]);
            for pair in nibbles[2..].chunks(2) {
                out.push((pair[0] << 4) | pair[1]);
            }
        }
        out
    }

    const TRANSFER_AMOUNT: u128 = 42;

    fn deposit_log(address: [u8; 20]) -> Vec<u8> {
        // topics[0] is the selector the verifier expects, data is the amount in
        // the low 16 bytes — `DecodedProof::validate`'s shape.
        let mut data = [0u8; 32];
        data[16..].copy_from_slice(&TRANSFER_AMOUNT.to_be_bytes());
        rlp_list(&[
            rlp_bytes(&address),
            rlp_list(&[rlp_bytes(&deposit_locked_selector())]),
            rlp_bytes(&data),
        ])
    }

    fn receipt_with_one_log(address: [u8; 20]) -> Vec<u8> {
        // Post-Byzantium status form: [status, cumulative_gas_used, logs].
        rlp_list(&[
            rlp_bytes(&[0x01]),
            rlp_bytes(&[0x00]),
            rlp_list(&[deposit_log(address)]),
        ])
    }

    /// A 15-field EIP-1186 header whose `receipts_root` is the one given.
    fn header_with_receipts_root(receipts_root: [u8; 32], number: u64) -> Vec<u8> {
        let zero32 = [0u8; 32];
        let mut number_bytes = Vec::new();
        number_bytes.extend_from_slice(&number.to_be_bytes());
        while number_bytes.len() > 1 && number_bytes[0] == 0 {
            number_bytes.remove(0);
        }
        // The standard order: receiptsRoot is index 5, and the decoder reads that
        // index — a header built per the abbreviated list would verify for the
        // wrong reason (TICKET-064).
        rlp_list(&[
            rlp_bytes(&zero32),        // 0  parentHash
            rlp_bytes(&zero32),        // 1  sha3Uncles
            rlp_bytes(&zero32),        // 2  beneficiary
            rlp_bytes(&zero32),        // 3  stateRoot
            rlp_bytes(&zero32),        // 4  transactionsRoot
            rlp_bytes(&receipts_root), // 5  receiptsRoot
            rlp_bytes(&[0u8; 256]),    // 6  logsBloom
            rlp_bytes(&[0x01]),        // 7  difficulty
            rlp_bytes(&number_bytes),  // 8  number
            rlp_bytes(&[0x01]),        // 9  gasLimit
            rlp_bytes(&[0x00]),        // 10 gasUsed
            rlp_bytes(&[0x01]),        // 11 timestamp
            rlp_bytes(&[]),            // 12 extraData
            rlp_bytes(&zero32),        // 13 mixHash
            rlp_bytes(&[0u8; 8]),      // 14 nonce
        ])
    }

    /// A one-leaf receipts trie at `key`, and the proof that binds `receipt_rlp`
    /// to it, both built from the standard encoding.
    fn single_leaf_trie(key: &[u8], receipt_rlp: &[u8]) -> ([u8; 32], Vec<u8>) {
        let leaf = rlp_list(&[rlp_bytes(&compact_leaf_path(key)), rlp_bytes(receipt_rlp)]);
        let root = keccak256_bytes(&leaf);
        let proof = rlp_list(&[rlp_bytes(&leaf)]);
        (root, proof)
    }

    /// The chain's view of the header a fixture built: its receipts root at its
    /// height, with `head` as the attested head.
    fn anchor_to(
        receipts_root: [u8; 32],
        number: u64,
        head: u64,
    ) -> EvmHeaderAnchorSource {
        EvmHeaderAnchorSource::Fixed {
            header: AnchoredEvmHeader {
                number,
                receipts_root,
                state_root: [0u8; 32],
                block_hash: [0u8; 32],
            },
            head,
        }
    }

    fn anchored_verifier(
        min_confirmations: u64,
        receipts_root: [u8; 32],
        number: u64,
        head: u64,
    ) -> ProductionEvmReceiptVerifier {
        ProductionEvmReceiptVerifier::with_anchor(
            min_confirmations,
            anchor_to(receipts_root, number, head),
        )
    }

    fn envelope_for(
        header_rlp: &[u8],
        receipt_rlp: &[u8],
        receipt_index: &[u8],
        proof: &[u8],
        recipient: [u8; 20],
        current_block_number: u64,
    ) -> ProofEnvelope {
        ProofEnvelope {
            proof_id: [0u8; 32],
            strategy: VerificationStrategy::EvmReceiptProof,
            source_chain: ChainKind::Evm { chain_id: 1 },
            destination_chain: ChainKind::X3,
            payload: encode_proof_payload(
                current_block_number,
                12,
                header_rlp,
                receipt_rlp,
                receipt_index,
                proof,
            ),
            expected_asset_id: [0u8; 32],
            expected_amount: TRANSFER_AMOUNT,
            expected_sender: Vec::new(),
            expected_recipient: recipient.to_vec(),
        }
    }

    #[test]
    fn the_receipt_trie_key_is_the_rlp_of_the_index() {
        // The convention two places in this repository state: `DecodedProof`'s own
        // doc ("the receipt-trie key is `rlp(index)`") and the x3-lang VM's bridge
        // fixture (key `0x01` for index 1). The helper used to wrap the index in a
        // list, which is a different key and a different nibble path (TICKET-064).
        assert_eq!(receipt_trie_key(0), vec![0x80]);
        assert_eq!(receipt_trie_key(1), vec![0x01]);
        assert_eq!(receipt_trie_key(0x7f), vec![0x7f]);
        assert_eq!(receipt_trie_key(0x80), vec![0x81, 0x80]);
        assert_eq!(receipt_trie_key(0x0100), vec![0x82, 0x01, 0x00]);
        // Leading zeros in the index bytes do not change the key: the wire format
        // says "big-endian bytes", not "fixed width".
        assert_eq!(rlp_index_key(&[0x00, 0x00, 0x01]), vec![0x01]);
        assert_eq!(rlp_index_key(&[]), vec![0x80]);
    }

    #[test]
    fn a_proof_built_with_the_standard_key_verifies() {
        // The verifier's first positive case: every path through
        // `ProductionEvmReceiptVerifier::verify` was an assertion that it *fails*
        // (short payload, wrong chain, undecodable receipt), so the merkle walk and
        // the key convention had no test that could notice either being wrong.
        let recipient = [0x11u8; 20];
        let receipt = receipt_with_one_log(recipient);
        let key = receipt_trie_key(1);
        assert_eq!(key, vec![0x01], "index 1's key is the single byte 0x01");
        let (receipts_root, proof) = single_leaf_trie(&key, &receipt);
        let header = header_with_receipts_root(receipts_root, 100);

        let envelope = envelope_for(&header, &receipt, &[0x01], &proof, recipient, 120);
        let outcome = anchored_verifier(12, receipts_root, 100, 120)
            .verify(&envelope)
            .expect("a receipt in the trie whose root the header carries must verify");
        assert!(outcome.accepted, "{outcome:?}");
    }

    #[test]
    fn a_header_the_chain_never_attested_is_refused() {
        // The provider's own header, a receipt in a trie they built, and a
        // perfectly valid walk to *their* root. Anchored to a different root —
        // what the chain actually attested for that height — this must not verify:
        // the proof would otherwise be about a block of the prover's choosing.
        let recipient = [0x11u8; 20];
        let receipt = receipt_with_one_log(recipient);
        let key = receipt_trie_key(1);
        let (prover_root, proof) = single_leaf_trie(&key, &receipt);
        let header = header_with_receipts_root(prover_root, 100);
        let envelope = envelope_for(&header, &receipt, &[0x01], &proof, recipient, 120);

        let mut attested_root = prover_root;
        attested_root[0] ^= 0xFF;
        let anchored = ProductionEvmReceiptVerifier::with_anchor(
            12,
            EvmHeaderAnchorSource::Fixed {
                header: AnchoredEvmHeader {
                    number: 100,
                    receipts_root: attested_root,
                    state_root: [0u8; 32],
                    block_hash: [0u8; 32],
                },
                head: 120,
            },
        );
        assert!(
            anchored.verify(&envelope).is_err(),
            "a receipt in the prover's own trie is not a receipt in the chain's block"
        );
    }

    #[test]
    fn the_proof_cannot_choose_its_own_confirmation_depth() {
        // The envelope claims a head of 1,000,000. The chain's attested head is
        // 110, so the block is 10 deep and this verifier wants 12. The payload's
        // number must not be the one that decides.
        let recipient = [0x11u8; 20];
        let receipt = receipt_with_one_log(recipient);
        let key = receipt_trie_key(1);
        let (receipts_root, proof) = single_leaf_trie(&key, &receipt);
        let header = header_with_receipts_root(receipts_root, 100);
        let envelope = envelope_for(&header, &receipt, &[0x01], &proof, recipient, 1_000_000);

        let result = anchored_verifier(12, receipts_root, 100, 110).verify(&envelope);
        assert!(
            result.is_err(),
            "depth comes from the attested head, not from the proof: {result:?}"
        );

        // And at the attested head it does verify, so the refusal above is about
        // depth rather than about the anchor being wired wrong.
        assert!(anchored_verifier(12, receipts_root, 100, 120).verify(&envelope).is_ok());
    }

    #[test]
    fn a_tampered_trie_node_does_not_verify() {
        // The same proof with one byte changed: the node no longer hashes to the
        // header's receipts root, so the walk must refuse rather than continue.
        let recipient = [0x11u8; 20];
        let receipt = receipt_with_one_log(recipient);
        let key = receipt_trie_key(1);
        let (receipts_root, proof) = single_leaf_trie(&key, &receipt);
        let header = header_with_receipts_root(receipts_root, 100);

        let mut tampered = proof.clone();
        // Flip a byte inside the leaf payload rather than in the list framing.
        let last = tampered.len() - 2;
        tampered[last] ^= 0xFF;

        let envelope = envelope_for(&header, &receipt, &[0x01], &tampered, recipient, 120);
        let result = anchored_verifier(12, receipts_root, 100, 120).verify(&envelope);
        assert!(
            result.is_err(),
            "a node that does not hash to the root must not verify: {result:?}"
        );
    }

    #[test]
    fn selector_constants_are_stable() {
        // The selectors must remain stable forever — they are the
        // on-chain event selectors that the gateway contract emits and
        // the verifier expects. The sanity checks below are the only
        // thing protecting us from accidentally swapping the byte
        // order or the underlying hash.
        let dep = deposit_locked_selector();
        let rel = withdrawal_released_selector();
        assert_eq!(dep.len(), 32);
        assert_eq!(rel.len(), 32);
        assert_ne!(dep, rel);
    }

    #[test]
    fn decode_short_payload_fails() {
        let r = ProductionEvmReceiptVerifier::anchored_by::<NoEvmHeaderAnchor>(12).verify(&ProofEnvelope {
            proof_id: [0u8; 32],
            strategy: VerificationStrategy::EvmReceiptProof,
            source_chain: ChainKind::Evm { chain_id: 1 },
            destination_chain: ChainKind::X3,
            payload: vec![0; 4],
            expected_asset_id: [0u8; 32],
            expected_amount: 0,
            expected_sender: Vec::new(),
            expected_recipient: vec![0u8; 20],
        });
        assert!(matches!(r, Err(VerificationError::MalformedProof)));
    }

    // ── Producer ↔ verifier ────────────────────────────────────────────────

    /// Receipts the size of real ones: the verifier only follows hash
    /// references, which a trie of tiny fixtures would never produce.
    fn realistic_receipt(seed: u8) -> Vec<u8> {
        let mut bloom = [0u8; 256];
        bloom[seed as usize] = seed;
        rlp_list(&[
            rlp_bytes(&[0x01]),
            rlp_bytes(&[seed, 0x10, 0x00]),
            rlp_bytes(&bloom),
            rlp_list(&[deposit_log([seed; 20])]),
        ])
    }

    #[test]
    fn the_root_of_no_receipts_is_the_empty_trie_root() {
        assert_eq!(
            receipts_trie_root(&[]).expect("empty trie"),
            EMPTY_RECEIPTS_TRIE_ROOT
        );
        assert_eq!(receipts_trie_proof(&[], 0), Err(EvmReceiptError::BadProof));
    }

    #[test]
    fn the_producer_and_the_verifier_agree_on_a_one_receipt_block() {
        let receipts = vec![realistic_receipt(0x11)];
        let root = receipts_trie_root(&receipts).expect("root");
        let proof = receipts_trie_proof(&receipts, 0).expect("proof");
        assert_eq!(
            verify_merkle_patricia_proof(
                &root,
                &receipt_trie_key(0),
                Some(receipts[0].as_slice()),
                &proof
            ),
            Ok(())
        );
    }

    #[test]
    fn the_producer_and_the_verifier_agree_on_a_multi_receipt_block() {
        // Enough receipts that the index key is more than one byte and the path
        // leaves the root's first branch — a one-leaf trie proves neither.
        let receipts: Vec<Vec<u8>> = (0u8..130).map(realistic_receipt).collect();
        let root = receipts_trie_root(&receipts).expect("root");
        for index in [0usize, 1, 15, 16, 127, 128, 129] {
            let proof = receipts_trie_proof(&receipts, index).expect("proof");
            assert_eq!(
                verify_merkle_patricia_proof(
                    &root,
                    &receipt_trie_key(index as u64),
                    Some(receipts[index].as_slice()),
                    &proof
                ),
                Ok(()),
                "receipt {index} must be provable"
            );
        }
    }

    #[test]
    fn a_proof_for_one_receipt_does_not_admit_another() {
        let receipts: Vec<Vec<u8>> = (0u8..8).map(realistic_receipt).collect();
        let root = receipts_trie_root(&receipts).expect("root");
        let proof = receipts_trie_proof(&receipts, 3).expect("proof");

        // The same proof under a different key is not this receipt's proof.
        assert_eq!(
            verify_merkle_patricia_proof(
                &root,
                &receipt_trie_key(4),
                Some(receipts[3].as_slice()),
                &proof
            ),
            Err(EvmReceiptError::InclusionFailed)
        );
        // Nor does it admit a receipt the block did not contain.
        assert_eq!(
            verify_merkle_patricia_proof(
                &root,
                &receipt_trie_key(3),
                Some(realistic_receipt(0xEE).as_slice()),
                &proof
            ),
            Err(EvmReceiptError::InclusionFailed)
        );
        // And it is not a valid proof against a different root.
        let mut other_root = root;
        other_root[0] ^= 0xFF;
        assert_eq!(
            verify_merkle_patricia_proof(
                &other_root,
                &receipt_trie_key(3),
                Some(receipts[3].as_slice()),
                &proof
            ),
            Err(EvmReceiptError::InclusionFailed)
        );
    }

    #[test]
    fn an_out_of_range_index_has_no_proof() {
        let receipts = vec![realistic_receipt(0x01), realistic_receipt(0x02)];
        assert_eq!(
            receipts_trie_proof(&receipts, 2),
            Err(EvmReceiptError::BadProof)
        );
    }

    #[test]
    fn a_typed_receipt_decodes_like_a_legacy_one() {
        let address = [0xAAu8; 20];
        let legacy = receipt_with_one_log(address);
        let decoded = EvmReceipt::decode(&legacy).expect("legacy receipt");
        assert!(decoded.status);
        assert_eq!(decoded.logs.len(), 1);

        for type_byte in TYPED_RECEIPT_TYPES {
            let mut typed = vec![type_byte];
            typed.extend_from_slice(&legacy);
            let typed_decoded = EvmReceipt::decode(&typed)
                .unwrap_or_else(|e| panic!("typed receipt 0x{type_byte:02x} must decode: {e}"));
            assert_eq!(typed_decoded.status, decoded.status);
            assert_eq!(typed_decoded.cumulative_gas_used, decoded.cumulative_gas_used);
            assert_eq!(typed_decoded.logs.len(), decoded.logs.len());
            assert_eq!(typed_decoded.logs[0].address, decoded.logs[0].address);
        }
    }

    #[test]
    fn a_type_byte_without_a_receipt_body_is_refused() {
        assert_eq!(EvmReceipt::decode(&[0x02]), Err(EvmReceiptError::BadReceipt));
        // A type byte followed by something that is not an RLP list.
        assert_eq!(
            EvmReceipt::decode(&[0x02, 0x01, 0x02, 0x03]),
            Err(EvmReceiptError::BadReceipt)
        );
    }

    fn proof_nodes(proof: &[u8]) -> Vec<Vec<u8>> {
        rlp::Rlp::new(proof)
            .iter()
            .map(|node| node.as_val::<Vec<u8>>().expect("a proof node"))
            .collect()
    }

    /// The proof wire format: a list of *byte strings*, each one a node's RLP.
    /// (`rlp_list` above nests each item as a list, which is right for building
    /// nodes and wrong for building a proof.)
    fn proof_list(nodes: &[Vec<u8>]) -> Vec<u8> {
        let mut stream = rlp::RlpStream::new_list(nodes.len());
        for node in nodes {
            stream.append(node);
        }
        stream.out().to_vec()
    }

    #[test]
    fn a_truncated_proof_is_rejected() {
        // The fix for the branch walk must not turn "a branch was followed" into
        // "a branch was enough": a proof that stops at the branch names the child
        // but never shows it, so it must not verify.
        let receipts: Vec<Vec<u8>> = (0u8..4).map(realistic_receipt).collect();
        let root = receipts_trie_root(&receipts).expect("root");
        let proof = receipts_trie_proof(&receipts, 2).expect("proof");
        let nodes = proof_nodes(&proof);
        assert!(nodes.len() > 1, "this block's proof must have a branch");

        let branch_only = proof_list(&nodes[..1]);
        assert_eq!(
            verify_merkle_patricia_proof(
                &root,
                &receipt_trie_key(2),
                Some(receipts[2].as_slice()),
                &branch_only
            ),
            Err(EvmReceiptError::InclusionFailed)
        );
    }

    #[test]
    fn a_leaf_borrowed_from_another_index_is_rejected() {
        let receipts: Vec<Vec<u8>> = (0u8..4).map(realistic_receipt).collect();
        let root = receipts_trie_root(&receipts).expect("root");
        let mut nodes = proof_nodes(&receipts_trie_proof(&receipts, 1).expect("proof for 1"));
        let other = proof_nodes(&receipts_trie_proof(&receipts, 3).expect("proof for 3"));
        // Keep the path to index 1 and swap in the leaf of index 3: the branch's
        // child reference no longer hashes to the leaf that follows it.
        *nodes.last_mut().expect("a leaf") = other.last().expect("a leaf").clone();
        let spliced = proof_list(&nodes);
        assert_ne!(
            verify_merkle_patricia_proof(
                &root,
                &receipt_trie_key(1),
                Some(receipts[1].as_slice()),
                &spliced
            ),
            Ok(())
        );
    }

    #[test]
    fn wrong_chain_kind_fails() {
        let r = ProductionEvmReceiptVerifier::anchored_by::<NoEvmHeaderAnchor>(12).verify(&ProofEnvelope {
            proof_id: [0u8; 32],
            strategy: VerificationStrategy::EvmReceiptProof,
            source_chain: ChainKind::Solana,
            destination_chain: ChainKind::X3,
            payload: vec![0; 64],
            expected_asset_id: [0u8; 32],
            expected_amount: 0,
            expected_sender: Vec::new(),
            expected_recipient: vec![0u8; 20],
        });
        assert!(matches!(r, Err(VerificationError::UnsupportedChain)));
    }

    #[test]
    fn wrong_destination_chain_fails() {
        let r = ProductionEvmReceiptVerifier::anchored_by::<NoEvmHeaderAnchor>(12).verify(&ProofEnvelope {
            proof_id: [0u8; 32],
            strategy: VerificationStrategy::EvmReceiptProof,
            source_chain: ChainKind::Evm { chain_id: 1 },
            destination_chain: ChainKind::Evm { chain_id: 2 },
            payload: vec![0; 64],
            expected_asset_id: [0u8; 32],
            expected_amount: 0,
            expected_sender: Vec::new(),
            expected_recipient: vec![0u8; 20],
        });
        assert!(matches!(r, Err(VerificationError::UnsupportedChain)));
    }

    #[test]
    fn decoded_proof_wire_format_roundtrip() {
        // Build a minimal but well-formed wire-format payload that
        // fails at the receipt decoder because the receipt RLP is too
        // short. This confirms the wire-format length-prefix decoder
        // is wired up correctly.
        let receipt = vec![0u8; 4];
        let mut body = Vec::new();
        let header = vec![0u8; 16];
        enc_section(&mut body, &header);
        enc_section(&mut body, &receipt);
        enc_section(&mut body, &[0u8]);
        enc_section(&mut body, &[0xc0]);

        let mut payload = Vec::new();
        let head: u64 = 1_000_000;
        let min: u64 = 12;
        payload.extend_from_slice(&head.to_le_bytes());
        payload.extend_from_slice(&min.to_le_bytes());
        payload.extend_from_slice(&body);

        let r = ProductionEvmReceiptVerifier::anchored_by::<NoEvmHeaderAnchor>(12).verify(&ProofEnvelope {
            proof_id: [0u8; 32],
            strategy: VerificationStrategy::EvmReceiptProof,
            source_chain: ChainKind::Evm { chain_id: 1 },
            destination_chain: ChainKind::X3,
            payload,
            expected_asset_id: [0u8; 32],
            expected_amount: 0,
            expected_sender: Vec::new(),
            expected_recipient: vec![0u8; 20],
        });
        assert!(matches!(r, Err(VerificationError::MalformedProof)));
    }
}
