/**
 * Chain Registry — canonical list of all supported blockchains.
 *
 * Includes mainnets + testnets for: Ethereum family, Bitcoin, Solana,
 * Polygon, BSC, Avalanche, Near, Cosmos, Substrate, and more.
 */

import type { ChainDescriptor } from "../types";
import { GENERATED_CHAIN_REGISTRY } from "./generated";

export const CHAIN_REGISTRY: ChainDescriptor[] = [
  // ─── Ethereum ────────────────────────────────────────────────
  {
    id: "ethereum",
    name: "Ethereum Mainnet",
    family: "evm",
    network: "mainnet",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    chainId: 1,
    defaultRpcUrls: ["https://eth.llamarpc.com", "https://rpc.ankr.com/eth"],
    defaultWsUrls: ["wss://eth.llamarpc.com"],
    explorerUrl: "https://etherscan.io",
    available: true,
    avgBlockTimeSeconds: 12,
    consensus: "Proof of Stake",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "ethereum",
  },
  {
    id: "ethereum-sepolia",
    name: "Ethereum Sepolia",
    family: "evm",
    network: "testnet",
    nativeCurrency: { name: "Sepolia ETH", symbol: "ETH", decimals: 18 },
    chainId: 11155111,
    defaultRpcUrls: ["https://rpc.sepolia.org", "https://rpc.ankr.com/eth_sepolia"],
    defaultWsUrls: ["wss://sepolia.drpc.org"],
    explorerUrl: "https://sepolia.etherscan.io",
    available: true,
    avgBlockTimeSeconds: 12,
    consensus: "Proof of Stake",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "ethereum",
  },
  {
    id: "ethereum-holesky",
    name: "Ethereum Holesky",
    family: "evm",
    network: "testnet",
    nativeCurrency: { name: "Holesky ETH", symbol: "ETH", decimals: 18 },
    chainId: 17000,
    defaultRpcUrls: ["https://rpc.holesky.ethpandaops.io"],
    defaultWsUrls: [],
    explorerUrl: "https://holesky.etherscan.io",
    available: true,
    avgBlockTimeSeconds: 12,
    consensus: "Proof of Stake",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "ethereum",
  },

  // ─── Bitcoin ─────────────────────────────────────────────────
  {
    id: "bitcoin",
    name: "Bitcoin Mainnet",
    family: "bitcoin",
    network: "mainnet",
    nativeCurrency: { name: "Bitcoin", symbol: "BTC", decimals: 8 },
    chainId: "bitcoin-mainnet",
    defaultRpcUrls: ["https://blockstream.info/api"],
    defaultWsUrls: ["wss://ws.blockchain.info/inv"],
    explorerUrl: "https://blockstream.info",
    available: true,
    avgBlockTimeSeconds: 600,
    consensus: "Proof of Work",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "sha256",
    gpuAccelerated: true,
    icon: "bitcoin",
  },
  {
    id: "bitcoin-testnet",
    name: "Bitcoin Testnet3",
    family: "bitcoin",
    network: "testnet",
    nativeCurrency: { name: "Test BTC", symbol: "tBTC", decimals: 8 },
    chainId: "bitcoin-testnet3",
    defaultRpcUrls: ["https://blockstream.info/testnet/api"],
    defaultWsUrls: [],
    explorerUrl: "https://blockstream.info/testnet",
    available: true,
    avgBlockTimeSeconds: 600,
    consensus: "Proof of Work",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "sha256",
    gpuAccelerated: true,
    icon: "bitcoin",
  },
  {
    id: "bitcoin-signet",
    name: "Bitcoin Signet",
    family: "bitcoin",
    network: "testnet",
    nativeCurrency: { name: "Signet BTC", symbol: "sBTC", decimals: 8 },
    chainId: "bitcoin-signet",
    defaultRpcUrls: ["https://mempool.space/signet/api"],
    defaultWsUrls: [],
    explorerUrl: "https://mempool.space/signet",
    available: true,
    avgBlockTimeSeconds: 600,
    consensus: "Proof of Work",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "sha256",
    gpuAccelerated: true,
    icon: "bitcoin",
  },

  // ─── Solana ──────────────────────────────────────────────────
  {
    id: "solana",
    name: "Solana Mainnet",
    family: "solana",
    network: "mainnet",
    nativeCurrency: { name: "Solana", symbol: "SOL", decimals: 9 },
    chainId: "solana-mainnet-beta",
    defaultRpcUrls: ["https://api.mainnet-beta.solana.com"],
    defaultWsUrls: ["wss://api.mainnet-beta.solana.com"],
    explorerUrl: "https://solscan.io",
    available: true,
    avgBlockTimeSeconds: 0.4,
    consensus: "Proof of History + Proof of Stake",
    signatureAlgorithm: "ed25519",
    hashAlgorithm: "sha256",
    gpuAccelerated: true,
    icon: "solana",
  },
  {
    id: "solana-devnet",
    name: "Solana Devnet",
    family: "solana",
    network: "devnet",
    nativeCurrency: { name: "SOL", symbol: "SOL", decimals: 9 },
    chainId: "solana-devnet",
    defaultRpcUrls: ["https://api.devnet.solana.com"],
    defaultWsUrls: ["wss://api.devnet.solana.com"],
    explorerUrl: "https://solscan.io/?cluster=devnet",
    available: true,
    avgBlockTimeSeconds: 0.4,
    consensus: "Proof of History + Proof of Stake",
    signatureAlgorithm: "ed25519",
    hashAlgorithm: "sha256",
    gpuAccelerated: true,
    icon: "solana",
  },
  {
    id: "solana-testnet",
    name: "Solana Testnet",
    family: "solana",
    network: "testnet",
    nativeCurrency: { name: "SOL", symbol: "SOL", decimals: 9 },
    chainId: "solana-testnet",
    defaultRpcUrls: ["https://api.testnet.solana.com"],
    defaultWsUrls: ["wss://api.testnet.solana.com"],
    explorerUrl: "https://solscan.io/?cluster=testnet",
    available: true,
    avgBlockTimeSeconds: 0.4,
    consensus: "Proof of History + Proof of Stake",
    signatureAlgorithm: "ed25519",
    hashAlgorithm: "sha256",
    gpuAccelerated: true,
    icon: "solana",
  },

  // ─── Polygon ──────────────────────────────────────────────────
  {
    id: "polygon",
    name: "Polygon PoS",
    family: "evm",
    network: "mainnet",
    nativeCurrency: { name: "POL", symbol: "POL", decimals: 18 },
    chainId: 137,
    defaultRpcUrls: ["https://polygon-rpc.com", "https://rpc.ankr.com/polygon"],
    defaultWsUrls: ["wss://polygon-bor-rpc.publicnode.com"],
    explorerUrl: "https://polygonscan.com",
    available: true,
    avgBlockTimeSeconds: 2,
    consensus: "Proof of Stake",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "polygon",
  },
  {
    id: "polygon-amoy",
    name: "Polygon Amoy Testnet",
    family: "evm",
    network: "testnet",
    nativeCurrency: { name: "POL", symbol: "POL", decimals: 18 },
    chainId: 80002,
    defaultRpcUrls: ["https://rpc-amoy.polygon.technology"],
    defaultWsUrls: [],
    explorerUrl: "https://amoy.polygonscan.com",
    available: true,
    avgBlockTimeSeconds: 2,
    consensus: "Proof of Stake",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "polygon",
  },

  // ─── BSC ─────────────────────────────────────────────────────
  {
    id: "bsc",
    name: "BNB Smart Chain",
    family: "evm",
    network: "mainnet",
    nativeCurrency: { name: "BNB", symbol: "BNB", decimals: 18 },
    chainId: 56,
    defaultRpcUrls: ["https://bsc-dataseed.binance.org", "https://rpc.ankr.com/bsc"],
    defaultWsUrls: ["wss://bsc-ws-node.nariox.org"],
    explorerUrl: "https://bscscan.com",
    available: true,
    avgBlockTimeSeconds: 3,
    consensus: "Proof of Staked Authority",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "bsc",
  },
  {
    id: "bsc-testnet",
    name: "BSC Testnet",
    family: "evm",
    network: "testnet",
    nativeCurrency: { name: "tBNB", symbol: "tBNB", decimals: 18 },
    chainId: 97,
    defaultRpcUrls: ["https://data-seed-prebsc-1-s1.binance.org:8545"],
    defaultWsUrls: [],
    explorerUrl: "https://testnet.bscscan.com",
    available: true,
    avgBlockTimeSeconds: 3,
    consensus: "Proof of Staked Authority",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "bsc",
  },

  // ─── Avalanche ───────────────────────────────────────────────
  {
    id: "avalanche",
    name: "Avalanche C-Chain",
    family: "evm",
    network: "mainnet",
    nativeCurrency: { name: "Avalanche", symbol: "AVAX", decimals: 18 },
    chainId: 43114,
    defaultRpcUrls: ["https://api.avax.network/ext/bc/C/rpc", "https://rpc.ankr.com/avalanche"],
    defaultWsUrls: ["wss://api.avax.network/ext/bc/C/ws"],
    explorerUrl: "https://snowtrace.io",
    available: true,
    avgBlockTimeSeconds: 2,
    consensus: "Snowball Consensus",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "avalanche",
  },
  {
    id: "avalanche-fuji",
    name: "Avalanche Fuji Testnet",
    family: "evm",
    network: "testnet",
    nativeCurrency: { name: "AVAX", symbol: "AVAX", decimals: 18 },
    chainId: 43113,
    defaultRpcUrls: ["https://api.avax-test.network/ext/bc/C/rpc"],
    defaultWsUrls: [],
    explorerUrl: "https://testnet.snowtrace.io",
    available: true,
    avgBlockTimeSeconds: 2,
    consensus: "Snowball Consensus",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "avalanche",
  },

  // ─── Arbitrum ────────────────────────────────────────────────
  {
    id: "arbitrum",
    name: "Arbitrum One",
    family: "evm",
    network: "mainnet",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    chainId: 42161,
    defaultRpcUrls: ["https://arb1.arbitrum.io/rpc", "https://rpc.ankr.com/arbitrum"],
    defaultWsUrls: ["wss://arb1.arbitrum.io/ws"],
    explorerUrl: "https://arbiscan.io",
    available: true,
    avgBlockTimeSeconds: 0.25,
    consensus: "Optimistic Rollup",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "arbitrum",
  },
  {
    id: "arbitrum-sepolia",
    name: "Arbitrum Sepolia",
    family: "evm",
    network: "testnet",
    nativeCurrency: { name: "ETH", symbol: "ETH", decimals: 18 },
    chainId: 421614,
    defaultRpcUrls: ["https://sepolia-rollup.arbitrum.io/rpc"],
    defaultWsUrls: [],
    explorerUrl: "https://sepolia.arbiscan.io",
    available: true,
    avgBlockTimeSeconds: 0.25,
    consensus: "Optimistic Rollup",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "arbitrum",
  },

  // ─── Optimism ────────────────────────────────────────────────
  {
    id: "optimism",
    name: "Optimism",
    family: "evm",
    network: "mainnet",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    chainId: 10,
    defaultRpcUrls: ["https://mainnet.optimism.io", "https://rpc.ankr.com/optimism"],
    defaultWsUrls: ["wss://mainnet.optimism.io"],
    explorerUrl: "https://optimistic.etherscan.io",
    available: true,
    avgBlockTimeSeconds: 2,
    consensus: "Optimistic Rollup",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "optimism",
  },
  {
    id: "optimism-sepolia",
    name: "Optimism Sepolia",
    family: "evm",
    network: "testnet",
    nativeCurrency: { name: "ETH", symbol: "ETH", decimals: 18 },
    chainId: 11155420,
    defaultRpcUrls: ["https://sepolia.optimism.io"],
    defaultWsUrls: [],
    explorerUrl: "https://sepolia-optimism.etherscan.io",
    available: true,
    avgBlockTimeSeconds: 2,
    consensus: "Optimistic Rollup",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "optimism",
  },

  // ─── Base ────────────────────────────────────────────────────
  {
    id: "base",
    name: "Base",
    family: "evm",
    network: "mainnet",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    chainId: 8453,
    defaultRpcUrls: ["https://mainnet.base.org", "https://rpc.ankr.com/base"],
    defaultWsUrls: ["wss://base.publicnode.com"],
    explorerUrl: "https://basescan.org",
    available: true,
    avgBlockTimeSeconds: 2,
    consensus: "Optimistic Rollup",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "base",
  },
  {
    id: "base-sepolia",
    name: "Base Sepolia",
    family: "evm",
    network: "testnet",
    nativeCurrency: { name: "ETH", symbol: "ETH", decimals: 18 },
    chainId: 84532,
    defaultRpcUrls: ["https://sepolia.base.org"],
    defaultWsUrls: [],
    explorerUrl: "https://sepolia.basescan.org",
    available: true,
    avgBlockTimeSeconds: 2,
    consensus: "Optimistic Rollup",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "base",
  },

  // ─── Near ────────────────────────────────────────────────────
  {
    id: "near",
    name: "NEAR Mainnet",
    family: "near",
    network: "mainnet",
    nativeCurrency: { name: "NEAR", symbol: "NEAR", decimals: 24 },
    chainId: "near-mainnet",
    defaultRpcUrls: ["https://rpc.mainnet.near.org"],
    defaultWsUrls: [],
    explorerUrl: "https://nearblocks.io",
    available: true,
    avgBlockTimeSeconds: 1.2,
    consensus: "Proof of Stake (Nightshade)",
    signatureAlgorithm: "ed25519",
    hashAlgorithm: "sha256",
    gpuAccelerated: false,
    icon: "near",
  },
  {
    id: "near-testnet",
    name: "NEAR Testnet",
    family: "near",
    network: "testnet",
    nativeCurrency: { name: "NEAR", symbol: "NEAR", decimals: 24 },
    chainId: "near-testnet",
    defaultRpcUrls: ["https://rpc.testnet.near.org"],
    defaultWsUrls: [],
    explorerUrl: "https://testnet.nearblocks.io",
    available: true,
    avgBlockTimeSeconds: 1.2,
    consensus: "Proof of Stake (Nightshade)",
    signatureAlgorithm: "ed25519",
    hashAlgorithm: "sha256",
    gpuAccelerated: false,
    icon: "near",
  },

  // ─── Cosmos Hub ──────────────────────────────────────────────
  {
    id: "cosmos",
    name: "Cosmos Hub",
    family: "cosmos",
    network: "mainnet",
    nativeCurrency: { name: "ATOM", symbol: "ATOM", decimals: 6 },
    chainId: "cosmoshub-4",
    defaultRpcUrls: ["https://cosmos-rpc.publicnode.com:443"],
    defaultWsUrls: ["wss://cosmos-rpc.publicnode.com:443/websocket"],
    explorerUrl: "https://www.mintscan.io/cosmos",
    available: true,
    avgBlockTimeSeconds: 6,
    consensus: "Tendermint BFT",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "sha256",
    gpuAccelerated: true,
    icon: "cosmos",
  },
  {
    id: "osmosis",
    name: "Osmosis",
    family: "cosmos",
    network: "mainnet",
    nativeCurrency: { name: "OSMO", symbol: "OSMO", decimals: 6 },
    chainId: "osmosis-1",
    defaultRpcUrls: ["https://osmosis-rpc.publicnode.com:443"],
    defaultWsUrls: [],
    explorerUrl: "https://www.mintscan.io/osmosis",
    available: true,
    avgBlockTimeSeconds: 6,
    consensus: "Tendermint BFT",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "sha256",
    gpuAccelerated: true,
    icon: "osmosis",
  },

  // ─── Polkadot / Substrate ────────────────────────────────────
  {
    id: "polkadot",
    name: "Polkadot",
    family: "substrate",
    network: "mainnet",
    nativeCurrency: { name: "DOT", symbol: "DOT", decimals: 10 },
    chainId: "polkadot",
    defaultRpcUrls: ["https://rpc.polkadot.io"],
    defaultWsUrls: ["wss://rpc.polkadot.io"],
    explorerUrl: "https://polkadot.subscan.io",
    available: true,
    avgBlockTimeSeconds: 6,
    consensus: "NPoS (GRANDPA + BABE)",
    signatureAlgorithm: "sr25519",
    hashAlgorithm: "blake2b",
    gpuAccelerated: false,
    icon: "polkadot",
  },
  {
    id: "kusama",
    name: "Kusama",
    family: "substrate",
    network: "mainnet",
    nativeCurrency: { name: "KSM", symbol: "KSM", decimals: 12 },
    chainId: "kusama",
    defaultRpcUrls: ["https://kusama-rpc.dwellir.com"],
    defaultWsUrls: ["wss://kusama-rpc.dwellir.com"],
    explorerUrl: "https://kusama.subscan.io",
    available: true,
    avgBlockTimeSeconds: 6,
    consensus: "NPoS (GRANDPA + BABE)",
    signatureAlgorithm: "sr25519",
    hashAlgorithm: "blake2b",
    gpuAccelerated: false,
    icon: "kusama",
  },

  // ─── Fantom ──────────────────────────────────────────────────
  {
    id: "fantom",
    name: "Fantom Opera",
    family: "evm",
    network: "mainnet",
    nativeCurrency: { name: "Fantom", symbol: "FTM", decimals: 18 },
    chainId: 250,
    defaultRpcUrls: ["https://rpc.ftm.tools", "https://rpc.ankr.com/fantom"],
    defaultWsUrls: [],
    explorerUrl: "https://ftmscan.com",
    available: true,
    avgBlockTimeSeconds: 1,
    consensus: "Lachesis aBFT",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "fantom",
  },

  // ─── zkSync Era ──────────────────────────────────────────────
  {
    id: "zksync",
    name: "zkSync Era",
    family: "evm",
    network: "mainnet",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    chainId: 324,
    defaultRpcUrls: ["https://mainnet.era.zksync.io"],
    defaultWsUrls: ["wss://mainnet.era.zksync.io/ws"],
    explorerUrl: "https://explorer.zksync.io",
    available: true,
    avgBlockTimeSeconds: 1,
    consensus: "ZK Rollup",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "zksync",
  },

  // ─── Linea ───────────────────────────────────────────────────
  {
    id: "linea",
    name: "Linea",
    family: "evm",
    network: "mainnet",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    chainId: 59144,
    defaultRpcUrls: ["https://rpc.linea.build"],
    defaultWsUrls: ["wss://rpc.linea.build"],
    explorerUrl: "https://lineascan.build",
    available: true,
    avgBlockTimeSeconds: 2,
    consensus: "ZK Rollup",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "linea",
  },

  // ─── Scroll ──────────────────────────────────────────────────
  {
    id: "scroll",
    name: "Scroll",
    family: "evm",
    network: "mainnet",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    chainId: 534352,
    defaultRpcUrls: ["https://rpc.scroll.io"],
    defaultWsUrls: ["wss://rpc.scroll.io"],
    explorerUrl: "https://scrollscan.com",
    available: true,
    avgBlockTimeSeconds: 3,
    consensus: "ZK Rollup",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "scroll",
  },

  // ─── Celo ────────────────────────────────────────────────────
  {
    id: "celo",
    name: "Celo",
    family: "evm",
    network: "mainnet",
    nativeCurrency: { name: "CELO", symbol: "CELO", decimals: 18 },
    chainId: 42220,
    defaultRpcUrls: ["https://forno.celo.org"],
    defaultWsUrls: ["wss://forno.celo.org/ws"],
    explorerUrl: "https://celoscan.io",
    available: true,
    avgBlockTimeSeconds: 5,
    consensus: "Proof of Stake (PBFT)",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "celo",
  },

  // ─── Gnosis ──────────────────────────────────────────────────
  {
    id: "gnosis",
    name: "Gnosis Chain",
    family: "evm",
    network: "mainnet",
    nativeCurrency: { name: "xDAI", symbol: "xDAI", decimals: 18 },
    chainId: 100,
    defaultRpcUrls: ["https://rpc.gnosischain.com", "https://rpc.ankr.com/gnosis"],
    defaultWsUrls: ["wss://rpc.gnosischain.com/wss"],
    explorerUrl: "https://gnosisscan.io",
    available: true,
    avgBlockTimeSeconds: 5,
    consensus: "Proof of Stake (AuRa)",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "gnosis",
  },

  // ─── Moonbeam ────────────────────────────────────────────────
  {
    id: "moonbeam",
    name: "Moonbeam",
    family: "evm",
    network: "mainnet",
    nativeCurrency: { name: "GLMR", symbol: "GLMR", decimals: 18 },
    chainId: 1284,
    defaultRpcUrls: ["https://rpc.api.moonbeam.network"],
    defaultWsUrls: ["wss://wss.api.moonbeam.network"],
    explorerUrl: "https://moonbeam.moonscan.io",
    available: true,
    avgBlockTimeSeconds: 12,
    consensus: "Proof of Stake (Parachain)",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "moonbeam",
  },

  // ─── Manta ───────────────────────────────────────────────────
  {
    id: "manta",
    name: "Manta Pacific",
    family: "evm",
    network: "mainnet",
    nativeCurrency: { name: "ETH", symbol: "ETH", decimals: 18 },
    chainId: 169,
    defaultRpcUrls: ["https://pacific-rpc.manta.network/http"],
    defaultWsUrls: [],
    explorerUrl: "https://pacific-explorer.manta.network",
    available: true,
    avgBlockTimeSeconds: 2,
    consensus: "Optimistic Rollup",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "keccak256",
    gpuAccelerated: true,
    icon: "manta",
  },

  // ─── Sui ─────────────────────────────────────────────────────
  {
    id: "sui",
    name: "Sui",
    family: "other",
    network: "mainnet",
    nativeCurrency: { name: "SUI", symbol: "SUI", decimals: 9 },
    chainId: "sui-mainnet",
    defaultRpcUrls: ["https://fullnode.mainnet.sui.io:443"],
    defaultWsUrls: ["wss://fullnode.mainnet.sui.io:443"],
    explorerUrl: "https://suiscan.xyz",
    available: true,
    avgBlockTimeSeconds: 0.5,
    consensus: "Narwhal/Bullshark DAG",
    signatureAlgorithm: "ed25519",
    hashAlgorithm: "sha256",
    gpuAccelerated: false,
    icon: "sui",
  },

  // ─── Aptos ───────────────────────────────────────────────────
  {
    id: "aptos",
    name: "Aptos",
    family: "other",
    network: "mainnet",
    nativeCurrency: { name: "APT", symbol: "APT", decimals: 8 },
    chainId: "aptos-mainnet",
    defaultRpcUrls: ["https://fullnode.mainnet.aptoslabs.com/v1"],
    defaultWsUrls: [],
    explorerUrl: "https://aptoscan.com",
    available: true,
    avgBlockTimeSeconds: 1,
    consensus: "AptosBFT",
    signatureAlgorithm: "ed25519",
    hashAlgorithm: "sha256",
    gpuAccelerated: false,
    icon: "aptos",
  },

  // ─── TON ─────────────────────────────────────────────────────
  {
    id: "ton",
    name: "TON",
    family: "other",
    network: "mainnet",
    nativeCurrency: { name: "Toncoin", symbol: "TON", decimals: 9 },
    chainId: "ton-mainnet",
    defaultRpcUrls: ["https://toncenter.com/api/v2/jsonRPC"],
    defaultWsUrls: [],
    explorerUrl: "https://tonviewer.com",
    available: true,
    avgBlockTimeSeconds: 5,
    consensus: "BFT PoS",
    signatureAlgorithm: "ed25519",
    hashAlgorithm: "sha256",
    gpuAccelerated: false,
    icon: "ton",
  },

  // ─── Cardano ─────────────────────────────────────────────────
  {
    id: "cardano",
    name: "Cardano",
    family: "other",
    network: "mainnet",
    nativeCurrency: { name: "ADA", symbol: "ADA", decimals: 6 },
    chainId: "cardano-mainnet",
    defaultRpcUrls: ["https://cardano-mainnet.blockfrost.io/api/v0"],
    defaultWsUrls: [],
    explorerUrl: "https://cardanoscan.io",
    available: true,
    avgBlockTimeSeconds: 20,
    consensus: "Ouroboros PoS",
    signatureAlgorithm: "ed25519",
    hashAlgorithm: "blake2b",
    gpuAccelerated: false,
    icon: "cardano",
  },

  // ─── Tezos ───────────────────────────────────────────────────
  {
    id: "tezos",
    name: "Tezos",
    family: "other",
    network: "mainnet",
    nativeCurrency: { name: "Tez", symbol: "XTZ", decimals: 6 },
    chainId: "tezos-mainnet",
    defaultRpcUrls: ["https://mainnet.api.tez.ie"],
    defaultWsUrls: [],
    explorerUrl: "https://tzstats.com",
    available: true,
    avgBlockTimeSeconds: 15,
    consensus: "Liquid Proof of Stake",
    signatureAlgorithm: "ed25519",
    hashAlgorithm: "blake2b",
    gpuAccelerated: false,
    icon: "tezos",
  },

  // ─── Algorand ────────────────────────────────────────────────
  {
    id: "algorand",
    name: "Algorand",
    family: "other",
    network: "mainnet",
    nativeCurrency: { name: "ALGO", symbol: "ALGO", decimals: 6 },
    chainId: "algorand-mainnet",
    defaultRpcUrls: ["https://mainnet-api.algonode.cloud"],
    defaultWsUrls: [],
    explorerUrl: "https://algoexplorer.io",
    available: true,
    avgBlockTimeSeconds: 3.3,
    consensus: "Pure Proof of Stake",
    signatureAlgorithm: "ed25519",
    hashAlgorithm: "sha256",
    gpuAccelerated: false,
    icon: "algorand",
  },

  // ─── XRP Ledger ──────────────────────────────────────────────
  {
    id: "xrp",
    name: "XRP Ledger",
    family: "other",
    network: "mainnet",
    nativeCurrency: { name: "XRP", symbol: "XRP", decimals: 6 },
    chainId: "xrpl-mainnet",
    defaultRpcUrls: ["https://xrplcluster.com"],
    defaultWsUrls: ["wss://xrplcluster.com"],
    explorerUrl: "https://xrpscan.com",
    available: true,
    avgBlockTimeSeconds: 4,
    consensus: "Federated Byzantine Agreement",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "sha256",
    gpuAccelerated: false,
    icon: "xrp",
  },

  // ─── Flow ────────────────────────────────────────────────────
  {
    id: "flow",
    name: "Flow",
    family: "other",
    network: "mainnet",
    nativeCurrency: { name: "FLOW", symbol: "FLOW", decimals: 8 },
    chainId: "flow-mainnet",
    defaultRpcUrls: ["https://rest-mainnet.onflow.org"],
    defaultWsUrls: [],
    explorerUrl: "https://www.flowdiver.io",
    available: true,
    avgBlockTimeSeconds: 2.5,
    consensus: "Proof of Stake (HotStuff)",
    signatureAlgorithm: "secp256k1",
    hashAlgorithm: "sha256",
    gpuAccelerated: false,
    icon: "flow",
  },
  // Auto-generated chains (loaded from external source)
  ...GENERATED_CHAIN_REGISTRY,
];

/**
 * Get a chain descriptor by ID.
 */
export function getChain(id: string): ChainDescriptor | undefined {
  return CHAIN_REGISTRY.find((c) => c.id === id);
}

/**
 * Get all chains, optionally filtered.
 */
export function getChains(filter?: {
  family?: ChainDescriptor["family"];
  network?: ChainDescriptor["network"];
  available?: boolean;
}): ChainDescriptor[] {
  let chains = CHAIN_REGISTRY;
  if (filter?.family) chains = chains.filter((c) => c.family === filter.family);
  if (filter?.network) chains = chains.filter((c) => c.network === filter.network);
  if (filter?.available !== undefined) chains = chains.filter((c) => c.available === filter.available);
  return chains;
}

/**
 * Get unique chain families.
 */
export function getChainFamilies(): ChainDescriptor["family"][] {
  return [...new Set(CHAIN_REGISTRY.map((c) => c.family))];
}

/**
 * Count chains by family.
 */
export function chainCountByFamily(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const c of CHAIN_REGISTRY) {
    counts[c.family] = (counts[c.family] || 0) + 1;
  }
  return counts;
}
