//! Weights for pallet-x3-inventory
//!
//! Auto-generated by benchmarking. These are placeholder values until actual benchmarks are run.

use frame_support::weights::{constants::RocksDbWeight, Weight};

/// Weight functions for `pallet_x3_inventory`.
pub trait WeightInfo {
    fn create_vault() -> Weight;
    fn update_vault_bands() -> Weight;
    fn register_lane() -> Weight;
    fn freeze_lane() -> Weight;
    fn unfreeze_lane() -> Weight;
    fn reserve_inventory() -> Weight;
    fn release_inventory() -> Weight;
    fn record_pending_out() -> Weight;
    fn confirm_settlement() -> Weight;
    fn fund_vault() -> Weight;
}

/// Default implementation using placeholder weights
pub struct SubstrateWeight<T>(core::marker::PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Weight for `create_vault`
    /// - 2 reads: check vault doesn't exist, get vault state
    /// - 1 write: insert vault state
    fn create_vault() -> Weight {
        Weight::from_parts(50_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    /// Weight for `update_vault_bands`
    /// - 1 read: get vault state
    /// - 1 write: update vault state
    fn update_vault_bands() -> Weight {
        Weight::from_parts(40_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    /// Weight for `register_lane`
    /// - 2 reads: check lane doesn't exist, get lane state
    /// - 1 write: insert lane state
    fn register_lane() -> Weight {
        Weight::from_parts(55_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    /// Weight for `freeze_lane`
    /// - 1 read: get lane state
    /// - 1 write: update lane status
    fn freeze_lane() -> Weight {
        Weight::from_parts(35_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    /// Weight for `unfreeze_lane`
    /// - 1 read: get lane state
    /// - 1 write: update lane status
    fn unfreeze_lane() -> Weight {
        Weight::from_parts(35_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    /// Weight for `reserve_inventory`
    /// - 2 reads: get vault state, check balance
    /// - 2 writes: update available and reserved balance
    fn reserve_inventory() -> Weight {
        Weight::from_parts(45_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }

    /// Weight for `release_inventory`
    /// - 2 reads: get vault state, check balance
    /// - 2 writes: update reserved and available balance
    fn release_inventory() -> Weight {
        Weight::from_parts(45_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }

    /// Weight for `record_pending_out`
    /// - 2 reads: get vault state, check balance
    /// - 2 writes: update available and pending_out balance
    fn record_pending_out() -> Weight {
        Weight::from_parts(45_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }

    /// Weight for `confirm_settlement`
    /// - 2 reads: get vault state, check pending_out
    /// - 2 writes: update pending_out and settled balance
    fn confirm_settlement() -> Weight {
        Weight::from_parts(45_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }

    /// Weight for `fund_vault`
    /// - 1 read: get vault state
    /// - 1 write: update available balance
    fn fund_vault() -> Weight {
        Weight::from_parts(35_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
}
