//! Weights for pallet-svm
//!
//! Auto-generated by benchmarking. These are placeholder values until actual benchmarks are run.

use frame_support::weights::{constants::RocksDbWeight, Weight};

/// Weight functions for `pallet_svm`.
pub trait WeightInfo {
    fn create_account() -> Weight;
    fn deploy_program(bytecode_len: u32) -> Weight;
    fn upgrade_program(bytecode_len: u32) -> Weight;
    fn execute_instruction(account_count: u32) -> Weight;
    fn transfer() -> Weight;
    fn close_account() -> Weight;
    fn allocate() -> Weight;
    fn assign() -> Weight;
    fn fund_account() -> Weight;
    fn freeze_program() -> Weight;
}

/// Default implementation using placeholder weights
pub struct SubstrateWeight<T>(core::marker::PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Weight for `create_account`
    /// - 2 reads: check account doesn't exist, get current slot
    /// - 3 writes: account info, account data, total lamports
    fn create_account() -> Weight {
        Weight::from_parts(50_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(3))
    }

    /// Weight for `deploy_program`
    /// - Scales with bytecode length
    /// - 2 reads: check program doesn't exist, get current slot
    /// - 4 writes: program info, program data, account info, total lamports
    fn deploy_program(bytecode_len: u32) -> Weight {
        Weight::from_parts(100_000_000, 0)
            .saturating_add(Weight::from_parts(1_000 * bytecode_len as u64, 0))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(4))
    }

    /// Weight for `upgrade_program`
    /// - Scales with bytecode length
    /// - 2 reads: program info, account info
    /// - 3 writes: program info, program data, account info
    fn upgrade_program(bytecode_len: u32) -> Weight {
        Weight::from_parts(80_000_000, 0)
            .saturating_add(Weight::from_parts(1_000 * bytecode_len as u64, 0))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(3))
    }

    /// Weight for `execute_instruction`
    /// - Heavy operation: reads program, all accounts, executes BPF
    /// - Variable reads based on account count
    /// - Variable writes for modified accounts
    fn execute_instruction(account_count: u32) -> Weight {
        let base_weight: u64 = 500_000_000;
        let per_account_reads = 20_000_000; // ~2 reads per account (info + data)
        let per_account_writes = 10_000_000; // ~1 write per writable account

        Weight::from_parts(
            base_weight
                .saturating_add((account_count as u64).saturating_mul(per_account_reads))
                .saturating_add((account_count as u64).saturating_mul(per_account_writes) / 2),
            0,
        )
        .saturating_add(RocksDbWeight::get().reads(5)) // base reads: program info, bytecode, etc.
        .saturating_add(RocksDbWeight::get().writes(2))
    }

    /// Weight for `transfer`
    /// - 2 reads: source and destination accounts
    /// - 2 writes: source and destination accounts (or 1 read + 2 writes if creating dest)
    fn transfer() -> Weight {
        Weight::from_parts(40_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }

    /// Weight for `close_account`
    /// - 2 reads: account to close, recipient account
    /// - 3 writes: remove account, remove data, update recipient
    fn close_account() -> Weight {
        Weight::from_parts(45_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(3))
    }

    /// Weight for `allocate`
    /// - 1 read: account info
    /// - 2 writes: account info, account data
    fn allocate() -> Weight {
        Weight::from_parts(35_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(2))
    }

    /// Weight for `assign`
    /// - 1 read: account info
    /// - 1 write: account info
    fn assign() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    /// Weight for `fund_account`
    /// - 2 reads: substrate account balance, SVM account
    /// - 3 writes: substrate balance, SVM account, total lamports
    fn fund_account() -> Weight {
        Weight::from_parts(55_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(3))
    }

    /// Weight for `freeze_program`
    /// - 1 read: program info
    /// - 1 write: program info
    fn freeze_program() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
}

/// Unit implementation for testing
impl WeightInfo for () {
    fn create_account() -> Weight {
        Weight::from_parts(1, 0)
    }

    fn deploy_program(_bytecode_len: u32) -> Weight {
        Weight::from_parts(1, 0)
    }

    fn upgrade_program(_bytecode_len: u32) -> Weight {
        Weight::from_parts(1, 0)
    }

    fn execute_instruction(_account_count: u32) -> Weight {
        Weight::from_parts(1, 0)
    }

    fn transfer() -> Weight {
        Weight::from_parts(1, 0)
    }

    fn close_account() -> Weight {
        Weight::from_parts(1, 0)
    }

    fn allocate() -> Weight {
        Weight::from_parts(1, 0)
    }

    fn assign() -> Weight {
        Weight::from_parts(1, 0)
    }

    fn fund_account() -> Weight {
        Weight::from_parts(1, 0)
    }

    fn freeze_program() -> Weight {
        Weight::from_parts(1, 0)
    }
}
