apiVersion: v2
name: explorer
description: "X3 Chain Block Explorer (Helm chart)"
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - explorer
  - x3-chain
maintainers:
  - name: x3-chain
    email: devops@x3-chain.io
