//! X3 Contract Templates for Voice-to-X3

use std::collections::HashMap;

/// Pre-built X3 contract templates
pub struct Templates;

impl Templates {
    /// Get ERC20 token template
    pub fn token(
        name: &str,
        symbol: &str,
        decimals: u8,
        total_supply: u128,
        mintable: bool,
        burnable: bool,
    ) -> String {
        let mut code = format!(
            r#"// X3 Token Contract: {name}
// Auto-generated by Voice-to-X3

contract {name} {{
    // Storage
    storage {{
        name: string = "{name}";
        symbol: string = "{symbol}";
        decimals: u8 = {decimals};
        total_supply: u256 = {total_supply};
        balances: map<address, u256>;
        allowances: map<address, map<address, u256>>;
        owner: address;
    }}

    // Events
    event Transfer {{
        from: address indexed;
        to: address indexed;
        amount: u256;
    }}

    event Approval {{
        owner: address indexed;
        spender: address indexed;
        amount: u256;
    }}

    // Constructor
    fn init(owner: address) {{
        self.owner = owner;
        self.balances[owner] = self.total_supply;
        emit Transfer {{ from: address(0), to: owner, amount: self.total_supply }};
    }}

    // View functions
    fn name() -> string {{
        return self.name;
    }}

    fn symbol() -> string {{
        return self.symbol;
    }}

    fn decimals() -> u8 {{
        return self.decimals;
    }}

    fn total_supply() -> u256 {{
        return self.total_supply;
    }}

    fn balance_of(account: address) -> u256 {{
        return self.balances[account];
    }}

    fn allowance(owner: address, spender: address) -> u256 {{
        return self.allowances[owner][spender];
    }}

    // Transfer functions
    fn transfer(to: address, amount: u256) -> bool {{
        require(self.balances[msg.sender] >= amount, "Insufficient balance");
        require(to != address(0), "Cannot transfer to zero address");
        
        self.balances[msg.sender] -= amount;
        self.balances[to] += amount;
        
        emit Transfer {{ from: msg.sender, to: to, amount: amount }};
        return true;
    }}

    fn approve(spender: address, amount: u256) -> bool {{
        self.allowances[msg.sender][spender] = amount;
        emit Approval {{ owner: msg.sender, spender: spender, amount: amount }};
        return true;
    }}

    fn transfer_from(from: address, to: address, amount: u256) -> bool {{
        require(self.balances[from] >= amount, "Insufficient balance");
        require(self.allowances[from][msg.sender] >= amount, "Insufficient allowance");
        require(to != address(0), "Cannot transfer to zero address");
        
        self.balances[from] -= amount;
        self.balances[to] += amount;
        self.allowances[from][msg.sender] -= amount;
        
        emit Transfer {{ from: from, to: to, amount: amount }};
        return true;
    }}
"#
        );

        // Add mint function if mintable
        if mintable {
            code.push_str(
                r#"
    // Mint new tokens (owner only)
    fn mint(to: address, amount: u256) {{
        require(msg.sender == self.owner, "Only owner can mint");
        require(to != address(0), "Cannot mint to zero address");
        
        self.total_supply += amount;
        self.balances[to] += amount;
        
        emit Transfer {{ from: address(0), to: to, amount: amount }};
    }}
"#,
            );
        }

        // Add burn function if burnable
        if burnable {
            code.push_str(
                r#"
    // Burn tokens
    fn burn(amount: u256) {{
        require(self.balances[msg.sender] >= amount, "Insufficient balance to burn");
        
        self.balances[msg.sender] -= amount;
        self.total_supply -= amount;
        
        emit Transfer {{ from: msg.sender, to: address(0), amount: amount }};
    }}
"#,
            );
        }

        code.push_str("}\n");
        code
    }

    /// Get NFT collection template
    pub fn nft(name: &str, symbol: &str, max_supply: u64, royalty_percent: u8) -> String {
        format!(
            r#"// X3 NFT Contract: {name}
// Auto-generated by Voice-to-X3

contract {name} {{
    // Storage
    storage {{
        name: string = "{name}";
        symbol: string = "{symbol}";
        max_supply: u64 = {max_supply};
        total_minted: u64 = 0;
        royalty_percent: u8 = {royalty_percent};
        base_uri: string;
        owner: address;
        owners: map<u256, address>;
        balances: map<address, u256>;
        token_uris: map<u256, string>;
        approvals: map<u256, address>;
        operator_approvals: map<address, map<address, bool>>;
    }}

    // Events
    event Transfer {{
        from: address indexed;
        to: address indexed;
        token_id: u256 indexed;
    }}

    event Approval {{
        owner: address indexed;
        approved: address indexed;
        token_id: u256 indexed;
    }}

    event ApprovalForAll {{
        owner: address indexed;
        operator: address indexed;
        approved: bool;
    }}

    // Constructor
    fn init(owner: address, base_uri: string) {{
        self.owner = owner;
        self.base_uri = base_uri;
    }}

    // View functions
    fn name() -> string {{
        return self.name;
    }}

    fn symbol() -> string {{
        return self.symbol;
    }}

    fn total_supply() -> u64 {{
        return self.total_minted;
    }}

    fn balance_of(account: address) -> u256 {{
        return self.balances[account];
    }}

    fn owner_of(token_id: u256) -> address {{
        let owner = self.owners[token_id];
        require(owner != address(0), "Token does not exist");
        return owner;
    }}

    fn token_uri(token_id: u256) -> string {{
        require(self.owners[token_id] != address(0), "Token does not exist");
        if self.token_uris[token_id] != "" {{
            return self.token_uris[token_id];
        }}
        return concat(self.base_uri, to_string(token_id));
    }}

    fn royalty_info(token_id: u256, sale_price: u256) -> (address, u256) {{
        let royalty = (sale_price * u256(self.royalty_percent)) / 100;
        return (self.owner, royalty);
    }}

    // Mint function
    fn mint(to: address, token_uri: string) -> u256 {{
        require(msg.sender == self.owner, "Only owner can mint");
        require(self.total_minted < self.max_supply, "Max supply reached");
        require(to != address(0), "Cannot mint to zero address");
        
        self.total_minted += 1;
        let token_id = u256(self.total_minted);
        
        self.owners[token_id] = to;
        self.balances[to] += 1;
        self.token_uris[token_id] = token_uri;
        
        emit Transfer {{ from: address(0), to: to, token_id: token_id }};
        return token_id;
    }}

    // Transfer function
    fn transfer_from(from: address, to: address, token_id: u256) {{
        require(self._is_approved_or_owner(msg.sender, token_id), "Not authorized");
        require(to != address(0), "Cannot transfer to zero address");
        
        self._clear_approval(token_id);
        
        self.balances[from] -= 1;
        self.balances[to] += 1;
        self.owners[token_id] = to;
        
        emit Transfer {{ from: from, to: to, token_id: token_id }};
    }}

    // Approval functions
    fn approve(to: address, token_id: u256) {{
        let owner = self.owners[token_id];
        require(msg.sender == owner || self.operator_approvals[owner][msg.sender], "Not authorized");
        
        self.approvals[token_id] = to;
        emit Approval {{ owner: owner, approved: to, token_id: token_id }};
    }}

    fn set_approval_for_all(operator: address, approved: bool) {{
        self.operator_approvals[msg.sender][operator] = approved;
        emit ApprovalForAll {{ owner: msg.sender, operator: operator, approved: approved }};
    }}

    // Internal functions
    fn _is_approved_or_owner(spender: address, token_id: u256) -> bool {{
        let owner = self.owners[token_id];
        return spender == owner 
            || self.approvals[token_id] == spender 
            || self.operator_approvals[owner][spender];
    }}

    fn _clear_approval(token_id: u256) {{
        self.approvals[token_id] = address(0);
    }}
}}
"#
        )
    }

    /// Get DEX/AMM template
    pub fn dex(name: &str, fee_basis_points: u16) -> String {
        format!(
            r#"// X3 DEX Contract: {name}
// Auto-generated by Voice-to-X3

contract {name} {{
    // Storage
    storage {{
        fee_basis_points: u16 = {fee_basis_points}; // 30 = 0.3%
        owner: address;
        total_liquidity: map<bytes32, u256>; // pool_id -> liquidity
        reserves: map<bytes32, (u256, u256)>; // pool_id -> (reserve0, reserve1)
        liquidity_positions: map<bytes32, map<address, u256>>; // pool_id -> user -> liquidity
        tokens: map<bytes32, (address, address)>; // pool_id -> (token0, token1)
    }}

    // Events
    event PoolCreated {{
        pool_id: bytes32 indexed;
        token0: address indexed;
        token1: address indexed;
    }}

    event LiquidityAdded {{
        pool_id: bytes32 indexed;
        provider: address indexed;
        amount0: u256;
        amount1: u256;
        liquidity: u256;
    }}

    event LiquidityRemoved {{
        pool_id: bytes32 indexed;
        provider: address indexed;
        amount0: u256;
        amount1: u256;
        liquidity: u256;
    }}

    event Swap {{
        pool_id: bytes32 indexed;
        trader: address indexed;
        amount_in: u256;
        amount_out: u256;
        token_in: address;
        token_out: address;
    }}

    // Constructor
    fn init(owner: address) {{
        self.owner = owner;
    }}

    // Create a new liquidity pool
    fn create_pool(token0: address, token1: address) -> bytes32 {{
        require(token0 != token1, "Identical tokens");
        require(token0 != address(0) && token1 != address(0), "Zero address");
        
        // Ensure canonical ordering
        let (t0, t1) = if token0 < token1 {{ (token0, token1) }} else {{ (token1, token0) }};
        
        let pool_id = keccak256(abi.encode(t0, t1));
        require(self.tokens[pool_id] == (address(0), address(0)), "Pool exists");
        
        self.tokens[pool_id] = (t0, t1);
        self.reserves[pool_id] = (0, 0);
        self.total_liquidity[pool_id] = 0;
        
        emit PoolCreated {{ pool_id: pool_id, token0: t0, token1: t1 }};
        return pool_id;
    }}

    // Add liquidity to pool
    fn add_liquidity(pool_id: bytes32, amount0: u256, amount1: u256, min_liquidity: u256) -> u256 {{
        let (token0, token1) = self.tokens[pool_id];
        require(token0 != address(0), "Pool does not exist");
        
        // Transfer tokens from user
        ERC20(token0).transfer_from(msg.sender, address(this), amount0);
        ERC20(token1).transfer_from(msg.sender, address(this), amount1);
        
        let (reserve0, reserve1) = self.reserves[pool_id];
        let total_liq = self.total_liquidity[pool_id];
        
        let liquidity: u256;
        if total_liq == 0 {{
            // Initial liquidity
            liquidity = sqrt(amount0 * amount1);
        }} else {{
            // Proportional liquidity
            let liq0 = (amount0 * total_liq) / reserve0;
            let liq1 = (amount1 * total_liq) / reserve1;
            liquidity = min(liq0, liq1);
        }}
        
        require(liquidity >= min_liquidity, "Insufficient liquidity minted");
        
        self.reserves[pool_id] = (reserve0 + amount0, reserve1 + amount1);
        self.total_liquidity[pool_id] = total_liq + liquidity;
        self.liquidity_positions[pool_id][msg.sender] += liquidity;
        
        emit LiquidityAdded {{ 
            pool_id: pool_id, 
            provider: msg.sender, 
            amount0: amount0, 
            amount1: amount1, 
            liquidity: liquidity 
        }};
        
        return liquidity;
    }}

    // Remove liquidity from pool
    fn remove_liquidity(pool_id: bytes32, liquidity: u256, min_amount0: u256, min_amount1: u256) -> (u256, u256) {{
        let (token0, token1) = self.tokens[pool_id];
        require(token0 != address(0), "Pool does not exist");
        require(self.liquidity_positions[pool_id][msg.sender] >= liquidity, "Insufficient liquidity");
        
        let (reserve0, reserve1) = self.reserves[pool_id];
        let total_liq = self.total_liquidity[pool_id];
        
        let amount0 = (liquidity * reserve0) / total_liq;
        let amount1 = (liquidity * reserve1) / total_liq;
        
        require(amount0 >= min_amount0 && amount1 >= min_amount1, "Slippage exceeded");
        
        self.liquidity_positions[pool_id][msg.sender] -= liquidity;
        self.total_liquidity[pool_id] -= liquidity;
        self.reserves[pool_id] = (reserve0 - amount0, reserve1 - amount1);
        
        // Transfer tokens to user
        ERC20(token0).transfer(msg.sender, amount0);
        ERC20(token1).transfer(msg.sender, amount1);
        
        emit LiquidityRemoved {{ 
            pool_id: pool_id, 
            provider: msg.sender, 
            amount0: amount0, 
            amount1: amount1, 
            liquidity: liquidity 
        }};
        
        return (amount0, amount1);
    }}

    // Swap tokens using constant product formula
    fn swap(pool_id: bytes32, token_in: address, amount_in: u256, min_amount_out: u256) -> u256 {{
        let (token0, token1) = self.tokens[pool_id];
        require(token_in == token0 || token_in == token1, "Invalid token");
        
        let (reserve0, reserve1) = self.reserves[pool_id];
        let (reserve_in, reserve_out, token_out) = if token_in == token0 {{
            (reserve0, reserve1, token1)
        }} else {{
            (reserve1, reserve0, token0)
        }};
        
        // Apply fee
        let amount_in_with_fee = amount_in * (10000 - u256(self.fee_basis_points)) / 10000;
        
        // Calculate output using x * y = k
        let amount_out = (amount_in_with_fee * reserve_out) / (reserve_in + amount_in_with_fee);
        require(amount_out >= min_amount_out, "Slippage exceeded");
        
        // Transfer tokens
        ERC20(token_in).transfer_from(msg.sender, address(this), amount_in);
        ERC20(token_out).transfer(msg.sender, amount_out);
        
        // Update reserves
        if token_in == token0 {{
            self.reserves[pool_id] = (reserve0 + amount_in, reserve1 - amount_out);
        }} else {{
            self.reserves[pool_id] = (reserve0 - amount_out, reserve1 + amount_in);
        }}
        
        emit Swap {{ 
            pool_id: pool_id, 
            trader: msg.sender, 
            amount_in: amount_in, 
            amount_out: amount_out, 
            token_in: token_in, 
            token_out: token_out 
        }};
        
        return amount_out;
    }}

    // View functions
    fn get_reserves(pool_id: bytes32) -> (u256, u256) {{
        return self.reserves[pool_id];
    }}

    fn get_quote(pool_id: bytes32, token_in: address, amount_in: u256) -> u256 {{
        let (token0, _) = self.tokens[pool_id];
        let (reserve0, reserve1) = self.reserves[pool_id];
        let (reserve_in, reserve_out) = if token_in == token0 {{
            (reserve0, reserve1)
        }} else {{
            (reserve1, reserve0)
        }};
        
        let amount_in_with_fee = amount_in * (10000 - u256(self.fee_basis_points)) / 10000;
        return (amount_in_with_fee * reserve_out) / (reserve_in + amount_in_with_fee);
    }}

    fn get_liquidity(pool_id: bytes32, provider: address) -> u256 {{
        return self.liquidity_positions[pool_id][provider];
    }}

    // Helper functions
    fn sqrt(x: u256) -> u256 {{
        if x == 0 {{ return 0; }}
        let mut z = (x + 1) / 2;
        let mut y = x;
        while z < y {{
            y = z;
            z = (x / z + z) / 2;
        }}
        return y;
    }}

    fn min(a: u256, b: u256) -> u256 {{
        return if a < b {{ a }} else {{ b }};
    }}
}}
"#
        )
    }

    /// Get Vault/Staking template
    pub fn vault(name: &str, lock_days: u32, target_apy_bps: u16) -> String {
        format!(
            r#"// X3 Vault Contract: {name}
// Auto-generated by Voice-to-X3

contract {name} {{
    // Storage
    storage {{
        staking_token: address;
        reward_token: address;
        lock_period: u64 = {lock_days} * 86400; // in seconds
        reward_rate: u256; // rewards per second per token staked
        total_staked: u256 = 0;
        reward_per_token_stored: u256 = 0;
        last_update_time: u64;
        owner: address;
        
        // User data
        stakes: map<address, u256>;
        stake_timestamps: map<address, u64>;
        rewards_paid: map<address, u256>;
        user_reward_per_token: map<address, u256>;
    }}

    // Events
    event Staked {{
        user: address indexed;
        amount: u256;
        timestamp: u64;
    }}

    event Withdrawn {{
        user: address indexed;
        amount: u256;
    }}

    event RewardClaimed {{
        user: address indexed;
        amount: u256;
    }}

    // Constructor
    fn init(owner: address, staking_token: address, reward_token: address, rewards_per_year: u256) {{
        self.owner = owner;
        self.staking_token = staking_token;
        self.reward_token = reward_token;
        self.reward_rate = rewards_per_year / 31536000; // per second
        self.last_update_time = block.timestamp;
    }}

    // Modifiers (implemented as internal checks)
    fn _update_reward(account: address) {{
        self.reward_per_token_stored = self.reward_per_token();
        self.last_update_time = block.timestamp;
        
        if account != address(0) {{
            self.rewards_paid[account] = self.earned(account);
            self.user_reward_per_token[account] = self.reward_per_token_stored;
        }}
    }}

    // View functions
    fn reward_per_token() -> u256 {{
        if self.total_staked == 0 {{
            return self.reward_per_token_stored;
        }}
        
        let time_delta = block.timestamp - self.last_update_time;
        return self.reward_per_token_stored + (u256(time_delta) * self.reward_rate * 1e18) / self.total_staked;
    }}

    fn earned(account: address) -> u256 {{
        let stake = self.stakes[account];
        let reward_per_token_delta = self.reward_per_token() - self.user_reward_per_token[account];
        return (stake * reward_per_token_delta) / 1e18 + self.rewards_paid[account];
    }}

    fn get_stake(account: address) -> u256 {{
        return self.stakes[account];
    }}

    fn can_withdraw(account: address) -> bool {{
        let stake_time = self.stake_timestamps[account];
        return stake_time > 0 && block.timestamp >= stake_time + self.lock_period;
    }}

    fn time_until_unlock(account: address) -> u64 {{
        let stake_time = self.stake_timestamps[account];
        if stake_time == 0 {{ return 0; }}
        
        let unlock_time = stake_time + self.lock_period;
        if block.timestamp >= unlock_time {{ return 0; }}
        
        return unlock_time - block.timestamp;
    }}

    // Stake tokens
    fn stake(amount: u256) {{
        require(amount > 0, "Cannot stake zero");
        
        self._update_reward(msg.sender);
        
        // Transfer staking tokens from user
        ERC20(self.staking_token).transfer_from(msg.sender, address(this), amount);
        
        self.stakes[msg.sender] += amount;
        self.total_staked += amount;
        
        // Reset lock timer if this is a new stake
        if self.stake_timestamps[msg.sender] == 0 {{
            self.stake_timestamps[msg.sender] = block.timestamp;
        }}
        
        emit Staked {{ user: msg.sender, amount: amount, timestamp: block.timestamp }};
    }}

    // Withdraw staked tokens
    fn withdraw(amount: u256) {{
        require(amount > 0, "Cannot withdraw zero");
        require(self.stakes[msg.sender] >= amount, "Insufficient stake");
        require(self.can_withdraw(msg.sender), "Lock period not ended");
        
        self._update_reward(msg.sender);
        
        self.stakes[msg.sender] -= amount;
        self.total_staked -= amount;
        
        // Reset timestamp if fully withdrawn
        if self.stakes[msg.sender] == 0 {{
            self.stake_timestamps[msg.sender] = 0;
        }}
        
        // Transfer staking tokens back to user
        ERC20(self.staking_token).transfer(msg.sender, amount);
        
        emit Withdrawn {{ user: msg.sender, amount: amount }};
    }}

    // Claim accumulated rewards
    fn claim_rewards() {{
        self._update_reward(msg.sender);
        
        let reward = self.rewards_paid[msg.sender];
        require(reward > 0, "No rewards to claim");
        
        self.rewards_paid[msg.sender] = 0;
        
        // Transfer reward tokens to user
        ERC20(self.reward_token).transfer(msg.sender, reward);
        
        emit RewardClaimed {{ user: msg.sender, amount: reward }};
    }}

    // Emergency withdraw (forfeits rewards, owner only can enable)
    fn emergency_withdraw() {{
        let stake = self.stakes[msg.sender];
        require(stake > 0, "No stake");
        
        self.stakes[msg.sender] = 0;
        self.stake_timestamps[msg.sender] = 0;
        self.rewards_paid[msg.sender] = 0;
        self.total_staked -= stake;
        
        ERC20(self.staking_token).transfer(msg.sender, stake);
        
        emit Withdrawn {{ user: msg.sender, amount: stake }};
    }}

    // Admin functions
    fn set_reward_rate(rewards_per_year: u256) {{
        require(msg.sender == self.owner, "Only owner");
        self._update_reward(address(0));
        self.reward_rate = rewards_per_year / 31536000;
    }}

    fn fund_rewards(amount: u256) {{
        require(msg.sender == self.owner, "Only owner");
        ERC20(self.reward_token).transfer_from(msg.sender, address(this), amount);
    }}
}}
"#
        )
    }

    /// Get Governance/DAO template
    pub fn governance(name: &str, quorum_percent: u8, voting_period_days: u32) -> String {
        let voting_period_seconds = voting_period_days * 86400;
        format!(
            r#"// X3 Governance Contract: {name}
// Auto-generated by Voice-to-X3

contract {name} {{
    // Storage
    storage {{
        governance_token: address;
        quorum_percent: u8 = {quorum_percent};
        voting_period: u64 = {voting_period_seconds};
        proposal_count: u256 = 0;
        
        proposals: map<u256, Proposal>;
        votes: map<u256, map<address, Vote>>;
        executed: map<u256, bool>;
    }}

    // Types
    struct Proposal {{
        id: u256;
        proposer: address;
        title: string;
        description: string;
        target: address;
        calldata: bytes;
        value: u256;
        start_time: u64;
        end_time: u64;
        for_votes: u256;
        against_votes: u256;
        abstain_votes: u256;
        canceled: bool;
    }}

    struct Vote {{
        has_voted: bool;
        support: u8; // 0=against, 1=for, 2=abstain
        weight: u256;
    }}

    // Events
    event ProposalCreated {{
        proposal_id: u256 indexed;
        proposer: address indexed;
        title: string;
    }}

    event Voted {{
        proposal_id: u256 indexed;
        voter: address indexed;
        support: u8;
        weight: u256;
    }}

    event ProposalExecuted {{
        proposal_id: u256 indexed;
    }}

    event ProposalCanceled {{
        proposal_id: u256 indexed;
    }}

    // Constructor
    fn init(governance_token: address) {{
        self.governance_token = governance_token;
    }}

    // Create a new proposal
    fn propose(
        title: string, 
        description: string, 
        target: address, 
        calldata: bytes,
        value: u256
    ) -> u256 {{
        let voting_power = ERC20(self.governance_token).balance_of(msg.sender);
        require(voting_power > 0, "No voting power");
        
        self.proposal_count += 1;
        let proposal_id = self.proposal_count;
        
        self.proposals[proposal_id] = Proposal {{
            id: proposal_id,
            proposer: msg.sender,
            title: title,
            description: description,
            target: target,
            calldata: calldata,
            value: value,
            start_time: block.timestamp,
            end_time: block.timestamp + self.voting_period,
            for_votes: 0,
            against_votes: 0,
            abstain_votes: 0,
            canceled: false
        }};
        
        emit ProposalCreated {{ proposal_id: proposal_id, proposer: msg.sender, title: title }};
        return proposal_id;
    }}

    // Cast a vote
    fn vote(proposal_id: u256, support: u8) {{
        let proposal = self.proposals[proposal_id];
        require(!proposal.canceled, "Proposal canceled");
        require(block.timestamp >= proposal.start_time, "Voting not started");
        require(block.timestamp <= proposal.end_time, "Voting ended");
        require(!self.votes[proposal_id][msg.sender].has_voted, "Already voted");
        require(support <= 2, "Invalid support value");
        
        let weight = ERC20(self.governance_token).balance_of(msg.sender);
        require(weight > 0, "No voting power");
        
        self.votes[proposal_id][msg.sender] = Vote {{
            has_voted: true,
            support: support,
            weight: weight
        }};
        
        if support == 0 {{
            self.proposals[proposal_id].against_votes += weight;
        }} else if support == 1 {{
            self.proposals[proposal_id].for_votes += weight;
        }} else {{
            self.proposals[proposal_id].abstain_votes += weight;
        }}
        
        emit Voted {{ proposal_id: proposal_id, voter: msg.sender, support: support, weight: weight }};
    }}

    // Execute a passed proposal
    fn execute(proposal_id: u256) {{
        let proposal = self.proposals[proposal_id];
        require(!proposal.canceled, "Proposal canceled");
        require(block.timestamp > proposal.end_time, "Voting not ended");
        require(!self.executed[proposal_id], "Already executed");
        require(self._has_passed(proposal_id), "Proposal did not pass");
        
        self.executed[proposal_id] = true;
        
        // Execute the proposal
        (bool success, ) = proposal.target.call{{value: proposal.value}}(proposal.calldata);
        require(success, "Execution failed");
        
        emit ProposalExecuted {{ proposal_id: proposal_id }};
    }}

    // Cancel a proposal (proposer only)
    fn cancel(proposal_id: u256) {{
        let proposal = self.proposals[proposal_id];
        require(msg.sender == proposal.proposer, "Only proposer can cancel");
        require(!self.executed[proposal_id], "Already executed");
        
        self.proposals[proposal_id].canceled = true;
        
        emit ProposalCanceled {{ proposal_id: proposal_id }};
    }}

    // View functions
    fn get_proposal(proposal_id: u256) -> Proposal {{
        return self.proposals[proposal_id];
    }}

    fn get_vote(proposal_id: u256, voter: address) -> Vote {{
        return self.votes[proposal_id][voter];
    }}

    fn state(proposal_id: u256) -> string {{
        let proposal = self.proposals[proposal_id];
        
        if proposal.canceled {{
            return "Canceled";
        }}
        if self.executed[proposal_id] {{
            return "Executed";
        }}
        if block.timestamp < proposal.start_time {{
            return "Pending";
        }}
        if block.timestamp <= proposal.end_time {{
            return "Active";
        }}
        if self._has_passed(proposal_id) {{
            return "Succeeded";
        }}
        return "Defeated";
    }}

    fn _has_passed(proposal_id: u256) -> bool {{
        let proposal = self.proposals[proposal_id];
        let total_supply = ERC20(self.governance_token).total_supply();
        let total_votes = proposal.for_votes + proposal.against_votes + proposal.abstain_votes;
        
        // Check quorum
        let quorum = (total_supply * u256(self.quorum_percent)) / 100;
        if total_votes < quorum {{
            return false;
        }}
        
        // Check majority
        return proposal.for_votes > proposal.against_votes;
    }}
}}
"#
        )
    }
}
