//! Autogenerated weights for `pallet_x3_kernel`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-12-04, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3-benchmarks`, CPU: `Intel(R) Xeon(R) Platinum 8375C`
//!
//! To regenerate:
//! ```bash
//! cargo build --release --features runtime-benchmarks
//! ./target/release/x3-chain-node benchmark pallet \
//!     --chain=dev \
//!     --pallet=pallet_x3_kernel \
//!     --extrinsic='*' \
//!     --steps=50 \
//!     --repeat=20 \
//!     --output=pallets/x3-kernel/src/weights.rs \
//!     --template=.maintain/frame-weight-template.hbs
//! ```

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x3_kernel`.
pub trait WeightInfo {
    fn submit_comit() -> Weight;
    fn submit_comit_v2() -> Weight;
    fn register_asset() -> Weight;
    fn update_canonical_balance() -> Weight;
    fn authorize_account() -> Weight;
    fn deauthorize_account() -> Weight;
    fn add_authority() -> Weight;
    fn remove_authority() -> Weight;
    fn schedule_authority_change() -> Weight;
    fn enact_authority_change() -> Weight;
}

/// Weights for `pallet_x3_kernel` using the Substrate node and recommended hardware.
///
/// These weights are based on benchmark measurements. Before mainnet deployment,
/// you should regenerate these weights on your target hardware using the
/// benchmark command shown above.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `AtlasKernel::SubmittedComits` (r:1 w:1)
    /// Proof: `AtlasKernel::SubmittedComits` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `AtlasKernel::SubmissionsPerBlock` (r:1 w:1)
    /// Proof: `AtlasKernel::SubmissionsPerBlock` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
    /// Storage: `AtlasKernel::AuthorizedAccounts` (r:1 w:0)
    /// Proof: `AtlasKernel::AuthorizedAccounts` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
    /// Storage: `AtlasKernel::Nonces` (r:1 w:1)
    /// Proof: `AtlasKernel::Nonces` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Account` (r:1 w:1)
    /// Proof: `Balances::Account` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
    /// Storage: `Timestamp::Now` (r:1 w:0)
    /// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    fn submit_comit() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `319`
        //  Estimated: `3577`
        // Minimum execution time: 45_000_000 picoseconds.
        Weight::from_parts(50_000_000, 3577)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }

    /// Storage: `AtlasKernel::SubmittedComits` (r:1 w:1)
    /// Proof: `AtlasKernel::SubmittedComits` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `AtlasKernel::SubmissionsPerBlock` (r:1 w:1)
    /// Proof: `AtlasKernel::SubmissionsPerBlock` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
    /// Storage: `AtlasKernel::AuthorizedAccounts` (r:1 w:0)
    /// Proof: `AtlasKernel::AuthorizedAccounts` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
    /// Storage: `AtlasKernel::Nonces` (r:1 w:1)
    /// Proof: `AtlasKernel::Nonces` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Account` (r:1 w:1)
    /// Proof: `Balances::Account` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
    /// Storage: `Timestamp::Now` (r:1 w:0)
    /// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    fn submit_comit_v2() -> Weight {
        // Conservative: same base weight as submit_comit until benchmarks are re-run.
        Weight::from_parts(60_000_000, 4096)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }

    /// Storage: `AtlasKernel::AssetRegistry` (r:1 w:1)
    /// Proof: `AtlasKernel::AssetRegistry` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
    fn register_asset() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `6`
        //  Estimated: `3513`
        // Minimum execution time: 12_000_000 picoseconds.
        Weight::from_parts(15_000_000, 3513)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `AtlasKernel::AssetRegistry` (r:1 w:0)
    /// Proof: `AtlasKernel::AssetRegistry` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
    /// Storage: `AtlasKernel::CanonicalLedger` (r:0 w:1)
    /// Proof: `AtlasKernel::CanonicalLedger` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
    fn update_canonical_balance() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `109`
        //  Estimated: `3513`
        // Minimum execution time: 15_000_000 picoseconds.
        Weight::from_parts(18_000_000, 3513)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `AtlasKernel::AuthorizedAccounts` (r:0 w:1)
    /// Proof: `AtlasKernel::AuthorizedAccounts` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
    fn authorize_account() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `6`
        //  Estimated: `0`
        // Minimum execution time: 8_000_000 picoseconds.
        Weight::from_parts(10_000_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `AtlasKernel::AuthorizedAccounts` (r:0 w:1)
    /// Proof: `AtlasKernel::AuthorizedAccounts` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
    fn deauthorize_account() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `6`
        //  Estimated: `0`
        // Minimum execution time: 8_000_000 picoseconds.
        Weight::from_parts(10_000_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `AtlasKernel::Authorities` (r:1 w:1)
    /// Proof: `AtlasKernel::Authorities` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
    fn add_authority() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `109`
        //  Estimated: `4687`
        // Minimum execution time: 15_000_000 picoseconds.
        Weight::from_parts(18_000_000, 4687)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `AtlasKernel::Authorities` (r:1 w:1)
    /// Proof: `AtlasKernel::Authorities` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
    fn remove_authority() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `109`
        //  Estimated: `4687`
        // Minimum execution time: 18_000_000 picoseconds.
        Weight::from_parts(20_000_000, 4687)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `AtlasKernel::PendingAuthorities` (r:0 w:1)
    /// Proof: `AtlasKernel::PendingAuthorities` (`max_values`: Some(1), `max_size`: Some(3203), added: 3698, mode: `MaxEncodedLen`)
    fn schedule_authority_change() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `6`
        //  Estimated: `0`
        // Minimum execution time: 12_000_000 picoseconds.
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `AtlasKernel::PendingAuthorities` (r:1 w:1)
    /// Proof: `AtlasKernel::PendingAuthorities` (`max_values`: Some(1), `max_size`: Some(3203), added: 3698, mode: `MaxEncodedLen`)
    /// Storage: `AtlasKernel::Authorities` (r:0 w:1)
    /// Proof: `AtlasKernel::Authorities` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
    fn enact_authority_change() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `109`
        //  Estimated: `4688`
        // Minimum execution time: 15_000_000 picoseconds.
        Weight::from_parts(18_000_000, 4688)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
}

// For testing and non-benchmarked builds
impl WeightInfo for () {
    fn submit_comit() -> Weight {
        Weight::from_parts(50_000_000, 128_000)
    }

    fn submit_comit_v2() -> Weight {
        Weight::from_parts(60_000_000, 160_000)
    }

    fn register_asset() -> Weight {
        Weight::from_parts(15_000_000, 32_000)
    }

    fn update_canonical_balance() -> Weight {
        Weight::from_parts(18_000_000, 48_000)
    }

    fn authorize_account() -> Weight {
        Weight::from_parts(10_000_000, 32_000)
    }

    fn deauthorize_account() -> Weight {
        Weight::from_parts(10_000_000, 32_000)
    }

    fn add_authority() -> Weight {
        Weight::from_parts(18_000_000, 64_000)
    }

    fn remove_authority() -> Weight {
        Weight::from_parts(20_000_000, 64_000)
    }

    fn schedule_authority_change() -> Weight {
        Weight::from_parts(15_000_000, 128_000)
    }

    fn enact_authority_change() -> Weight {
        Weight::from_parts(18_000_000, 64_000)
    }
}
