// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_northern_swarm`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `x3star1`, CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/lojak/Desktop/xxxstar-main/target/release/x3-chain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet-northern-swarm
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// /home/lojak/Desktop/xxxstar-main/.maintain/frame-weight-template.hbs
// --output
// /home/lojak/Desktop/xxxstar-main/pallets/northern-swarm/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_northern_swarm`.
pub trait WeightInfo {
	fn register_executor() -> Weight;
	fn deregister_executor() -> Weight;
	fn release_stake() -> Weight;
	fn submit_heartbeat() -> Weight;
	fn submit_task() -> Weight;
	fn claim_task() -> Weight;
	fn submit_result() -> Weight;
	fn slash_executor() -> Weight;
}

/// Weights for `pallet_northern_swarm` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `NorthernSwarm::Executors` (r:1 w:1)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	fn register_executor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3567`
		// Minimum execution time: 77_885_000 picoseconds.
		Weight::from_parts(78_998_000, 3567)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NorthernSwarm::Executors` (r:1 w:1)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::ClaimedTaskCount` (r:1 w:0)
	/// Proof: `NorthernSwarm::ClaimedTaskCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn deregister_executor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `267`
		//  Estimated: `3567`
		// Minimum execution time: 49_281_000 picoseconds.
		Weight::from_parts(54_903_000, 3567)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NorthernSwarm::Executors` (r:1 w:1)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	fn release_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `271`
		//  Estimated: `3567`
		// Minimum execution time: 78_050_000 picoseconds.
		Weight::from_parts(79_872_000, 3567)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NorthernSwarm::Executors` (r:1 w:1)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	fn submit_heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `267`
		//  Estimated: `3567`
		// Minimum execution time: 44_140_000 picoseconds.
		Weight::from_parts(45_046_000, 3567)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NorthernSwarm::Tasks` (r:0 w:1)
	/// Proof: `NorthernSwarm::Tasks` (`max_values`: None, `max_size`: Some(684), added: 3159, mode: `MaxEncodedLen`)
	fn submit_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 71_663_000 picoseconds.
		Weight::from_parts(72_396_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NorthernSwarm::Executors` (r:1 w:0)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::TaskClaims` (r:1 w:1)
	/// Proof: `NorthernSwarm::TaskClaims` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::ClaimedTaskCount` (r:1 w:1)
	/// Proof: `NorthernSwarm::ClaimedTaskCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::TaskClaimSlots` (r:1 w:1)
	/// Proof: `NorthernSwarm::TaskClaimSlots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::Tasks` (r:1 w:1)
	/// Proof: `NorthernSwarm::Tasks` (`max_values`: None, `max_size`: Some(684), added: 3159, mode: `MaxEncodedLen`)
	fn claim_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `421`
		//  Estimated: `4149`
		// Minimum execution time: 83_984_000 picoseconds.
		Weight::from_parts(85_441_000, 4149)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `NorthernSwarm::Executors` (r:1 w:0)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::TaskClaims` (r:2 w:1)
	/// Proof: `NorthernSwarm::TaskClaims` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::ResultCommits` (r:4 w:1)
	/// Proof: `NorthernSwarm::ResultCommits` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::Tasks` (r:1 w:1)
	/// Proof: `NorthernSwarm::Tasks` (`max_values`: None, `max_size`: Some(684), added: 3159, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::ClaimedTaskCount` (r:1 w:1)
	/// Proof: `NorthernSwarm::ClaimedTaskCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::TaskClaimSlots` (r:0 w:1)
	/// Proof: `NorthernSwarm::TaskClaimSlots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn submit_result() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1043`
		//  Estimated: `11402`
		// Minimum execution time: 217_548_000 picoseconds.
		Weight::from_parts(224_325_000, 11402)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `NorthernSwarm::Executors` (r:1 w:1)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn slash_executor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `407`
		//  Estimated: `3593`
		// Minimum execution time: 92_294_000 picoseconds.
		Weight::from_parts(93_462_000, 3593)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `NorthernSwarm::Executors` (r:1 w:1)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	fn register_executor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3567`
		// Minimum execution time: 77_885_000 picoseconds.
		Weight::from_parts(78_998_000, 3567)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NorthernSwarm::Executors` (r:1 w:1)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::ClaimedTaskCount` (r:1 w:0)
	/// Proof: `NorthernSwarm::ClaimedTaskCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn deregister_executor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `267`
		//  Estimated: `3567`
		// Minimum execution time: 49_281_000 picoseconds.
		Weight::from_parts(54_903_000, 3567)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NorthernSwarm::Executors` (r:1 w:1)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	fn release_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `271`
		//  Estimated: `3567`
		// Minimum execution time: 78_050_000 picoseconds.
		Weight::from_parts(79_872_000, 3567)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NorthernSwarm::Executors` (r:1 w:1)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	fn submit_heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `267`
		//  Estimated: `3567`
		// Minimum execution time: 44_140_000 picoseconds.
		Weight::from_parts(45_046_000, 3567)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NorthernSwarm::Tasks` (r:0 w:1)
	/// Proof: `NorthernSwarm::Tasks` (`max_values`: None, `max_size`: Some(684), added: 3159, mode: `MaxEncodedLen`)
	fn submit_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 71_663_000 picoseconds.
		Weight::from_parts(72_396_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NorthernSwarm::Executors` (r:1 w:0)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::TaskClaims` (r:1 w:1)
	/// Proof: `NorthernSwarm::TaskClaims` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::ClaimedTaskCount` (r:1 w:1)
	/// Proof: `NorthernSwarm::ClaimedTaskCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::TaskClaimSlots` (r:1 w:1)
	/// Proof: `NorthernSwarm::TaskClaimSlots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::Tasks` (r:1 w:1)
	/// Proof: `NorthernSwarm::Tasks` (`max_values`: None, `max_size`: Some(684), added: 3159, mode: `MaxEncodedLen`)
	fn claim_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `421`
		//  Estimated: `4149`
		// Minimum execution time: 83_984_000 picoseconds.
		Weight::from_parts(85_441_000, 4149)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `NorthernSwarm::Executors` (r:1 w:0)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::TaskClaims` (r:2 w:1)
	/// Proof: `NorthernSwarm::TaskClaims` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::ResultCommits` (r:4 w:1)
	/// Proof: `NorthernSwarm::ResultCommits` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::Tasks` (r:1 w:1)
	/// Proof: `NorthernSwarm::Tasks` (`max_values`: None, `max_size`: Some(684), added: 3159, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::ClaimedTaskCount` (r:1 w:1)
	/// Proof: `NorthernSwarm::ClaimedTaskCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NorthernSwarm::TaskClaimSlots` (r:0 w:1)
	/// Proof: `NorthernSwarm::TaskClaimSlots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn submit_result() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1043`
		//  Estimated: `11402`
		// Minimum execution time: 217_548_000 picoseconds.
		Weight::from_parts(224_325_000, 11402)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `NorthernSwarm::Executors` (r:1 w:1)
	/// Proof: `NorthernSwarm::Executors` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn slash_executor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `407`
		//  Estimated: `3593`
		// Minimum execution time: 92_294_000 picoseconds.
		Weight::from_parts(93_462_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
