//! X3 bytecode code generator: lowers IR to X3 bytecode.
//!
//! Takes an IrModule after optimization and produces a flat bytecode sequence
//! compatible with the X3VM bytecode format.

use crate::ir::{IrBinOp, IrFunction, IrInstr, IrModule};
use std::collections::BTreeMap;

/// A single bytecode instruction (opcode + operand).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CodegenInstr {
    pub opcode: u8,
    pub operand: u32,
}

impl CodegenInstr {
    pub fn new(opcode: u8, operand: u32) -> Self {
        Self { opcode, operand }
    }
}

/// Bytecode opcodes (subset used by codegen).
pub mod op {
    pub const NOP: u8 = 0x00;
    pub const LD_CONST: u8 = 0x01;
    pub const ADD: u8 = 0x10;
    pub const SUB: u8 = 0x11;
    pub const MUL: u8 = 0x12;
    pub const DIV: u8 = 0x13;
    pub const CMP_EQ: u8 = 0x14;
    pub const CMP_NE: u8 = 0x15;
    pub const CMP_LT: u8 = 0x16;
    pub const CMP_GT: u8 = 0x17;
    pub const JUMP: u8 = 0x20;
    pub const JUMP_Z: u8 = 0x21;
    pub const CALL: u8 = 0x30;
    pub const RET: u8 = 0x31;
    pub const HALT: u8 = 0xFF;
}

/// Errors from codegen.
#[derive(Debug, PartialEq, Eq)]
pub enum CodegenError {
    /// Block referenced but not found.
    UnknownBlock(u32),
    /// Function referenced but not found.
    UnknownFunction(String),
    /// Empty function body.
    EmptyFunction(String),
}

/// Generated bytecode for a single function.
#[derive(Clone, Debug, Default)]
pub struct FunctionCode {
    pub name: String,
    pub instructions: Vec<CodegenInstr>,
    pub const_pool: Vec<i64>,
}

/// Lower an IrFunction to FunctionCode.
pub fn codegen_function(func: &IrFunction) -> Result<FunctionCode, CodegenError> {
    let mut code = FunctionCode {
        name: func.name.clone(),
        ..Default::default()
    };

    // Process blocks in order (entry first, then the rest by block ID)
    let mut block_ids: Vec<_> = func.blocks.keys().copied().collect();
    block_ids.sort();
    // Move entry to front
    block_ids.retain(|&b| b != func.entry);
    let ordered: Vec<_> = std::iter::once(func.entry).chain(block_ids).collect();

    if ordered.is_empty() {
        return Err(CodegenError::EmptyFunction(func.name.clone()));
    }

    for &bid in &ordered {
        if let Some(block) = func.blocks.get(&bid) {
            for instr in &block.instrs {
                match instr {
                    IrInstr::Const { val, .. } => {
                        let idx = code.const_pool.len() as u32;
                        code.const_pool.push(*val);
                        code.instructions.push(CodegenInstr::new(op::LD_CONST, idx));
                    }
                    IrInstr::BinOp { op: binop, .. } => {
                        let opcode = match binop {
                            IrBinOp::Add => op::ADD,
                            IrBinOp::Sub => op::SUB,
                            IrBinOp::Mul => op::MUL,
                            IrBinOp::Div => op::DIV,
                            IrBinOp::CmpEq => op::CMP_EQ,
                            IrBinOp::CmpNe => op::CMP_NE,
                            IrBinOp::CmpLt => op::CMP_LT,
                            IrBinOp::CmpGt => op::CMP_GT,
                        };
                        code.instructions.push(CodegenInstr::new(opcode, 0));
                    }
                    IrInstr::Return { .. } => {
                        code.instructions.push(CodegenInstr::new(op::RET, 0));
                    }
                    IrInstr::Nop => {
                        code.instructions.push(CodegenInstr::new(op::NOP, 0));
                    }
                    IrInstr::Jump { target } => {
                        code.instructions
                            .push(CodegenInstr::new(op::JUMP, target.0));
                    }
                    IrInstr::Branch { true_target, .. } => {
                        code.instructions
                            .push(CodegenInstr::new(op::JUMP_Z, true_target.0));
                    }
                    IrInstr::Call { func: fname, .. } => {
                        code.instructions.push(CodegenInstr::new(op::CALL, 0));
                    }
                    _ => {
                        code.instructions.push(CodegenInstr::new(op::NOP, 0));
                    }
                }
            }
        }
    }

    if code.instructions.is_empty() {
        code.instructions.push(CodegenInstr::new(op::RET, 0));
    }

    Ok(code)
}

/// Lower an entire IrModule to a list of FunctionCodes.
pub fn codegen_module(module: &IrModule) -> Result<Vec<FunctionCode>, CodegenError> {
    module.functions.iter().map(codegen_function).collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{IrBinOp, IrFunction, IrInstr, IrType};

    fn const_add_fn() -> IrFunction {
        let mut f = IrFunction::new("add_consts", IrType::I64);
        let entry = f.entry;
        let a = f.new_val();
        let b = f.new_val();
        let c = f.new_val();
        f.push(entry, IrInstr::Const { dst: a, val: 5 });
        f.push(entry, IrInstr::Const { dst: b, val: 7 });
        f.push(
            entry,
            IrInstr::BinOp {
                dst: c,
                op: IrBinOp::Add,
                lhs: a,
                rhs: b,
            },
        );
        f.push(entry, IrInstr::Return { val: Some(c) });
        f
    }

    #[test]
    fn test_codegen_produces_instructions() {
        let f = const_add_fn();
        let code = codegen_function(&f).unwrap();
        assert!(!code.instructions.is_empty());
    }

    #[test]
    fn test_codegen_ld_const_for_constants() {
        let f = const_add_fn();
        let code = codegen_function(&f).unwrap();
        let ld_count = code
            .instructions
            .iter()
            .filter(|i| i.opcode == op::LD_CONST)
            .count();
        assert_eq!(ld_count, 2);
    }

    #[test]
    fn test_codegen_ends_with_ret() {
        let f = const_add_fn();
        let code = codegen_function(&f).unwrap();
        assert_eq!(code.instructions.last().unwrap().opcode, op::RET);
    }

    #[test]
    fn test_codegen_const_pool_populated() {
        let f = const_add_fn();
        let code = codegen_function(&f).unwrap();
        assert!(code.const_pool.contains(&5));
        assert!(code.const_pool.contains(&7));
    }

    #[test]
    fn test_codegen_add_opcode() {
        let f = const_add_fn();
        let code = codegen_function(&f).unwrap();
        assert!(code.instructions.iter().any(|i| i.opcode == op::ADD));
    }

    #[test]
    fn test_codegen_empty_module() {
        let module = IrModule { functions: vec![] };
        let result = codegen_module(&module).unwrap();
        assert!(result.is_empty());
    }
}
