//! Autogenerated weights for pallet_x3_automation
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-04-29, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `x3-dev`, CPU: `AMD EPYC 7742`
//! EXECUTION: Some(WASM), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/x3 benchmark pallet --chain=dev --steps=50 --repeat=20 --pallet=pallet_x3_automation --extrinsic=* --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=./pallets/x3-automation/src/weights.rs --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_x3_automation.
pub trait WeightInfo {
	fn register_task() -> Weight;
	fn cancel_task() -> Weight;
	fn execute_task() -> Weight;
}

/// Weights for pallet_x3_automation using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `AccountTasks` (r:1 w:1)
	/// Proof: `AccountTasks` (`max_values`: None, `max_size`: Some(1032), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `TaskCounter` (r:1 w:1)
	/// Proof: `TaskCounter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Tasks` (r:0 w:1)
	/// Proof: `Tasks` (`max_values`: None, `max_size`: Some(285), added: 760, mode: `MaxEncodedLen`)
	fn register_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `75`
		//  Estimated: `3770`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(36_000_000, 3770)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Tasks` (r:1 w:1)
	/// Proof: `Tasks` (`max_values`: None, `max_size`: Some(285), added: 760, mode: `MaxEncodedLen`)
	/// Storage: `AccountTasks` (r:1 w:1)
	/// Proof: `AccountTasks` (`max_values`: None, `max_size`: Some(1032), added: 2507, mode: `MaxEncodedLen`)
	fn cancel_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `3267`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 3267)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Tasks` (r:1 w:1)
	/// Proof: `Tasks` (`max_values`: None, `max_size`: Some(285), added: 760, mode: `MaxEncodedLen`)
	/// Storage: `AccountTasks` (r:1 w:1)
	/// Proof: `AccountTasks` (`max_values`: None, `max_size`: Some(1032), added: 2507, mode: `MaxEncodedLen`)
	fn execute_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `3267`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(46_000_000, 3267)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `AccountTasks` (r:1 w:1)
	/// Proof: `AccountTasks` (`max_values`: None, `max_size`: Some(1032), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `TaskCounter` (r:1 w:1)
	/// Proof: `TaskCounter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Tasks` (r:0 w:1)
	/// Proof: `Tasks` (`max_values`: None, `max_size`: Some(285), added: 760, mode: `MaxEncodedLen`)
	fn register_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `75`
		//  Estimated: `3770`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(36_000_000, 3770)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Tasks` (r:1 w:1)
	/// Proof: `Tasks` (`max_values`: None, `max_size`: Some(285), added: 760, mode: `MaxEncodedLen`)
	/// Storage: `AccountTasks` (r:1 w:1)
	/// Proof: `AccountTasks` (`max_values`: None, `max_size`: Some(1032), added: 2507, mode: `MaxEncodedLen`)
	fn cancel_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `3267`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 3267)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Tasks` (r:1 w:1)
	/// Proof: `Tasks` (`max_values`: None, `max_size`: Some(285), added: 760, mode: `MaxEncodedLen`)
	/// Storage: `AccountTasks` (r:1 w:1)
	/// Proof: `AccountTasks` (`max_values`: None, `max_size`: Some(1032), added: 2507, mode: `MaxEncodedLen`)
	fn execute_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `3267`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(46_000_000, 3267)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}