//! GPU Bytecode Generator for X3 VM
//!
//! Generates X3 bytecode that dispatches to GPU hostcalls for cryptographic operations.
//! This module bridges the gap between DeterministicEngine tasks and X3 VM GPU execution.

use crate::crypto::HashAlgorithm;
use tracing::debug;
use x3_backend::bc_format::{
    BytecodeModule, ConstPool, FeatureFlags, FunctionEntry, ModuleFlags, VersionInfo,
};
use x3_backend::opcode::Opcode;

/// Generate X3 bytecode for a SHA-256 batch hash operation
///
/// Generated bytecode:
/// ```text
/// LoadConst r1, <inputs_const_idx>   ; r1 = inputs from const pool
/// LoadConst r2, <count>              ; r2 = batch count
/// GpuSha256Batch r0, r1, r2          ; r0 = gpu_sha256_batch(inputs, count)
/// Ret r0                             ; return r0
/// ```
pub fn generate_sha256_batch_bytecode(inputs: Vec<u8>, count: i64) -> BytecodeModule {
    let mut const_pool = ConstPool::new();
    let inputs_idx = const_pool
        .add_bytes(inputs)
        .map(|idx| idx.0) // Extract u32 from ConstIdx
        .unwrap_or(0);
    let count_idx = const_pool
        .add_integer(count)
        .map(|idx| idx.0) // Extract u32 from ConstIdx
        .unwrap_or(1);

    let mut code = Vec::new();

    // LoadConst r1, inputs_idx (2 bytes for opcode, 2 for register, 4 for idx = 8 bytes)
    code.push(Opcode::LoadConst.to_byte());
    code.extend_from_slice(&1u16.to_le_bytes());
    code.extend_from_slice(&inputs_idx.to_le_bytes());

    // LoadConst r2, count_idx (8 bytes)
    code.push(Opcode::LoadConst.to_byte());
    code.extend_from_slice(&2u16.to_le_bytes());
    code.extend_from_slice(&count_idx.to_le_bytes());

    // GpuSha256Batch r0, r1, r2 (4 bytes: opcode + 3 registers)
    code.push(Opcode::GpuSha256Batch.to_byte());
    code.push(0u8); // r0 (dst)
    code.push(1u8); // r1 (inputs)
    code.push(2u8); // r2 (count)

    // Ret r0 (2 bytes)
    code.push(Opcode::Ret.to_byte());
    code.push(0u8);

    BytecodeModule {
        version: VersionInfo::new(1, 0, 0),
        min_version: VersionInfo::new(1, 0, 0),
        flags: ModuleFlags::default(),
        features: FeatureFlags(0),
        const_pool,
        functions: vec![FunctionEntry {
            name: "gpu_sha256_batch".into(),
            entry_point: 0,
            param_count: 0,
            local_count: 0,
            max_stack: 0,
            return_type_tag: 1, // bytes
        }],
        globals: vec![],
        code,
        debug_info: None,
        metadata: None,
    }
}

/// Generate X3 bytecode for a Keccak-256 batch hash operation
pub fn generate_keccak256_batch_bytecode(inputs: Vec<u8>, count: i64) -> BytecodeModule {
    let mut const_pool = ConstPool::new();
    let inputs_idx = const_pool
        .add_bytes(inputs)
        .map(|idx| idx.0) // Extract u32 from ConstIdx
        .unwrap_or(0);
    let count_idx = const_pool
        .add_integer(count)
        .map(|idx| idx.0) // Extract u32 from ConstIdx
        .unwrap_or(1);

    let mut code = Vec::new();

    // LoadConst r1, inputs_idx
    code.push(Opcode::LoadConst.to_byte());
    code.extend_from_slice(&1u16.to_le_bytes());
    code.extend_from_slice(&inputs_idx.to_le_bytes());

    // LoadConst r2, count_idx
    code.push(Opcode::LoadConst.to_byte());
    code.extend_from_slice(&2u16.to_le_bytes());
    code.extend_from_slice(&count_idx.to_le_bytes());

    // GpuKeccak256Batch r0, r1, r2
    code.push(Opcode::GpuKeccak256Batch.to_byte());
    code.push(0u8); // r0 (dst)
    code.push(1u8); // r1 (inputs)
    code.push(2u8); // r2 (count)

    // Ret r0
    code.push(Opcode::Ret.to_byte());
    code.push(0u8);

    BytecodeModule {
        version: VersionInfo::new(1, 0, 0),
        min_version: VersionInfo::new(1, 0, 0),
        flags: ModuleFlags::default(),
        features: FeatureFlags(0),
        const_pool,
        functions: vec![FunctionEntry {
            name: "gpu_keccak256_batch".into(),
            entry_point: 0,
            param_count: 0,
            local_count: 0,
            max_stack: 0,
            return_type_tag: 1, // bytes
        }],
        globals: vec![],
        code,
        debug_info: None,
        metadata: None,
    }
}

/// Generate X3 GPU bytecode based on the algorithm
pub fn generate_gpu_bytecode_for_algorithm(
    algorithm: HashAlgorithm,
    inputs: Vec<u8>,
    count: i64,
) -> BytecodeModule {
    match algorithm {
        HashAlgorithm::Sha256 => generate_sha256_batch_bytecode(inputs, count),
        HashAlgorithm::Keccak256 => generate_keccak256_batch_bytecode(inputs, count),
        HashAlgorithm::Blake2b => {
            // Blake2b not available as GPU opcode, fallback to Keccak256
            debug!("[GPU Bytecode] Blake2b not available as GPU opcode, using Keccak256");
            generate_keccak256_batch_bytecode(inputs, count)
        }
    }
}
